### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by mbpakalin** [atom-minimap/minimap#275]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Microsoft     
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v4.2.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /c:/Users/mbpakalin/.atom/packages/minimap/lib/minimap-element.coffee:49

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.createdCallback (c:\Users\mbpakalin\.atom\packages\minimap\lib\minimap-element.coffee:35:36)
  at Object.createView (c:\Users\mbpakalin\.atom\packages\minimap\lib\minimap-element.coffee:487:15)
  at ViewRegistry.module.exports.ViewRegistry.createView (c:\Users\mbpakalin\AppData\Local\atom\app-0.165.0\resources\app\src\view-registry.js:61:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (c:\Users\mbpakalin\AppData\Local\atom\app-0.165.0\resources\app\src\view-registry.js:43:21)
  at c:\Users\mbpakalin\.atom\packages\minimap\lib\main.coffee:287:35
  at c:\Users\mbpakalin\AppData\Local\atom\app-0.165.0\resources\app\src\workspace.js:270:16
  at c:\Users\mbpakalin\AppData\Local\atom\app-0.165.0\resources\app\src\workspace.js:327:18
  at Emitter.module.exports.Emitter.emit (c:\Users\mbpakalin\AppData\Local\atom\app-0.165.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (c:\Users\mbpakalin\AppData\Local\atom\app-0.165.0\resources\app\src\pane-container.js:379:27)
  at c:\Users\mbpakalin\AppData\Local\atom\app-0.165.0\resources\app\src\pane-container.js:366:26
  at Emitter.module.exports.Emitter.emit (c:\Users\mbpakalin\AppData\Local\atom\app-0.165.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (c:\Users\mbpakalin\AppData\Local\atom\app-0.165.0\resources\app\src\pane.js:334:20)
  at Pane.module.exports.Pane.activateItem (c:\Users\mbpakalin\AppData\Local\atom\app-0.165.0\resources\app\src\pane.js:313:14)
  at c:\Users\mbpakalin\AppData\Local\atom\app-0.165.0\resources\app\src\workspace.js:494:16
  at _fulfilled (c:\Users\mbpakalin\AppData\Local\atom\app-0.165.0\resources\app\node_modules\q\q.js:787:54)
  at self.promiseDispatch.done (c:\Users\mbpakalin\AppData\Local\atom\app-0.165.0\resources\app\node_modules\q\q.js:816:30)
  at Promise.promise.promiseDispatch (c:\Users\mbpakalin\AppData\Local\atom\app-0.165.0\resources\app\node_modules\q\q.js:749:13)
  at c:\Users\mbpakalin\AppData\Local\atom\app-0.165.0\resources\app\node_modules\q\q.js:557:44
  at flush (c:\Users\mbpakalin\AppData\Local\atom\app-0.165.0\resources\app\node_modules\q\q.js:108:17)
  at process._tickCallback (node.js:378:11)

```

### Commands

```
  2x -5:15.6 core:backspace (input.hidden-input)
     -5:15.1 core:select-all (input.hidden-input)
     -5:14.9 core:backspace (input.hidden-input)
     -5:14.5 core:confirm (input.hidden-input)
     -5:02.1 core:select-all (input.hidden-input)
     -4:59.5 core:confirm (input.hidden-input)
     -2:14.1 core:backspace (div.settings-view.pane-item)
     -0:00.0 settings-view:install-packages (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.1.6
color-picker, v1.4.4
language-css-plus, v0.3.0
linter, v0.11.1
minimap, v4.2.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by fundon** [comment]
Update your Atom to the latest
