### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by sriki18** [atom-minimap/minimap#278]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.157.0
**System**: linux 3.16.0-30-generic
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.3.0

### Steps To Reproduce

1. I just toggled the minimap from packages menu, and this happened. 
2. ...

### Stack Trace

```
At /home/codebox/.atom/packages/minimap/lib/minimap-element.coffee:34

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.createdCallback (/home/codebox/.atom/packages/minimap/lib/minimap-element.coffee:34:36)
  at Object.createView (/home/codebox/.atom/packages/minimap/lib/minimap-element.coffee:483:15)
  at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app/src/view-registry.js:61:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app/src/view-registry.js:43:21)
  at /home/codebox/.atom/packages/minimap/lib/main.coffee:281:35
  at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app/src/workspace.js:265:9)
  at Main.initSubscriptions (/home/codebox/.atom/packages/minimap/lib/main.coffee:277:39)
  at Main.toggle (/home/codebox/.atom/packages/minimap/lib/main.coffee:144:8)
  at atom-workspace.Main.subscriptionsOfCommands.add.atom.commands.add.minimap:toggle (/home/codebox/.atom/packages/minimap/lib/main.coffee:96:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

/cc @atom/core

**Comment by fundon** [comment]
Update Atom to the latest v0.182.0. Thanks.

**Comment by fundon** [comment]
It's still happend after updated Atom.  Please, reopen it. Thanks.

**Comment by sriki18** [comment]
Hi, I'm stuck with rather slow internet. My download failed at 91% last night. I will check it in a some time and reopen it.
