### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Strike444** [atom-minimap/minimap#283]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.166.0
**System**: linux 3.13.0-37-generic
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.3.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/strike/.atom/packages/minimap/lib/minimap-element.coffee:34

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.createdCallback (/home/strike/.atom/packages/minimap/lib/minimap-element.coffee:34:36)
  at Object.createView (/home/strike/.atom/packages/minimap/lib/minimap-element.coffee:483:15)
  at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app/src/view-registry.js:56:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app/src/view-registry.js:43:21)
  at /home/strike/.atom/packages/minimap/lib/main.coffee:281:35
  at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app/src/workspace.js:268:9)
  at Main.initSubscriptions (/home/strike/.atom/packages/minimap/lib/main.coffee:277:39)
  at Main.toggle (/home/strike/.atom/packages/minimap/lib/main.coffee:144:8)
  at Main.activate (/home/strike/.atom/packages/minimap/lib/main.coffee:108:6)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:225:27)
  at /usr/share/atom/resources/app/src/package.js:211:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:157:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:205:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:410:21)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:234:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:37:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:461:12)

```

### Commands

```
     -0:28.7 pane:reopen-closed-item (atom-text-editor.editor)
     -0:26.2 core:undo (atom-text-editor.editor)
  4x -0:24.8 pane:reopen-closed-item (atom-text-editor.editor)
     -0:14.1 core:save-as (atom-text-editor.editor)
     -0:07.1 command-palette:toggle (atom-text-editor.editor)
  4x -0:03.1 core:move-down (atom-text-editor.editor.mini)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 settings-view:install-packages (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "Cozy-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Cozy-theme, v0.1.0
git-log, v0.3.0
rsense, v0.6.0
term2, v0.9.4

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Latest versions of the minimap only support Atom >= 0.175, please update your atom version (currently the latest is 0.184).

**Comment by Strike444** [comment]
Thank you.

**Comment by Victorystick** [comment]
I have this same issue with a supported Atom version.

1. Open a file

**Atom Version**: 0.176.0
**System**: linux 3.13.0-46-generic
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.4.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/eoskseg/.atom/packages/minimap/lib/minimap-element.coffee:69

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (/home/eoskseg/.atom/packages/minimap/lib/minimap-element.coffee:69:35)
  at atom-pane.PaneElement.activeItemChanged (/opt/atom/resources/app/src/pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/opt/atom/resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.addItem (/opt/atom/resources/app/src/pane.js:353:14)
  at Pane.module.exports.Pane.activateItem (/opt/atom/resources/app/src/pane.js:327:14)
  at /opt/atom/resources/app/src/workspace.js:524:16
  at _fulfilled (/opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:749:13)
  at /opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:557:44
  at flush (/opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:386:11)

```

### Commands

```
  3x -0:05.8 core:close (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "file-icons",
      "seti-file-icons",
      "atom-color-highlight"
    ],
    "audioBeep": false
  },
  "minimap": {
    "plugins": {},
    "adjustMinimapWidthToSoftWrap": false,
    "scrollAnimation": true
  }
}
```

### Installed Packages

```coffee
# User
language-bil, v0.0.0
language-latex, v0.4.1
language-ocaml, v1.1.0
language-x86asm, v0.4.0
latex, v0.18.1
minimap, v4.4.0
minimap-git-diff, v4.1.2
pdf-view, v0.17.0
symbols-tree-view, v0.6.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
@Victorystick Same issue than @Strike444  but with a different engine version, v4.4.0 will work only with atom >= 0.184.

apm is supposed to check the engine field in `package.json` when installing a package, but the settings-view is not honoring this constraint, which leads to this kind of issue. My advice is to update your Atom version to the latest (you won't regret it, there was major performances boost lately)
