### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by BastiHo** [atom-minimap/minimap#286]
I just set up Atom editor, installed the minimap package and got these errors.

Uncaught TypeError: undefined is not a function

**Atom Version**: 0.161.0
**System**: Mac OS X 10.10.2
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.4.0

### Steps To Reproduce

1. Install minimap package
2. ...

### Stack Trace

```
At /Users/sebastianh/.atom/packages/minimap/lib/minimap-element.coffee:31

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.createdCallback (/Users/sebastianh/.atom/packages/minimap/lib/minimap-element.coffee:31:36)
  at Object.createView (/Users/sebastianh/.atom/packages/minimap/lib/minimap-element.coffee:481:15)
  at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:61:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:43:21)
  at /Users/sebastianh/.atom/packages/minimap/lib/main.coffee:279:35
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:270:16
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:327:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:379:27)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:366:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:334:20)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:313:14)
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:494:16
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:749:13)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:557:44
  at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:378:11)

```
```
At /Users/sebastianh/.atom/packages/minimap/lib/minimap-element.coffee:69

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (/Users/sebastianh/.atom/packages/minimap/lib/minimap-element.coffee:69:35)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:250:22)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:339:14)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:313:14)
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:494:16
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:749:13)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:557:44
  at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:378:11)

```
/cc @atom/core

**Comment by abe33** [comment]
Sadly, we're still waiting for the `settings-view` package to honor the `engine` field in `package.json` so that this kind of issues won't happen again. 

v4.4.0 of the minimap package is only compatible with atom >= 0.184 as defined in the [package.json](https://github.com/atom-minimap/minimap/blob/master/package.json#L21) due to many changes in the core API we rely on.

You can either upgrade your Atom version (recommended) or downgrade the minimap version by using the `apm install minimap@version` command. I think v3.5.6 is the last release supporting atom < 0.175.0.

**Comment by BastiHo** [comment]
Just browsed through some closed issues with similar errors and updated Atom, thanks!

**Comment by abe33** [comment]
I've made up my mind and will implement this in the settings view package. Given the amount of issues to handle every time we update the engine version it'll be worth fixing it myself :).

**Comment by BastiHo** [comment]
Great! Thank you for your efforts
