### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by mandymu** [atom-minimap/minimap#291]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.170.0
**System**: linux 3.13.0-46-generic
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.5.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/mandy/.atom/packages/minimap/lib/minimap-element.coffee:69

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (/home/mandy/.atom/packages/minimap/lib/minimap-element.coffee:69:35)
  at atom-pane.PaneElement.activeItemChanged (/usr/share/atom/resources/app/src/pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:250:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:314:21)
  at tabs-tab.<anonymous> (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:184:24)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.4.0
autocomplete-snippets, v1.0.1
minimap, v4.5.0
monokai, v0.10.0
seti-ui, v0.6.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
See #288 since it's the same issue.
