### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by jinger89** [atom-minimap/minimap#293]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.2
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.5.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/jingtaoliu/.atom/packages/minimap/lib/minimap-element.coffee:31

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.createdCallback (/Users/jingtaoliu/.atom/packages/minimap/lib/minimap-element.coffee:31:36)
  at Object.createView (/Users/jingtaoliu/.atom/packages/minimap/lib/minimap-element.coffee:481:15)
  at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:61:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:43:21)
  at /Users/jingtaoliu/.atom/packages/minimap/lib/main.coffee:283:35
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:270:16
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:327:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:379:27)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:366:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:334:20)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:313:14)
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:494:16
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:749:13)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:557:44
  at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:378:11)

```

### Commands

```
  4x -2:55.5 core:backspace (input.hidden-input)
     -1:38.4 core:move-up (input.hidden-input)
     -1:37.6 core:backspace (input.hidden-input)
  2x -1:37.0 core:move-down (input.hidden-input)
     -1:36.7 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -1:35.3 core:backspace (input.hidden-input)
     -1:30.6 core:move-down (input.hidden-input)
  2x -1:18.5 core:backspace (input.hidden-input)
     -1:17.1 core:move-down (input.hidden-input)
     -1:16.7 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:11.8 core:move-up (input.hidden-input)
     -1:11.6 editor:newline (input.hidden-input)
     -1:07.5 core:move-down (input.hidden-input)
     -1:07.2 core:move-up (input.hidden-input)
     -1:06.7 core:move-down (input.hidden-input)
     -0:00.0 core:save (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "useReactEditor": true
  },
  "minimap": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
command-logger, v0.22.0
editor-stats, v0.17.0
file-icons, v1.4.5
minimap, v4.5.0
monokai, v0.12.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by badray** [comment]
+1

**Comment by badray** [comment]
Ok, I've just updated atom to `0.187.0` and problem is resolved. It seems like this is some core function added while somewhere between `0.165.0 - 0.187.0`. Maybe add some Troubleshooting section in a README which will recommend updated Atom to latest version if plugin will crush with similar error?

**Comment by abe33** [comment]
Actually the minimap package define a minimal Atom version through the `engine` field of the `package.json` file.
Apm started honoring this field when checking for compatibility in sometime after version 0.165 which explain why you could install/update this package despite not having the right Atom version.
Event now there's still issues with the way the `settings-view` handle that field, see atom/settings-view#377.

Thanks for the suggestion of a troubleshooting section in the README, it make sense so I'll try to add one soon.
