### ISSUE TITLE
Error installling minimap

### ISSUE THREAD

**Issue by duytrung** [atom-minimap/minimap#294]
```
Uncaught TypeError: undefined is not a function
/C:/Users/My%20Experiment/.atom/packages/minimap/lib/minimap-element.coffee:117
Hide Stack TraceShow Stack Trace
TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (C:\Users\My Experiment\.atom\packages\minimap\lib\minimap-element.coffee:69:35)
  at atom-text-editor-minimap.MinimapElement.attachToRight (C:\Users\My Experiment\.atom\packages\minimap\lib\minimap-element.coffee:98:33)
  at atom-text-editor-minimap.MinimapElement.swapMinimapPosition (C:\Users\My Experiment\.atom\packages\minimap\lib\minimap-element.coffee:104:8)
  at atom-text-editor-minimap.MinimapElement.attach (C:\Users\My Experiment\.atom\packages\minimap\lib\minimap-element.coffee:90:6)
  at C:\Users\My Experiment\.atom\packages\minimap\lib\main.coffee:287:22
  at Workspace.module.exports.Workspace.observeTextEditors (C:\Users\My Experiment\AppData\Local\atom\app-0.179.0\resources\app\src\workspace.js:274:9)
  at Main.initSubscriptions (C:\Users\My Experiment\.atom\packages\minimap\lib\main.coffee:279:39)
  at Main.toggle (C:\Users\My Experiment\.atom\packages\minimap\lib\main.coffee:145:8)
  at Main.activate (C:\Users\My Experiment\.atom\packages\minimap\lib\main.coffee:109:6)
  at Package.module.exports.Package.activateNow (C:\Users\My Experiment\AppData\Local\atom\app-0.179.0\resources\app\src\package.js:235:27)
  at C:\Users\My Experiment\AppData\Local\atom\app-0.179.0\resources\app\src\package.js:221:28
  at Package.module.exports.Package.measure (C:\Users\My Experiment\AppData\Local\atom\app-0.179.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.activate (C:\Users\My Experiment\AppData\Local\atom\app-0.179.0\resources\app\src\package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\My Experiment\AppData\Local\atom\app-0.179.0\resources\app\src\package-manager.js:464:21)
  at C:\Users\My Experiment\AppData\Local\atom\app-0.179.0\resources\app\node_modules\settings-view\lib\package-manager.js:268:29
  at exit (C:\Users\My Experiment\AppData\Local\atom\app-0.179.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (C:\Users\My Experiment\AppData\Local\atom\app-0.179.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (C:\Users\My Experiment\AppData\Local\atom\app-0.179.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)
The error was thrown from the minimap package. This issue has already been reported.
````

**Comment by fundon** [comment]
More details.

Which version is your Atom? Which version is Minimap?

**Comment by abe33** [comment]
Looks like you're using a version of Atom < 0.184. Please update your Atom version and tell us if you still get this error.
