### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by jaywunder** [atom-minimap/minimap#297]
[Enter steps to reproduce below:]

1. I just installed the latest version for the package manager
2. Re-Opened Atom

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10.2
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.6.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/JacobWunder/.atom/packages/minimap/lib/minimap-element.coffee:83

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (/Users/JacobWunder/.atom/packages/minimap/lib/minimap-element.coffee:83:35)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:353:14)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:327:14)
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:524:16
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:749:13)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:557:44
  at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:386:11)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "base16-tomorrow-light-theme"
    ],
    "projectHome": "/Users/JacobWunder/Documents",
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
achievements, v0.7.0
minimap, v4.6.0
project-manager, v1.15.5
terminal-status, v1.3.5

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Minimap v4.5+ is only compatible with Atom >= 0.184.
Sadly, previous version of the settings view didn't honor properly the engine field in the package.json file, leading to this kind of issues.
Please update your version of Atom, or if you can't, downgrade minimap version to one before v4.5.
