### ISSUE TITLE
Minimap error on ubunto 14.10

### ISSUE THREAD

**Issue by mapaiva** [atom-minimap/minimap#298]
I've just install minimap via package manager on my ubunto 14.10 and have this error:

**Atom Version**: 0.174.0
**System**: linux 3.16.0-31-generic
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.6.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/matheus/.atom/packages/minimap/lib/minimap-element.coffee:83

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (/home/matheus/.atom/packages/minimap/lib/minimap-element.coffee:83:35)
  at atom-pane.PaneElement.activeItemChanged (/usr/share/atom/resources/app/src/pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:353:14)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:327:14)
  at /usr/share/atom/resources/app/src/workspace.js:518:16
  at _fulfilled (/usr/share/atom/resources/app/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app/node_modules/q/q.js:749:13)
  at /usr/share/atom/resources/app/node_modules/q/q.js:557:44
  at flush (/usr/share/atom/resources/app/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:386:11)

```

### Commands

```
     -2:50.2 core:select-down (atom-text-editor.editor)
     -2:44.4 core:copy (atom-text-editor.editor)
  2x -2:40.8 editor:newline (atom-text-editor.editor)
     -2:40.3 core:paste (atom-text-editor.editor)
     -1:51.2 core:copy (atom-text-editor.editor)
     -1:48.9 settings-view:open (atom-text-editor.editor)
     -1:31.4 core:copy (atom-text-editor.editor)
     -0:44.9 core:move-right (atom-text-editor.editor)
  6x -0:42.2 core:backspace (atom-text-editor.editor)
     -0:37.6 core:paste (atom-text-editor.editor)
  9x -0:35.2 core:move-left (atom-text-editor.editor)
     -0:11.4 core:backspace (atom-text-editor.editor)
  2x -0:10.2 core:move-right (atom-text-editor.editor)
     -0:00.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "save-session"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.5.5
autocomplete-plus, v2.4.2
language-arduino, v0.2.1
linter, v0.12.0
linter-jshint, v0.1.0
minimap, v4.6.0
monokai, v0.12.0

# Dev
No dev packages
```

/cc @atom/core

Any ideas?
Thanks

**Comment by abe33** [comment]
Please see #288. This is a compatibility issue induced by the settings view not honoring the engine field in `package.json`.

**Comment by mapaiva** [comment]
I followed the steps in #288 and it worked. 
Thanks @abe33
