### ISSUE TITLE
Failed to activate the minimap package

### ISSUE THREAD

**Issue by Zielak** [atom-minimap/minimap#299]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.6.0

### Stack Trace

Failed to activate the minimap package

```
At object is not a function

TypeError: object is not a function
    at Main.minimapForEditor (/Users/gosc/.atom/packages/minimap/lib/main.coffee:228:19)
    at /Users/gosc/.atom/packages/minimap/lib/main.coffee:274:27
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:284:9)
    at Main.initSubscriptions (/Users/gosc/.atom/packages/minimap/lib/main.coffee:271:52)
    at Main.toggle (/Users/gosc/.atom/packages/minimap/lib/main.coffee:167:21)
    at Main.activate (/Users/gosc/.atom/packages/minimap/lib/main.coffee:121:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
```

### Commands

```
     -0:28.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-light-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
file-icons, v1.5.1
linter, v0.12.0
minimap, v4.6.0
monokai, v0.12.0
set-syntax, v0.2.1

# Dev
No dev packages
```

**Comment by abe33** [comment]
It's a know issue with the `settings-view` package, you can subscribe to atom/settings-view#416

**Comment by clemorphy** [comment]
[Enter steps to reproduce below:]

1. Launch Atom

**Atom Version**: 1.0.15
**System**: Windows 8.1
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.13.3


### Stack Trace

Failed to activate the minimap package

```
At Cannot find module 'atom-utils'

Error: Cannot find module 'atom-utils'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Clément\.atom\packages\minimap\lib\minimap-element.coffee:3:40)
  at Object.<anonymous> (C:\Users\Clément\.atom\packages\minimap\lib\minimap-element.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Main.activate (C:\Users\Clément\.atom\packages\minimap\lib\main.coffee:102:23)
  at Package.module.exports.Package.activateNow (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:245:19)
  at C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:226:30
  at Package.module.exports.Package.measure (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.activate (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package-manager.js:486:21)
  at C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package-manager.js:314:19
  at C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:587:20
  at Emitter.module.exports.Emitter.emit (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:772:29)
  at Config.module.exports.Config.setRawValue (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:564:19)
  at Config.module.exports.Config.set (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:356:12)
  at Package.module.exports.Package.enable (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:154:26)
  at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package-manager.js:143:14)
  at HTMLButtonElement.<anonymous> (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-card.js:314:27)
  at HTMLButtonElement.jQuery.event.dispatch (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
  2x -0:15.3.0 key-binding-resolver:toggle (atom-text-editor.editor.is-focused)
     -0:14 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-atom-api",
      "autocomplete-snippets",
      "simple-drag-drop-text"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.19.0
color-picker, v2.0.11
minimap, v4.13.3
php-twig, v4.0.0

# Dev
No dev packages
```

**Comment by nathansobo** [comment]
@maxbrunsfeld: I wonder if this could have anything to do with the recent changes to the module cache?

**Comment by maxbrunsfeld** [comment]
@clemorphy can you report the output of this command?

```sh
dir C:\Users\Clément\.atom\packages\minimap\node_modules
```

Is there an `atom-utils` folder? Does it contain `package.json` and `lib\atom-utils.js`?

**Comment by clemorphy** [comment]
Sure @maxbrunsfeld 
Here it is :
```
λ dir C:\Users\Clément\.atom\packages\minimap\node_modules

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----        18/09/2015     11:03            .bin
d----        18/09/2015     11:03            atom-utils
d----        18/09/2015     11:03            delegato
d----        18/09/2015     11:03            event-kit
d----        18/09/2015     11:03            fs-plus
d----        18/09/2015     11:03            mixto
d----        18/09/2015     11:03            semver
d----        18/09/2015     11:03            underscore-plus

C:\Users\Clément\.atom\packages\minimap\node_modules
λ cd .\atom-utils
C:\Users\Clément\.atom\packages\minimap\node_modules\atom-utils
λ ls

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----        18/09/2015     11:03            lib
-a---        18/09/2015     11:03         69 .npmignore
-a---        18/09/2015     11:03       1601 package.json
-a---        18/09/2015     11:03       5197 README.md

C:\Users\Clément\.atom\packages\minimap\node_modules\atom-utils
λ cd .\lib
C:\Users\Clément\.atom\packages\minimap\node_modules\atom-utils\lib
λ ls

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----        18/09/2015     11:03            mixins
-a---        18/09/2015     11:03       1298 atom-utils.js


```

**Comment by abe33** [comment]
So the install was properly done. 

FWIW there's a discussion on the forum about require issues: 

https://discuss.atom.io/t/atom-throwing-several-failed-to-load-the-xyz-package-errors/20969

@maxbrunsfeld Let me know if you want me to open an issue in atom/atom to references all the related issues in the various packages (I know that @olmokramer had one reported too on one of its packages).

**Comment by clemorphy** [comment]
I have a similar issue with the simple-drag-drop-text package  : https://github.com/mark-hahn/simple-drag-drop-text/issues/8

Though the "missing module" is a different one (`sub-atom`)

**Comment by mingjunyang** [comment]
```shell
NAME=openSUSE
VERSION="13.2 (Harlequin)"
VERSION_ID="13.2"
PRETTY_NAME="openSUSE 13.2 (Harlequin) (x86_64)
```

atom 1.1.0-beta.0

├── minimap@4.14.0
├── minimap-git-diff@4.1.8


```shell
this.textEditorElement.onDidChangeScrollTop is not a function
Hide Stack Trace
TypeError: this.textEditorElement.onDidChangeScrollTop is not a function
    at new Minimap (/home/mingjunyang/.atom/packages/minimap/lib/minimap.coffee:59:33)
    at Main.minimapForEditor (/home/mingjunyang/.atom/packages/minimap/lib/main.coffee:253:21)
    at /home/mingjunyang/.atom/packages/minimap/lib/main.coffee:297:18
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:276:9)
    at Main.initSubscriptions (/home/mingjunyang/.atom/packages/minimap/lib/main.coffee:296:39)
    at Main.toggle (/home/mingjunyang/.atom/packages/minimap/lib/main.coffee:146:8)
    at Main.activate (/home/mingjunyang/.atom/packages/minimap/lib/main.coffee:116:6)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:245:19)
    at /usr/share/atom/resources/app.asar/src/package.js:226:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:169:15)
```

**Comment by abe33** [comment]
@mingjunyang This might seems a bit tricky, but the v4.14.0 is only compatible with latest beta (beta 1), which moved some API from the text editor to the text editor element (hence your error). I've made the changes to prepare for the release of v1.0.20, but as you use beta 0 you don't have the new APIs. I tried, but failed, to support both version at the same time, as there were many changes in other parts of the API that made it almost impossible to achieve. I would suggest you update to beta 1.

**Comment by nathansobo** [comment]
@abe33 What are the APIs that are problematic? I'd like to make it easy to make minimap work across both the stable and beta versions of Atom.

**Comment by abe33** [comment]
@nathansobo off the top of my head, there's the `TextEditor::getMaxScrollTop` method replaced by `TextEditorElement::getScrollHeight` but that returns a different value when `scrollPastEnd` is enabled (see https://github.com/atom-minimap/minimap/commit/17ce6680b9cab748d8ea7bc83d31fa6cf840bf60#diff-c5fbd0d22eddd51072b33ed093c72e6cL202 where I had to subtract the editor height to get the proper scroll height). 

I also have many failures on Travis that I'm not sure about their cause (https://travis-ci.org/atom-minimap/minimap/builds/85386888). I should probably start again from the version compatible with 1.0.19 and make sure all the changes still pass with both.

On another front, to keep up with the changes in master, I'll need to update the test environment (mainly the use of the `TextEditor` constructor and measurements that are now compeltely off in the tests).
And I also noticed that on master the flex display seems to have been dropped on the text editor. So the minimap is now pushed below the `.editor--private` div. I found that by inserting it in the `.editor-contents--private` div instead it was coming back to its previous place, but now I have to find a way to push the scrollbar to the left so that it doesn't overlap with the minimap. And I doubt this will last long with the current pace of changes on master ^^.

**Comment by nathansobo** [comment]
@as-cii could you take a look at supporting these old methods in deprecated mode so minimap can be backwards-forwards-compatible? Also, do the flex issues he describes ring a bell?

**Comment by as-cii** [comment]
> Also, do the flex issues he describes ring a bell?

@nathansobo: as far as styling is concerned, there shouldn't have been changes so this looks a bit suspicious. I am a bit worried that we may have changed too many _big_ things at once and finding a culprit couldn't be super easy.

> Could you take a look at supporting these old methods in deprecated mode so minimap can be backwards-forwards-compatible?

Sure, I can start with re-introducing `TextEditor::getMaxScrollTop`. @abe33: after that maybe you can ping me on the exact issues you're facing so that we can solve them together one by one.

**Comment by abe33** [comment]
@as-cii @nathansobo thank you for the help, I will only be able to seriously look at that this evening.

**Comment by abe33** [comment]
@as-cii @nathansobo I've just published a new version which should handle both version nicely. 

I reverted my changes and use an adapter layer to handle the differences in API. I'll leave the change in tests for later as I can't possibly maintains one set of test for each version.

**Comment by nathansobo** [comment]
@abe33 Thanks as usual for your excellent work and maintenance of great packages like minimap. Appreciate you keeping it operational on stable.

**Comment by fbardel** [comment]
Hi ! Thanks for this package :) but I have the same problem : Cannot find module 'atom-utils' :(

**Comment by abe33** [comment]
@fbardel Ah, right, sorry, the discussion quite moved to another topic in the meantime. You're right, it was identified that this issue is linked to the presence of accented chars in the path (as explained in atom/atom#8891). But, unfortunately, it's not something that can be fixed at the minimap level, and it seems there's currently no knows workaround.

**Comment by jameswlane** [comment]
[Enter steps to reproduce below:]

1. Launch Atom

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.24.7


### Stack Trace

Failed to activate the minimap package

```
At Cannot find module 'mixto'

Error: Cannot find module 'mixto'
  at Module._resolveFilename (module.js:338:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:289:25)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/jl82576/.atom/packages/minimap/lib/mixins/plugin-management.js:19:14)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/jl82576/.atom/packages/minimap/lib/main.js:25:31)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
  at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:754:28

```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "hyperclick",
      "nuclide-arcanist",
      "nuclide-blame",
      "nuclide-blame-provider-hg",
      "nuclide-blame-ui",
      "nuclide-buck-files",
      "nuclide-clang-atom",
      "nuclide-code-format",
      "nuclide-debugger-atom",
      "nuclide-debugger-hhvm",
      "nuclide-debugger-lldb",
      "nuclide-diagnostics-store",
      "nuclide-diagnostics-ui",
      "nuclide-diff-view",
      "nuclide-file-tree",
      "nuclide-file-watcher",
      "nuclide-find-references",
      "nuclide-flow",
      "nuclide-format-js",
      "nuclide-fuzzy-filename-provider",
      "nuclide-hack",
      "nuclide-hack-symbol-provider",
      "nuclide-hg-repository",
      "nuclide-installer",
      "nuclide-language-hack",
      "nuclide-move-pane",
      "nuclide-objc",
      "nuclide-ocaml",
      "nuclide-open-filenames-provider",
      "nuclide-quick-open",
      "nuclide-remote-projects",
      "nuclide-test-runner",
      "nuclide-toolbar",
      "nuclide-type-hint",
      "tree-view",
      "activate-power-mode"
    ],
    "projectHome": "/Workbench"
  },
  "minimap": {
    "plugins": {
      "find-and-replace": true,
      "find-and-replaceDecorationsZIndex": 0,
      "git-diff": true,
      "git-diffDecorationsZIndex": 0,
      "highlight-selected": true,
      "highlight-selectedDecorationsZIndex": 0,
      "pigments": true,
      "pigmentsDecorationsZIndex": 0
    }
  }
}
```

### Installed Packages

```coffee
# User
achievements, v0.9.0
achiever, v0.1.1
atom-ternjs, v0.14.2
auto-detect-indentation, v1.1.0
autoclose-html, v0.23.0
autocomplete-modules, v1.5.2
autocomplete-paths, v1.0.2
autocomplete-sass, v0.1.0
change-case, v0.6.3
color-picker, v2.2.2
compare-files, v0.6.2
css-snippets, v0.9.0
ctags-status, v1.3.5
editorconfig, v1.4.1
file-icons, v1.7.17
fonts, v1.6.0
git-diff-details, v1.3.0
git-tab-status, v1.9.2
goto-definition, v1.1.18
grunt-runner, v0.14.0
gulp-snippets, v0.6.2
hashrocket, v0.4.10
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
javascript-snippets, v1.2.1
jquery-snippets, v11.0.0
js-refactor, v0.7.3
language-babel, vundefined
language-docker, v1.1.6
language-ini, v1.16.0
language-javascript-jsx, v0.3.7
language-ocaml, v1.1.2
language-thrift, v1.0.2
linter, v1.11.14
linter-eslint, v7.2.4
linter-ruby, v1.2.2
linter-scss-lint, v3.0.4
merge-conflicts, v1.4.4
minimap, v4.24.7
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-pigments, v0.2.1
node-debugger, vundefined
nuclide, v0.158.0
open-recent, v5.0.0
pigments, v0.31.2
project-manager, v2.9.7
react, v0.15.0
react-snippets, v0.4.2
refactor, v0.9.2
save-session, v0.16.0
set-syntax, v0.3.0
tabs-to-spaces, v1.0.2
terminal-plus, v0.14.5
terminal-status, v1.6.8
test-status, v1.0.0
tidy-tabs, v0.3.0
time-status, v1.1.2
tool-bar, v1.0.0
trailing-spaces, v0.3.2
tree-view-git-projects, v0.5.0
tree-view-git-status, v1.0.2
underscorejs-snippets, v0.2.2
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by Luizgpp** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.24.7


### Stack Trace

Failed to activate the minimap package

```
At Cannot find module './decorators/include'

Error: Cannot find module './decorators/include'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/opt/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/nofpowells/.atom/packages/minimap/lib/main.js:16:50)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/opt/atom/resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:173:16)
    at /opt/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:92:15)
    at /opt/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:538:21)
    at /opt/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/opt/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/opt/atom/resources/app.asar/src/package-manager.js:497:46)
    at /opt/atom/resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-csslint"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.4.6
atom-material-ui, v1.3.3
auto-indent, v0.5.0
autoclose-html, v0.23.0
autocomplete-modules, v1.6.1
autocomplete-paths, v1.0.2
color-picker, v2.2.2
docblockr, v0.8.2
emmet, v2.4.3
file-icons, v1.7.18
highlight-selected, v0.11.2
intentions, v1.1.0
laravel, v0.7.0
linter, v1.11.16
linter-bootlint, v1.0.2
linter-htmlhint, v1.3.0
linter-jshint, v2.1.0
linter-php, v1.2.0
linter-tidy, v2.2.0
merge-conflicts, v1.4.4
minimap, v4.24.7
php-cs-fixer, v2.5.9
pigments, v0.31.2
project-manager, v2.9.7
simple-drag-drop-text, v0.3.1

# Dev
No dev packages
```

**Comment by Swivelgames** [comment]
Oh look... everything is broken again :/

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.0
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.25.0


### Stack Trace

Failed to activate the minimap package

```
At Cannot read property 'screenExtent' of undefined

TypeError: Cannot read property 'screenExtent' of undefined
    at ScreenLineIterator.getScreenPositionWithMaxLineLength (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/display-index/dist/screen-line-iterator.js:184:29)
    at DisplayIndex.getScreenPositionWithMaxLineLength (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/display-index/dist/display-index.js:141:32)
    at DisplayLayer.module.exports.DisplayLayer.getRightmostScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1508:32)
    at TextEditor.module.exports.TextEditor.getRightmostScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:991:32)
    at TextEditor.module.exports.TextEditor.getLongestScreenRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:999:19)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getScreenRowsToRender (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:389:37)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getScreenRangesToRender (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:405:25)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLines (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1351:20)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:119:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:265:60)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:195:12)
    at new TextEditorComponent (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:169:12)
    at atom-text-editor.TextEditorElement.mountComponent (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:196:24)
    at atom-text-editor.TextEditorElement.setModel (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:145:12)
    at atom-text-editor.TextEditorElement.initialize (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:131:12)
    at TextEditor.module.exports.TextEditor.getElement (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:3245:109)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:98:26)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at new Minimap (/Users/joseph/.atom/packages/minimap/lib/minimap.js:182:20)
    at Main.minimapForEditor (/Users/joseph/.atom/packages/minimap/lib/main.js:322:17)
    at /Users/joseph/.atom/packages/minimap/lib/main.js:385:26
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:330:9)
    at Main.initSubscriptions (/Users/joseph/.atom/packages/minimap/lib/main.js:384:43)
    at Main.toggle (/Users/joseph/.atom/packages/minimap/lib/main.js:180:12)
    at Main.activate (/Users/joseph/.atom/packages/minimap/lib/main.js:111:55)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "activate-power-mode"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.0.2 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.6 (inactive)
auto-detect-indentation, v1.2.0 (inactive)
genesis-ui, v0.5.0 (inactive)
katana-syntax, v0.1.0 (inactive)
language-babel, v2.44.1 (inactive)
language-diff, v0.6.0 (inactive)
language-pug, v0.0.19 (inactive)
linter, v1.11.18 (inactive)
linter-eslint, v8.0.0 (inactive)
minimap, v4.25.0 (inactive)
native-ui, v0.19.1 (inactive)
neptune-dark-syntax, v1.0.0 (inactive)
node-debugger, v1.8.2 (inactive)
pigments, v0.37.0 (inactive)
seti-ui, v1.3.2 (inactive)
slim-dark-ui, v0.12.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.59.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by nathansobo** [comment]
@Swivelgames Can you share a file that makes this happen or provide any other reproduction steps? I can't reproduce the issue.

**Comment by nathansobo** [comment]
@Swivelgames This is caused by `auto-detect-indentation` calling `Editor.setTabLength()` with `null`. We actually had a fix on master and due to process confusion the fix didn't make it into beta 😬 . We'll have a hotfix out today... I'm very sorry.
