### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by MichaelGarza** [atom-minimap/minimap#300]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.174.0
**System**: Mac OS X 10.10.2
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.6.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/mgarza/.atom/packages/minimap/lib/minimap-element.coffee:83

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (/Users/mgarza/.atom/packages/minimap/lib/minimap-element.coffee:83:35)
  at atom-text-editor-minimap.MinimapElement.attachToRight (/Users/mgarza/.atom/packages/minimap/lib/minimap-element.coffee:122:33)
  at atom-text-editor-minimap.MinimapElement.swapMinimapPosition (/Users/mgarza/.atom/packages/minimap/lib/minimap-element.coffee:130:8)
  at atom-text-editor-minimap.MinimapElement.attach (/Users/mgarza/.atom/packages/minimap/lib/minimap-element.coffee:111:6)
  at /Users/mgarza/.atom/packages/minimap/lib/main.coffee:291:22
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:274:9)
  at Main.initSubscriptions (/Users/mgarza/.atom/packages/minimap/lib/main.coffee:283:39)
  at Main.toggle (/Users/mgarza/.atom/packages/minimap/lib/main.coffee:149:8)
  at Main.activate (/Users/mgarza/.atom/packages/minimap/lib/main.coffee:113:6)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:235:27)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:453:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:469:12)

```

### Commands

```
 18x -3:45.4 core:backspace (atom-text-editor.editor)
     -3:40.8 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
 10x -2:25.4 core:backspace (atom-text-editor.editor.mini)
     -0:00.0 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.6.0
language-csharp, v0.5.0
seti-syntax, v0.3.3
seti-ui, v0.6.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by fundon** [comment]
Update you Atom to the latest version. Thanks.
