### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by onsta** [atom-minimap/minimap#302]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: linux 3.16.0-33-generic
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.6.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/ondra/.atom/packages/minimap/lib/minimap-element.coffee:43

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.createdCallback (/home/ondra/.atom/packages/minimap/lib/minimap-element.coffee:43:36)
  at Object.createView (/home/ondra/.atom/packages/minimap/lib/minimap-element.coffee:633:15)
  at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app/src/view-registry.js:61:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app/src/view-registry.js:43:21)
  at /home/ondra/.atom/packages/minimap/lib/main.coffee:287:35
  at /usr/share/atom/resources/app/src/workspace.js:270:16
  at /usr/share/atom/resources/app/src/workspace.js:327:18
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app/src/pane-container.js:379:27)
  at /usr/share/atom/resources/app/src/pane-container.js:366:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:334:20)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:313:14)
  at /usr/share/atom/resources/app/src/workspace.js:494:16
  at _fulfilled (/usr/share/atom/resources/app/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app/node_modules/q/q.js:749:13)
  at /usr/share/atom/resources/app/node_modules/q/q.js:557:44
  at flush (/usr/share/atom/resources/app/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:378:11)

```

### Commands

```
```

### Config

```
{}
```

### Installed Packages

```coffee
# User
linter, v0.12.0
linter-tslint, v0.2.1
minimap, v4.6.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by fundon** [comment]
You should update Atom.

**Comment by alfgaar** [comment]
I think u mean downgrade, i have the same issue on windows and i'm running the latest version of atom (0.179.0 11/02/2015 17:48:18)

**Comment by ChaoticMind** [comment]
That's not the [latest](https://github.com/atom/atom/releases) version.

**Comment by alfgaar** [comment]
ok, atom update feature must be bugged, it keeps sayint it is the latest release, ty

**Comment by abe33** [comment]
Github is actually under a massive DDOS attack (3 days straight since it started) so many operations requiring access to github may encounter issues.

**Comment by big-wave-tim** [comment]
Also have this issue 

After dismiss the red error box I do see the first page of text in the minimap, but anything after the fist page of text is missing.

Below is copied from the stack trace that pops up, hope it helps, thanks for making minimap and I hope you find an easy fix. 

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.7.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\tim\.atom\packages\minimap\lib\minimap-element.coffee:88

TypeError: undefined is not a function
    at atom-text-editor-minimap.MinimapElement.attachedCallback (C:\Users\tim\.atom\packages\minimap\lib\minimap-element.coffee:117:41)
    at atom-pane.PaneElement.activeItemChanged (C:\Users\tim\AppData\Local\atom\app-0.182.0\resources\app\src\pane-element.js:110:24)
    at Emitter.module.exports.Emitter.emit (C:\Users\tim\AppData\Local\atom\app-0.182.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\tim\AppData\Local\atom\app-0.182.0\resources\app\src\pane.js:264:22)
    at Pane.module.exports.Pane.activateItem (C:\Users\tim\AppData\Local\atom\app-0.182.0\resources\app\src\pane.js:328:21)
    at C:\Users\tim\AppData\Local\atom\app-0.182.0\resources\app\src\workspace.js:522:16
    at _fulfilled (C:\Users\tim\AppData\Local\atom\app-0.182.0\resources\app\node_modules\q\q.js:794:54)
    at self.promiseDispatch.done (C:\Users\tim\AppData\Local\atom\app-0.182.0\resources\app\node_modules\q\q.js:823:30)
    at Promise.promise.promiseDispatch (C:\Users\tim\AppData\Local\atom\app-0.182.0\resources\app\node_modules\q\q.js:756:13)
    at C:\Users\tim\AppData\Local\atom\app-0.182.0\resources\app\node_modules\q\q.js:564:44
```

### Commands

```
     -0:30.0 settings-view:uninstall-packages (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
minimap, v4.7.1

# Dev
No dev packages
```

**Comment by big-wave-tim** [comment]
Atom was not updating for me so I downloaded it from the website and installed on top of existing installation. All works marvellously now!

**Comment by fundon** [comment]
Closed.

If you need, reopen it. Thanks.
