### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by denegny** [atom-minimap/minimap#310]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.158.0
**System**: linux 3.16.0-28-generic
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.7.5

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /home/jarto/.atom/packages/minimap/lib/minimap-element.coffee:79

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (/home/jarto/.atom/packages/minimap/lib/minimap-element.coffee:79:35)
  at atom-pane.PaneElement.activeItemChanged (/usr/share/atom/resources/app/src/pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:250:22)
  at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:339:14)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:313:14)
  at /usr/share/atom/resources/app/src/workspace.js:494:16
  at _fulfilled (/usr/share/atom/resources/app/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app/node_modules/q/q.js:749:13)
  at /usr/share/atom/resources/app/node_modules/q/q.js:557:44
  at flush (/usr/share/atom/resources/app/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:378:11)

```

/cc @atom/core

**Comment by fundon** [comment]
Update Atom.
Thanks.
