### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by good3n** [atom-minimap/minimap#313]
Error upon attempting to install package.

**Atom Version**: 0.174.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.7.6

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /c:/Users/Tom/.atom/packages/minimap/lib/minimap-element.coffee:111

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (c:\Users\Tom\.atom\packages\minimap\lib\minimap-element.coffee:79:35)
  at atom-text-editor-minimap.MinimapElement.attachToRight (c:\Users\Tom\.atom\packages\minimap\lib\minimap-element.coffee:127:33)
  at atom-text-editor-minimap.MinimapElement.swapMinimapPosition (c:\Users\Tom\.atom\packages\minimap\lib\minimap-element.coffee:135:8)
  at atom-text-editor-minimap.MinimapElement.attach (c:\Users\Tom\.atom\packages\minimap\lib\minimap-element.coffee:116:6)
  at c:\Users\Tom\.atom\packages\minimap\lib\main.coffee:291:22
  at Workspace.module.exports.Workspace.observeTextEditors (c:\Users\Tom\AppData\Local\atom\app-0.174.0\resources\app\src\workspace.js:274:9)
  at Main.initSubscriptions (c:\Users\Tom\.atom\packages\minimap\lib\main.coffee:283:39)
  at Main.toggle (c:\Users\Tom\.atom\packages\minimap\lib\main.coffee:149:8)
  at Main.activate (c:\Users\Tom\.atom\packages\minimap\lib\main.coffee:113:6)
  at Package.module.exports.Package.activateNow (c:\Users\Tom\AppData\Local\atom\app-0.174.0\resources\app\src\package.js:235:27)
  at c:\Users\Tom\AppData\Local\atom\app-0.174.0\resources\app\src\package.js:221:28
  at Package.module.exports.Package.measure (c:\Users\Tom\AppData\Local\atom\app-0.174.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.activate (c:\Users\Tom\AppData\Local\atom\app-0.174.0\resources\app\src\package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (c:\Users\Tom\AppData\Local\atom\app-0.174.0\resources\app\src\package-manager.js:453:21)
  at c:\Users\Tom\AppData\Local\atom\app-0.174.0\resources\app\node_modules\settings-view\lib\package-manager.js:268:29
  at exit (c:\Users\Tom\AppData\Local\atom\app-0.174.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (c:\Users\Tom\AppData\Local\atom\app-0.174.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (c:\Users\Tom\AppData\Local\atom\app-0.174.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:110:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1068:12)

```

### Commands

```
     -0:00.0 settings-view:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.7
Remote-FTP, v0.6.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Latest versions are only compatible with atom 0.184 and above, we're still waiting atom/settings-view#377 to be merged so that this problem get fixed.
