### ISSUE TITLE
Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by tkotha** [atom-minimap/minimap#318]
[Enter steps to reproduce below:]

1. update to latest version of minimap
2. try to toggle minimap

**Atom Version**: 0.190.0
**System**: Mac OS X 10.9.4
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.7.6

### Stack Trace

Uncaught TypeError: object is not a function

```
At /Users/human/.atom/packages/minimap/lib/main.coffee:250

TypeError: object is not a function
  at Main.minimapForEditor (/Users/human/.atom/packages/minimap/lib/main.coffee:250:21)
  at /Users/human/.atom/packages/minimap/lib/main.coffee:284:18
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:266:9)
  at Main.initSubscriptions (/Users/human/.atom/packages/minimap/lib/main.coffee:283:39)
  at Main.toggle (/Users/human/.atom/packages/minimap/lib/main.coffee:149:8)
  at atom-workspace.Main.subscriptionsOfCommands.add.atom.commands.add.minimap:toggle (/Users/human/.atom/packages/minimap/lib/main.coffee:101:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:157:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:73:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -1:27.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
     -0:37.4 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
  2x -0:08.5 minimap:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.6.0
linter, v0.12.0
minimap, v4.7.6

# Dev
No dev packages
```

**Comment by abe33** [comment]
Thanks for the report, I'll take a look at that problem asap.

**Comment by abe33** [comment]
Do you still get that issue with the latest version or should I close this ticket?

**Comment by gaulinmp** [comment]
I get the error as of 0.177.0 on Xubuntu 15.04.

**Comment by fundon** [comment]
Closed.
You can re-open it If it has same issue with the latest version.
