### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by waynegraham** [atom-minimap/minimap#321]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.168.0
**System**: Mac OS X 10.10.3
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.7.6

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/wsg4w/.atom/packages/minimap/lib/minimap-element.coffee:79

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (/Users/wsg4w/.atom/packages/minimap/lib/minimap-element.coffee:79:35)
  at atom-text-editor-minimap.MinimapElement.attachToRight (/Users/wsg4w/.atom/packages/minimap/lib/minimap-element.coffee:127:33)
  at atom-text-editor-minimap.MinimapElement.swapMinimapPosition (/Users/wsg4w/.atom/packages/minimap/lib/minimap-element.coffee:135:8)
  at atom-text-editor-minimap.MinimapElement.attach (/Users/wsg4w/.atom/packages/minimap/lib/minimap-element.coffee:116:6)
  at /Users/wsg4w/.atom/packages/minimap/lib/main.coffee:291:22
  at Workspace.module.exports.Workspace.observeTextEditors (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/workspace.js:268:9)
  at Main.initSubscriptions (/Users/wsg4w/.atom/packages/minimap/lib/main.coffee:283:39)
  at Main.toggle (/Users/wsg4w/.atom/packages/minimap/lib/main.coffee:149:8)
  at Main.activate (/Users/wsg4w/.atom/packages/minimap/lib/main.coffee:113:6)
  at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:225:27)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:211:28
  at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:157:15)
  at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:205:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package-manager.js:410:21)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:469:12)

```

### Commands

```
     -0:04.7 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:00.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/wsg4w/projects"
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.6.0
linter, v0.10.1
travis-ci-status, v0.13.0
vim-mode, v0.43.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by dxlbrt** [comment]
[Enter steps to reproduce below:]

1. Open atom (with mini-map installed)

**Atom Version**: 0.179.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.7.6

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /C:/Users/Dario/.atom/packages/minimap/lib/minimap-element.coffee:111

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (C:\Users\Dario\.atom\packages\minimap\lib\minimap-element.coffee:79:35)
  at atom-pane.PaneElement.activeItemChanged (C:\Users\Dario\AppData\Local\atom\app-0.179.0\resources\app\src\pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (C:\Users\Dario\AppData\Local\atom\app-0.179.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\Dario\AppData\Local\atom\app-0.179.0\resources\app\src\pane.js:264:22)
  at Pane.module.exports.Pane.addItem (C:\Users\Dario\AppData\Local\atom\app-0.179.0\resources\app\src\pane.js:353:14)
  at Pane.module.exports.Pane.activateItem (C:\Users\Dario\AppData\Local\atom\app-0.179.0\resources\app\src\pane.js:327:14)
  at C:\Users\Dario\AppData\Local\atom\app-0.179.0\resources\app\src\workspace.js:524:16
  at _fulfilled (C:\Users\Dario\AppData\Local\atom\app-0.179.0\resources\app\node_modules\q\q.js:794:54)
  at self.promiseDispatch.done (C:\Users\Dario\AppData\Local\atom\app-0.179.0\resources\app\node_modules\q\q.js:823:30)
  at Promise.promise.promiseDispatch (C:\Users\Dario\AppData\Local\atom\app-0.179.0\resources\app\node_modules\q\q.js:756:13)
  at C:\Users\Dario\AppData\Local\atom\app-0.179.0\resources\app\node_modules\q\q.js:564:44
  at flush (C:\Users\Dario\AppData\Local\atom\app-0.179.0\resources\app\node_modules\q\q.js:110:17)
  at process._tickCallback (node.js:364:11)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
minimap, v4.7.6

# Dev
No dev packages
```

**Comment by fundon** [comment]
Could you try the latest Atom?

**Comment by dxlbrt** [comment]
Works perfectly on atom 0.192.0

**Comment by fundon** [comment]
Thanks.
