### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by lihuanshuai** [atom-minimap/minimap#324]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Unknown Windows Version
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.7.6

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /c:/Users/lihs/.atom/packages/minimap/lib/minimap-element.coffee:111

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (c:\Users\lihs\.atom\packages\minimap\lib\minimap-element.coffee:79:35)
  at atom-pane.PaneElement.activeItemChanged (c:\Users\lihs\AppData\Local\atom\app-0.165.0\resources\app\src\pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (c:\Users\lihs\AppData\Local\atom\app-0.165.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (c:\Users\lihs\AppData\Local\atom\app-0.165.0\resources\app\src\pane.js:250:22)
  at Pane.module.exports.Pane.addItem (c:\Users\lihs\AppData\Local\atom\app-0.165.0\resources\app\src\pane.js:339:14)
  at Pane.module.exports.Pane.activateItem (c:\Users\lihs\AppData\Local\atom\app-0.165.0\resources\app\src\pane.js:313:14)
  at c:\Users\lihs\AppData\Local\atom\app-0.165.0\resources\app\src\workspace.js:494:16
  at _fulfilled (c:\Users\lihs\AppData\Local\atom\app-0.165.0\resources\app\node_modules\q\q.js:787:54)
  at self.promiseDispatch.done (c:\Users\lihs\AppData\Local\atom\app-0.165.0\resources\app\node_modules\q\q.js:816:30)
  at Promise.promise.promiseDispatch (c:\Users\lihs\AppData\Local\atom\app-0.165.0\resources\app\node_modules\q\q.js:749:13)
  at c:\Users\lihs\AppData\Local\atom\app-0.165.0\resources\app\node_modules\q\q.js:557:44
  at flush (c:\Users\lihs\AppData\Local\atom\app-0.165.0\resources\app\node_modules\q\q.js:108:17)
  at process._tickCallback (node.js:378:11)

```

### Commands

```
```

### Config

```
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by pmted** [comment]
Got the same with the exact same stack trace (differrent username). Windows 8.1. No packages or anything.

**Comment by ChaoticMind** [comment]
Update Atom. Use [search](https://github.com/atom-minimap/minimap/issues?utf8=%E2%9C%93&q=is%3Aissue+Uncaught+TypeError+undefined+is+not+a+function) on the issue tracker.

**Comment by lihuanshuai** [comment]
use portable version now, no this trouble

**Comment by abe33** [comment]
@lihuanshuai thank you for the feedback, I'm glad in now works for you.
