### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by hennumjr** [atom-minimap/minimap#327]
1. Installed minimap and opened a file

**Atom Version**: 0.174.0
**System**: linux 3.13.0-49-generic
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.8.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/shomea/a/andehen/.atom/packages/minimap/lib/minimap-element.coffee:79

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (/home/shomea/a/andehen/.atom/packages/minimap/lib/minimap-element.coffee:79:35)
  at atom-pane.PaneElement.activeItemChanged (/usr/share/atom/resources/app/src/pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:328:21)
  at /usr/share/atom/resources/app/src/workspace.js:518:16
  at _fulfilled (/usr/share/atom/resources/app/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app/node_modules/q/q.js:749:13)
  at /usr/share/atom/resources/app/node_modules/q/q.js:557:44
  at flush (/usr/share/atom/resources/app/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:386:11)

```

### Commands

```
     -3:46.2 core:cancel (atom-text-editor.editor.mini)
     -3:45.6 application:open-file (atom-text-editor.editor)
     -2:55.5 window:run-package-specs (atom-text-editor.editor)
     -2:51.5 command-palette:toggle (atom-text-editor.editor)
     -2:49.2 core:confirm (atom-text-editor.editor.mini)
     -2:49.2 settings-view:open (atom-text-editor.editor)
 11x -2:16.5 core:backspace (atom-text-editor.editor.mini)
  2x -2:13.7 core:confirm (atom-text-editor.editor.mini)
     -1:50.4 core:backspace (atom-text-editor.editor.mini)
  3x -1:50.0 core:confirm (atom-text-editor.editor.mini)
     -0:45.0 build:trigger (atom-text-editor.editor)
     -0:26.2 core:confirm (atom-text-editor.editor.mini)
 15x -0:20.6 core:backspace (atom-text-editor.editor.mini)
     -0:16.5 core:confirm (atom-text-editor.editor.mini)
  9x -0:12.4 core:backspace (atom-text-editor.editor.mini)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
build, v0.30.0
language-knitr, v0.1.0
language-latex, v0.6.1
minimap, v4.8.0
minimap-git-diff, v4.1.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Please update Atom to the latest version, latest minimap version is only compatible with Atom >=0.184.0.
