### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by exotherm1k** [atom-minimap/minimap#333]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.174.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.8.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /c:/Users/cwiet/.atom/packages/minimap/lib/minimap-element.coffee:111

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (c:\Users\cwiet\.atom\packages\minimap\lib\minimap-element.coffee:79:35)
  at atom-pane.PaneElement.activeItemChanged (c:\Users\cwiet\AppData\Local\atom\app-0.174.0\resources\app\src\pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (c:\Users\cwiet\AppData\Local\atom\app-0.174.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (c:\Users\cwiet\AppData\Local\atom\app-0.174.0\resources\app\src\pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (c:\Users\cwiet\AppData\Local\atom\app-0.174.0\resources\app\src\pane.js:328:21)
  at c:\Users\cwiet\AppData\Local\atom\app-0.174.0\resources\app\src\workspace.js:518:16
  at _fulfilled (c:\Users\cwiet\AppData\Local\atom\app-0.174.0\resources\app\node_modules\q\q.js:787:54)
  at self.promiseDispatch.done (c:\Users\cwiet\AppData\Local\atom\app-0.174.0\resources\app\node_modules\q\q.js:816:30)
  at Promise.promise.promiseDispatch (c:\Users\cwiet\AppData\Local\atom\app-0.174.0\resources\app\node_modules\q\q.js:749:13)
  at c:\Users\cwiet\AppData\Local\atom\app-0.174.0\resources\app\node_modules\q\q.js:557:44
  at flush (c:\Users\cwiet\AppData\Local\atom\app-0.174.0\resources\app\node_modules\q\q.js:108:17)
  at process._tickCallback (node.js:386:11)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-arm",
      "language-ilasm",
      "language-x86",
      "deprecation-cop",
      "remote-edit"
    ],
    "themes": [
      "seti-ui",
      "seti-monokai"
    ]
  },
  "minimap": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v1.7.0
language-csharp, v0.5.0
language-PIC-8bit, v0.0.1
minimap, v4.8.0
remote-sync, v2.4.1
seti-monokai, v0.3.1
seti-ui, v0.7.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Please see #288
