### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by 190n** [atom-minimap/minimap#335]
When I tried deleting something in Atom 0.206, I got an error message from the minimap package.

Atom: 0.206
Minimap: 4.9.3
Plugins: minimap-find-and-replace 4.2.0, minimap-highlight-selected 4.3.0, minimap-selection 4.2.0
Platform: Ubuntu 14.10

```
TypeError: undefined is not a function
    at Decoration.module.exports.Decoration.setProperties (/usr/share/atom/resources/app.asar/src/decoration.js:135:28)
    at new Decoration (/usr/share/atom/resources/app.asar/src/decoration.js:58:12)
    at Minimap.module.exports.DecorationManagement.decorateMarker (/home/ben/.atom/packages/minimap/lib/mixins/decoration-management.coffee:159:20)
    at MinimapSelectionView.module.exports.MinimapSelectionView.handleSelection (/home/ben/.atom/packages/minimap-selection/lib/minimap-selection-view.coffee:37:37)
    at /home/ben/.atom/packages/minimap-selection/lib/minimap-selection-view.coffee:3:61
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextEditor.module.exports.TextEditor.cursorMoved (/usr/share/atom/resources/app.asar/src/text-editor.js:1563:27)
    at /usr/share/atom/resources/app.asar/src/cursor.js:56:31
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Marker.module.exports.Marker.notifyObservers (/usr/share/atom/resources/app.asar/src/marker.js:270:27)
    at /usr/share/atom/resources/app.asar/src/marker.js:65:26
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Marker.module.exports.Marker.emitChangeEvent (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:390:20)
    at Marker.module.exports.Marker.update (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:339:12)
    at Marker.module.exports.Marker.setHeadPosition (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:140:19)
    at Marker.module.exports.Marker.setHeadBufferPosition (/usr/share/atom/resources/app.asar/src/marker.js:175:32)
```

**Comment by marty80** [comment]
[Enter steps to reproduce below:]

1. As soon as I start typing any character (e.g. "a") in a file called additional_information.cfm, the error occurs.
2. ...

**Atom Version**: 0.206.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.9.3


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\220983F\AppData\Local\atom\app-0.206.0\resources\app.asar\src\decoration.js:135

TypeError: undefined is not a function
  at Decoration.module.exports.Decoration.setProperties (C:\Users\220983F\AppData\Local\atom\app-0.206.0\resources\app.asar\src\decoration.js:135:28)
  at new Decoration (C:\Users\220983F\AppData\Local\atom\app-0.206.0\resources\app.asar\src\decoration.js:58:12)
  at Minimap.module.exports.DecorationManagement.decorateMarker (C:\Users\220983F\.atom\packages\minimap\lib\mixins\decoration-management.coffee:203:22)
  at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.markRange (C:\Users\220983F\.atom\packages\minimap-git-diff\lib\minimap-git-diff-binding.coffee:56:14)
  at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.addDecorations (C:\Users\220983F\.atom\packages\minimap-git-diff\lib\minimap-git-diff-binding.coffee:46:10)
  at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.updateDiffs (C:\Users\220983F\.atom\packages\minimap-git-diff\lib\minimap-git-diff-binding.coffee:35:8)
  at C:\Users\220983F\.atom\packages\minimap-git-diff\lib\minimap-git-diff-binding.coffee:1:1
  at Emitter.module.exports.Emitter.emit (C:\Users\220983F\AppData\Local\atom\app-0.206.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\220983F\AppData\Local\atom\app-0.206.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1207:25

```

### Commands

```
     -6:40.5.0 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -6:40.3.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -6:39.1.0 tree-view:open-selected-entry (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
 16x -6:35.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -5:45.5.0 core:close (atom-text-editor.editor.is-focused)
  4x -5:41.2.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  4x -5:40 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:37.7.0 tree-view:open-selected-entry (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  4x -5:31 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:30 tree-view:open-selected-entry (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  4x -5:25.4.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -3:50.4.0 core:close (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-seti-ui)
  2x -3:42.6.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:42 tree-view:open-selected-entry (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:38 core:move-left (atom-text-editor.editor.is-focused)
     -0:06.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ]
  },
  "minimap": {
    "plugins": {
      "git-diff": true
    }
  }
}
```

### Installed Packages

```coffee
# User
git-diff-details, v0.18.0
git-go, v1.0.1
git-log, v0.4.1
git-projects, v1.14.1
git-tab-status, v1.9.2
language-cfml, v0.6.0
minimap, v4.9.3
minimap-git-diff, v4.1.3
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by 190n** [comment]
Thanks for the error info, Atom wasn't copying it for some reason.

**Comment by mingjunyang** [comment]
how to do now ? disable minimap and wait next ?

```shell
Uncaught TypeError: undefined is not a function
/usr/share/atom/resources/app.asar/src/decoration.js:135
TypeError: undefined is not a function
    at Decoration.module.exports.Decoration.setProperties (/usr/share/atom/resources/app.asar/src/decoration.js:135:28)
    at new Decoration (/usr/share/atom/resources/app.asar/src/decoration.js:58:12)
    at Minimap.module.exports.DecorationManagement.decorateMarker (/home/mingjunyang/.atom/packages/minimap/lib/mixins/decoration-management.coffee:159:20)
    at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.markRange (/home/mingjunyang/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:94:20)
    at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.addDecorations (/home/mingjunyang/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:67:30)
    at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.updateDiffs (/home/mingjunyang/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:51:21)
    at /home/mingjunyang/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:3:61
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1207:25
```

**Comment by basarat** [comment]
Not to be annoying. But this just happened to me as well after latest atom update `0.206`

**Comment by qnub** [comment]
When disable `minimap-highlight-selected` bug disappeared.

**Comment by basarat** [comment]
Cool tip. I had to disable `minimap-find-and-replace`. I don't have `minimap-highlight-selected` installed. I guess they use similar code.

**Comment by Danmer** [comment]
Same problem with `minimap-git-diff` after update to 0.206. win 8.1 x64

**Comment by basarat** [comment]
@Danmer I agree. I ended up disabling everything. I guess the issue is really in `minimap` and not the others .

**Comment by abe33** [comment]
Thanks for the report, it seems they introduced a new method in the DisplayBuffer while I was sleeping (seriously, I built Atom from master yesterday in the evening and didn't get any error). Sorry for the trouble but I wouldn't have been able to prevent that even if I wanted to.

The fix will come very soon.

**Comment by tomoya** [comment]
:+1:
