### ISSUE TITLE
Failed to activate the minimap-selection package

### ISSUE THREAD

**Issue by tscholak** [atom-minimap/minimap#336]
Something is wrong with the new version...

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.4
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.9.3

### Stack Trace

Failed to activate the minimap-selection package

```
At undefined is not a function

TypeError: undefined is not a function
    at Decoration.module.exports.Decoration.setProperties (/Applications/Atom.app/Contents/Resources/app.asar/src/decoration.js:135:28)
    at new Decoration (/Applications/Atom.app/Contents/Resources/app.asar/src/decoration.js:58:12)
    at Minimap.module.exports.DecorationManagement.decorateMarker (/Users/tscholak/.atom/packages/minimap/lib/mixins/decoration-management.coffee:159:20)
    at MinimapSelectionView.module.exports.MinimapSelectionView.handleSelection (/Users/tscholak/.atom/packages/minimap-selection/lib/minimap-selection-view.coffee:37:37)
    at MinimapSelectionView.handleSelection (/Users/tscholak/.atom/packages/minimap-selection/lib/minimap-selection-view.coffee:3:61)
    at new MinimapSelectionView (/Users/tscholak/.atom/packages/minimap-selection/lib/minimap-selection-view.coffee:20:12)
    at /Users/tscholak/.atom/packages/minimap-selection/lib/minimap-selection.coffee:30:27
    at /Users/tscholak/.atom/packages/minimap/lib/main.coffee:256:18
    at Map.forEach (native)
    at Main.observeMinimaps (/Users/tscholak/.atom/packages/minimap/lib/main.coffee:255:15)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "minimap": {
    "plugins": {
      "bookmarks": true,
      "git-diff": true,
      "selection": true,
      "color-highlight": true,
      "highlight-selected": true
    }
  }
}
```

### Installed Packages

```coffee
# User
highlight-selected, v0.9.3
minimap, v4.9.3
minimap-bookmarks, v0.1.0
minimap-color-highlight, v4.1.4
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.2.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Thanks for the report and sorry for the inconvenience, fixed in 4.9.4
