### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by abinashmeher999** [atom-minimap/minimap#340]
[Enter steps to reproduce below:]

1. Open Atom Editor

**Atom Version**: 0.182.0
**System**: linux 3.13.0-53-generic
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.9.4

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/abinashmeher999/.atom/packages/minimap/lib/minimap-element.coffee:79

TypeError: undefined is not a function
    at atom-text-editor-minimap.MinimapElement.attachedCallback (/home/abinashmeher999/.atom/packages/minimap/lib/minimap-element.coffee:111:41)
    at atom-pane.PaneElement.activeItemChanged (/usr/share/atom/resources/app/src/pane-element.js:110:24)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:264:22)
    at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:353:14)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:327:14)
    at /usr/share/atom/resources/app/src/workspace.js:522:16
    at _fulfilled (/usr/share/atom/resources/app/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/usr/share/atom/resources/app/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/usr/share/atom/resources/app/node_modules/q/q.js:756:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "followSymlinks": true,
    "disabledPackages": [
      "whitespace"
    ]
  },
  "minimap": {
    "plugins": {
      "bookmarks": true,
      "minimap-autohide": true,
      "git-diff": true,
      "selection": true
    }
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-ruby, v0.1.0
foldingtext-for-atom, v0.5.0
markdown-preview-plus, v1.5.0
minimap, v4.9.4
minimap-autohide, v0.10.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.2.0
project-manager, v1.15.10
set-syntax, v0.3.0
tabs-to-spaces, v0.11.0
terminal-status, v1.6.8
trailing-spaces, v0.3.1
travis-ci-status, v0.15.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Your Atom version is way behind (latest is v0.208), as it get closer to v1.0 we get rid of deprecated API.

**Comment by emafernandez** [comment]
I had the same issue, my atom version is the latest one (v0.208), but the minimap package was way behind, updating minimap package solved the issue for me.
