### ISSUE TITLE
Uncaught Error: No screen line exists when converting buffer row to screen row

### ISSUE THREAD

**Issue by kmdavis** [atom-minimap/minimap#355]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.10.1

### Stack Trace

Uncaught Error: No screen line exists when converting buffer row to screen row

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1105

Error: No screen line exists when converting buffer row to screen row
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1105:17)
  at Marker.module.exports.Marker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:179:33)
  at Marker.module.exports.Marker.onDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:59:43)
  at Minimap.module.exports.DecorationManagement.decorateMarker (/Users/kdavis/.atom/packages/minimap/lib/mixins/decoration-management.coffee:187:64)
  at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.markRange (/Users/kdavis/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:56:14)
  at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.addDecorations (/Users/kdavis/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:44:10)
  at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.updateDiffs (/Users/kdavis/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:35:8)
  at /Users/kdavis/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:1:1
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1183:25

```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "*.pyc"
    ],
    "disabledPackages": [
      "snippets",
      "atomatigit",
      "linter-flake8",
      "tree-view-filter",
      "notebook",
      "open-last-project",
      "regex-railroad-diagram"
    ]
  },
  "minimap": {
    "plugins": {
      "selection": true,
      "color-highlight": true,
      "highlight-selected": true,
      "git-diff": true,
      "find-and-replace": true
    }
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-color-highlight, v3.0.9
atom-handlebars, v1.0.0
atom-python-debugger, v0.3.4
auto-update-packages, v1.0.0
change-case, v0.6.0
coffee-compile, v0.16.1
coffee-refactor, v0.6.2
color-picker, v2.0.7
docblockr, v0.7.2
emmet, v2.3.11
file-icons, v1.5.8
git-log, v0.4.1
git-tab-status, v1.9.2
highlight-line, v0.11.0
highlight-selected, v0.10.1
js-refactor, v0.4.2
language-python-django, v0.3.1
linter, v1.1.0
linter-coffeelint, v0.3.2
minimap, v4.10.1
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.3.0
refactor, v0.5.1
symbols-tree-view, v0.9.3
view-tail-large-files, v0.2.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hmm, can you give some details on the context in which this error occured? Were you editing a file or something?

**Comment by kmdavis** [comment]
This happened on startup.

**Comment by abe33** [comment]
With a file open? Which kind of file? You bet that I can't guess what you're doing, and AFAIK it's not an issue that everybody has so it has to be somehow bound to your configuration.

**Comment by kmdavis** [comment]
I just reproduced it again with 3 python files open on load.

**Comment by fundon** [comment]
Is it still here with the latest version?
