### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by atindermann08** [atom-minimap/minimap#359]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.174.0
**System**: linux 3.13.0-37-generic
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.10.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/atinder/.atom/packages/minimap/lib/minimap-element.coffee:84

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (/home/atinder/.atom/packages/minimap/lib/minimap-element.coffee:84:35)
  at atom-pane.PaneElement.activeItemChanged (/usr/share/atom/resources/app/src/pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:328:21)
  at /usr/share/atom/resources/app/src/workspace.js:518:16
  at _fulfilled (/usr/share/atom/resources/app/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app/node_modules/q/q.js:749:13)
  at /usr/share/atom/resources/app/node_modules/q/q.js:557:44
  at flush (/usr/share/atom/resources/app/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:386:11)

```

### Commands

```
  2x -30:04.5 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode)
     -30:03.0 vim-mode:move-up (atom-text-editor.editor.vim-mode)
     -30:02.6 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode)
     -30:00.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-lint, v0.20.1
autocomplete-css, v0.8.0
autocomplete-elixir, v1.3.12
autocomplete-php, v0.3.6
autocomplete-phpunit, v1.0.2
autocomplete-sass, v0.1.0
color-picker, v2.0.8
css-snippets, v0.8.0
emmet, v2.3.12
jshint, v1.3.9
linter-csslint, v0.0.14
linter-php, v0.0.15
linter-scss-lint, v1.0.5
minimap, v4.10.2
vim-mode, v0.54.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Please update Atom to a version >= 0.208.0. Actually Atom has reached the 1.0.0 milestone so I won't maintain the minimap for any older versions.
