### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by pelo8888** [atom-minimap/minimap#363]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: linux 3.13.0-53-generic
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.11.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/afontes/.atom/packages/minimap/lib/minimap-element.coffee:82

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (/home/afontes/.atom/packages/minimap/lib/minimap-element.coffee:82:35)
  at atom-pane.PaneElement.activeItemChanged (/usr/share/atom/resources/app/src/pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:328:21)
  at /usr/share/atom/resources/app/src/workspace.js:524:16
  at _fulfilled (/usr/share/atom/resources/app/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app/node_modules/q/q.js:749:13)
  at /usr/share/atom/resources/app/node_modules/q/q.js:557:44
  at flush (/usr/share/atom/resources/app/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:386:11)

```

### Commands

```
  2x -6:03.6 core:move-down (atom-text-editor.editor)
  2x -6:03.3 core:move-right (atom-text-editor.editor)
  2x -6:02.3 core:save (atom-text-editor.editor)
  6x -5:59.9 core:move-up (atom-text-editor.editor)
     -5:58.9 core:delete (atom-text-editor.editor)
     -5:58.5 core:save (atom-text-editor.editor)
  7x -5:57.5 core:move-down (atom-text-editor.editor)
  2x -5:56.6 core:move-left (atom-text-editor.editor)
     -5:55.8 core:save (atom-text-editor.editor)
     -3:40.9 dev-live-reload:reload-all (atom-text-editor.editor)
     -3:29.6 styleguide:show (atom-text-editor.editor)
     -2:41.6 settings-view:show-keybindings (atom-text-editor.editor)
  4x -1:39.7 core:move-down (atom-text-editor.editor.mini)
     -0:29.4 core:confirm (atom-text-editor.editor.mini)
  4x -0:17.8 core:backspace (atom-text-editor.editor.mini)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.18.0
minimap, v4.11.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Atom has now reached version 1.0, and the latest version of the minimap only support Atom >= 0.208 so updating your Atom version should fix this issue.
