### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by irstavr** [atom-minimap/minimap#364]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: linux 3.13.0-43-generic
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.12.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/username/.atom/packages/minimap/lib/minimap-element.coffee:82

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (/home/username/.atom/packages/minimap/lib/minimap-element.coffee:82:35)
  at atom-text-editor-minimap.MinimapElement.attach (/home/wi/.atom/packages/minimap/lib/minimap-element.coffee:119:33)
  at /home/username/.atom/packages/minimap/lib/main.coffee:279:22
  at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app/src/workspace.js:265:9)
  at Main.initSubscriptions (/home/wi/.atom/packages/minimap/lib/main.coffee:271:39)
  at Main.toggle (/home/wi/.atom/packages/minimap/lib/main.coffee:140:8)
  at Main.activate (/home/wi/.atom/packages/minimap/lib/main.coffee:116:6)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:227:27)
  at /usr/share/atom/resources/app/src/package.js:213:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:159:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:207:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:410:21)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:234:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:37:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:461:12)

```

### Commands

```
  2x -0:00.0 core:confirm (input.hidden-input)
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "color-picker",
      "open-on-github"
    ],
    "autoHideMenuBar": true,
    "followSymlinks": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by ChaoticMind** [comment]
See #363

**Comment by abe33** [comment]
Hi @irstavr, You're using a pretty old version of Atom, you should update it, latest version of the minimap only support Atom >= 0.208 and we finally reached 1.0.
