### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setScreenHeightAndWidth' of null

### ISSUE THREAD

**Issue by BhaveshSGupta** [atom-minimap/minimap#375]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.13.1

### Stack Trace

Uncaught TypeError: Cannot read property 'setScreenHeightAndWidth' of null

```
At C:\Users\bhavesh.gupta\.atom\packages\minimap\lib\minimap-element.coffee:416

TypeError: Cannot read property 'setScreenHeightAndWidth' of null
  at atom-text-editor-minimap.MinimapElement.measureHeightAndWidth (C:\Users\bhavesh.gupta\.atom\packages\minimap\lib\minimap-element.coffee:416:5)
  at atom-text-editor-minimap.MinimapElement.pollDOM (C:\Users\bhavesh.gupta\.atom\packages\minimap\lib\minimap-element.coffee:386:38)
  at C:\Users\bhavesh.gupta\.atom\packages\minimap\lib\minimap-element.coffee:90:52
  at ViewRegistry.module.exports.ViewRegistry.performDocumentPoll (C:\Users\bhavesh.gupta\AppData\Local\atom\app-1.0.7\resources\app.asar\src\view-registry.js:217:9)
  at later (C:\Users\bhavesh.gupta\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\underscore-plus\node_modules\underscore\underscore.js:688:21)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "metrics",
      "linter-cpplint",
      "todo-list",
      "vim-mode"
    ],
    "audioBeep": false,
    "followSymlinks": false
  },
  "minimap": {
    "plugins": {
      "git-diff": true,
      "pigments": true,
      "find-and-replace": true,
      "bookmarks": true,
      "selection": true
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-minify, v0.2.2
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
color-picker, v2.0.11
docblockr, v0.7.3
editor-stats, v0.17.0
emmet, v2.3.12
fetch, v0.3.0
file-icons, v1.6.7
language-batchfile, v0.4.0
linter, v1.4.3
linter-clang, v3.1.3
linter-csslint, v1.0.5
linter-htmlhint, v0.1.1
linter-javac, v1.1.0
linter-jshint, v1.1.5
live-archive, v0.1.15
local-history, v3.2.3
minimap, v4.13.1
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.6
minimap-selection, v4.3.0
nuclide-hg-repository, vundefined
nuclide-remote-projects, vundefined
pigments, v0.11.0
project-manager, v1.15.11
save-session, v0.15.7
travis-ci-status, v0.16.0

# Dev
No dev packages
```

**Comment by zer0her0** [comment]
[Enter steps to reproduce below:]

1. Open Atom
2. Update to 4.13.1
3. Move to other app to work
4. Come back and switch to tab w/ a lot of content
5. Crash
6. Crash.
7. Cr...well you get the idea.

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.13.1


### Stack Trace

Uncaught TypeError: Cannot read property 'setScreenHeightAndWidth' of null

```
At /Users/ameier/.atom/packages/minimap/lib/minimap-element.coffee:416

TypeError: Cannot read property 'setScreenHeightAndWidth' of null
  at atom-text-editor-minimap.MinimapElement.measureHeightAndWidth (/Users/ameier/.atom/packages/minimap/lib/minimap-element.coffee:416:5)
  at atom-text-editor-minimap.MinimapElement.attachedCallback (/Users/ameier/.atom/packages/minimap/lib/minimap-element.coffee:91:6)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:150:24)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:242:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:306:21)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
git-log, v0.4.1
minimap, v4.13.1
pdf-view, v0.23.0

# Dev
No dev packages
```

**Comment by erikdonohoo** [comment]
Yep, confirmed for me.  As soon as I updated.

**Comment by abe33** [comment]
Just reloading Atom after the update should be fine too.
