### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setScreenHeightAndWidth' of null

### ISSUE THREAD

**Issue by marcofranssen** [atom-minimap/minimap#376]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.13.1

### Stack Trace

Uncaught TypeError: Cannot read property 'setScreenHeightAndWidth' of null

```
At C:\Users\Marco\.atom\packages\minimap\lib\minimap-element.coffee:416

TypeError: Cannot read property 'setScreenHeightAndWidth' of null
  at atom-text-editor-minimap.MinimapElement.measureHeightAndWidth (C:\Users\Marco\.atom\packages\minimap\lib\minimap-element.coffee:416:5)
  at atom-text-editor-minimap.MinimapElement.pollDOM (C:\Users\Marco\.atom\packages\minimap\lib\minimap-element.coffee:386:38)
  at C:\Users\Marco\.atom\packages\minimap\lib\minimap-element.coffee:90:52
  at ViewRegistry.module.exports.ViewRegistry.performDocumentPoll (C:\Users\Marco\AppData\Local\atom\app-1.0.7\resources\app.asar\src\view-registry.js:217:9)
  at ViewRegistry.<anonymous> (C:\Users\Marco\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\underscore-plus\node_modules\underscore\underscore.js:701:23)
  at ViewRegistry.module.exports.ViewRegistry.requestDocumentPoll (C:\Users\Marco\AppData\Local\atom\app-1.0.7\resources\app.asar\src\view-registry.js:208:21)
  at MutationObserver.<anonymous> (C:\Users\Marco\AppData\Local\atom\app-1.0.7\resources\app.asar\src\view-registry.js:3:61)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "welcome",
      "autocomplete-plus"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "minimap": {
    "plugins": {
      "find-and-replace": true
    },
    "absoluteMode": true
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.12
emmet, v2.3.12
json-schema, v0.1.11
language-babel, v0.11.9
language-csharp, v0.7.0
language-elixir, v0.5.2
language-erlang, v3.0.0
language-fsharp, v0.8.4
language-puppet, v0.14.0
language-scala, v1.1.3
linter, v1.4.3
linter-csslint, v1.0.5
linter-elixirc, v0.2.2
linter-js-yaml, v1.1.1
linter-jscs, v2.0.4
linter-jshint, v1.1.5
linter-pep8, v1.0.1
linter-php, v1.0.3
linter-phpcs, v1.0.6
linter-phpmd, v1.0.0
linter-python-pep8, v0.2.0
linter-scalac, v1.0.2
linter-tidy, v1.0.1
minimap, v4.13.1
minimap-find-and-replace, v4.3.0
omnisharp-atom, v0.24.0
php-getters-setters, v0.5.5
seti-syntax, v0.4.0
seti-ui, v0.8.0
Stylus, v1.2.1
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by wmayner** [comment]
+1

**Comment by piks** [comment]
My Linux Mint 17.2 just threw this same error also.

**Comment by squilter** [comment]
+1

**Comment by mfvico** [comment]
MacBook Pro running Yosemite is also throwing this error

**Comment by JadeGeek** [comment]
+1

**Comment by abe33** [comment]
Sorry guys for the wait, the patch is ready, I just have to publish it.
