### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getLineHeight' of null

### ISSUE THREAD

**Issue by Stanzilla** [atom-minimap/minimap#378]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.13.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getLineHeight' of null

```
At C:\Users\Benjamin\.atom\packages\minimap\lib\minimap-element.coffee:429

TypeError: Cannot read property 'getLineHeight' of null
  at atom-text-editor-minimap.MinimapElement.measureHeightAndWidth (C:\Users\Benjamin\.atom\packages\minimap\lib\minimap-element.coffee:429:7)
  at atom-text-editor-minimap.MinimapElement.attachedCallback (C:\Users\Benjamin\.atom\packages\minimap\lib\minimap-element.coffee:91:6)
  at atom-pane.PaneElement.activeItemChanged (C:\Users\Benjamin\AppData\Local\atom\app-1.0.7\resources\app.asar\src\pane-element.js:150:24)
  at Emitter.module.exports.Emitter.emit (C:\Users\Benjamin\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\Benjamin\AppData\Local\atom\app-1.0.7\resources\app.asar\src\pane.js:242:22)
  at Pane.module.exports.Pane.activateItem (C:\Users\Benjamin\AppData\Local\atom\app-1.0.7\resources\app.asar\src\pane.js:306:21)
  at tabs-tab.<anonymous> (C:\Users\Benjamin\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\Benjamin\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\Benjamin\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "spell-check",
      "highlight-css-color",
      "white-cursor",
      "feedback",
      "welcome",
      "auto-indent",
      "linter-luacheck",
      "atom-beautify",
      "build"
    ],
    "autoHideMenuBar": true,
    "excludeVcsIgnoredPaths": false
  },
  "minimap": {
    "displayPluginsControls": false,
    "adjustMinimapWidthToSoftWrap": false,
    "v4Preview": true,
    "scrollAnimation": true
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.4.2
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-sass, v0.1.0
css-color-underline, v1.0.1
file-icons, v1.6.9
fold-functions, v0.3.1
indent-guide-improved, v1.4.2
indentation-indicator, v0.6.0
keyboard-localization, v1.4.8
language-blade, v0.15.0
language-gitignore, v0.2.0
language-lua, v0.9.4
laravel, v0.7.0
less-than-slash, v0.8.0
line-ending-selector, v0.0.5
linter, v1.4.3
linter-lua, v1.0.0
linter-lua-findglobals, v1.0.0
linter-php, v1.0.3
minimap, v4.13.2
one-dark-syntax, v1.1.0
one-dark-ui, v1.0.3
open-recent, v2.3.0
tabs-to-spaces, v0.11.1
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi there, I believe the issue is the same issue than #374, please see my reply [here](https://github.com/atom-minimap/minimap/issues/374#issuecomment-135363998). 

I'll close this issue as soon as you confirm that a reload fix things for you.

**Comment by Stanzilla** [comment]
Yes, can confirm.
