### ISSUE TITLE
Failed to load the minimap package

### ISSUE THREAD

**Issue by alex88** [atom-minimap/minimap#389]
Right after I start atom I get this error:

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.13.4

### Stack Trace

Failed to load the minimap package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/alessandro/.atom/packages/minimap/lib/main.coffee:1:34)
    at Object.<anonymous> (/Users/alessandro/.atom/packages/minimap/lib/main.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-emblem, v0.2.3
atom-typescript, vundefined
language-elixir, v0.5.2
language-haml, v0.22.2
language-spacebars, v0.2.2
linter, v1.6.0
minimap, v4.13.4
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by mdalacu** [comment]
Same here, on Ubuntu 15.04

**Comment by abe33** [comment]
Hi there, 

Is there an `event-kit` directory in the minimap's `node_modules` folder? Also, was there some error reported during the update? 
Actually, I think I can remove `event-kit` from the dependencies (as it's now part of Atom) but I would like to make sure there's not an error somewhere else.

**Comment by alex88** [comment]
@abe33 what's the path of the minimap package?

**Comment by alex88** [comment]
@abe33 nm found it `~/.atom/packages/minimap/.travis.yml` anyway, there is no `node_modules` folder. Tried to reinstall and now it works! Maybe an exception during node_modules install

**Comment by abe33** [comment]
@alex88 It should be in your home under `.atom/packages/minimap`.

**Comment by alex88** [comment]
I think this can be closed

**Comment by abe33** [comment]
Yep, if it's fine for you I'll close then.

**Comment by alex88** [comment]
At least if someone else has the same issue he'll know it's just an `npm install` issue

**Comment by mdalacu** [comment]
After i have properly configured ~/.atom/.apmrc ...by putting an ending "/" to http-proxy key ...instalation of minimap worked through GUI. Strange.

**Comment by Banjerr** [comment]
i'm still getting this issue. i've tried running npm install in the minimap directory, but that didn't seem to help. I do have a node_module folder though.

**Comment by Banjerr** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.2
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.16.1


### Stack Trace

Failed to activate the minimap package

```
At Cannot find module './register-or-update-element'

Error: Cannot find module './register-or-update-element'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Krsna/.atom/packages/minimap/node_modules/atom-utils/lib/atom-utils.js:41:30)
    at Object.<anonymous> (/Users/Krsna/.atom/packages/minimap/node_modules/atom-utils/lib/atom-utils.js:50:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "batman-syntax"
    ],
    "projectHome": "/Users/Krsna/Sites"
  },
  "minimap": {
    "scrollAnimation": true
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.8.0
atom-pair, v2.0.10
batman-syntax, v1.0.1
color-picker, v2.0.13
default-language, v0.2.0
emmet, v2.3.14
laravel, v0.7.0
minimap, v4.16.1
neon-cursor, v0.2.0
neon-selection, v0.3.2
nyancat, v0.2.0
pigments, v0.19.0
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by abe33** [comment]
@Banjerr 

> i'm still getting this issue. i've tried running npm install in the minimap directory, but that didn't seem to 

Generally, you should run `apm install` rather than `npm install` (but it doesn't matter much here because there's no binary to compile against Atom).

As for the node_modules directory, you should make sure that `atom-utils` version is `>= 0.7.0` (which introduce the `registerOrUpdateElement` method). What's weird is that the `package.json` file explicitly ask for version `0.7.x` (see https://github.com/atom-minimap/minimap/blob/master/package.json#L36) so even `npm install` should honour the requested version.
