### ISSUE TITLE
Uncaught TypeError: this.textEditorElement.onDidChangeScrollTop is not a function

### ISSUE THREAD

**Issue by ashleysommer** [atom-minimap/minimap#393]
1. Install Atom 1.0.19
2. Install Minimap v4.14.0

**Atom Version**: 1.0.19
**System**: "Fedora release
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.14.0

### Stack Trace

Uncaught TypeError: this.textEditorElement.onDidChangeScrollTop is not a function

```
At /home/flubba86/.atom/packages/minimap/lib/minimap.coffee:59

TypeError: this.textEditorElement.onDidChangeScrollTop is not a function
  at new Minimap (/home/flubba86/.atom/packages/minimap/lib/minimap.coffee:59:33)
  at Main.minimapForEditor (/home/flubba86/.atom/packages/minimap/lib/main.coffee:253:21)
  at /home/flubba86/.atom/packages/minimap/lib/main.coffee:297:18
  at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:276:9)
  at Main.initSubscriptions (/home/flubba86/.atom/packages/minimap/lib/main.coffee:296:39)
  at Main.toggle (/home/flubba86/.atom/packages/minimap/lib/main.coffee:146:8)
  at atom-workspace.subscriptionsOfCommands.atom.commands.add.minimap:toggle (/home/flubba86/.atom/packages/minimap/lib/main.coffee:107:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-li.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLOListElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -1:05.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:04.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:03.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:03.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:03.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:03.4.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:02.9.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -1:02.6.0 core:delete (atom-text-editor.editor.is-focused)
     -1:01.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:00.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:30.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:27.6.0 scope-inspector:toggle-sidebar (atom-text-editor.editor)
     -0:22.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:21.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:19.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 minimap:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {},
  "minimap": {
    "plugins": {
      "find-and-replace": true,
      "git-diff": true,
      "pigments": true,
      "highlight-selected": true
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
atom-typescript, v7.4.6
autocomplete-php, v0.3.7
color-picker, v2.0.13
emmet, v2.3.13
highlight-selected, v0.10.1
jshint, v1.8.1
language-rust, v0.4.5
linter, v1.8.1
linter-rust, v0.2.10
minimap, v4.14.0
minimap-find-and-replace, v4.3.1
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
pigments, v0.18.0
racer, v0.17.2
scope-inspector, v1.0.1

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @ashleysommer, how did you get the 4.14 update? It shouldn't have been available for Atom 1.0.19.
I would advise you to downgrade to version 4.13.4 for the time being, I'm planning to spend some time this week-end to make a version compatible with both 1.0.19 and beta/master.

**Comment by me-benni** [comment]
Atom Beta creates an error and shows this issue (https://github.com/atom-minimap/minimap/issues/387) and lets you install version 4.14

**Comment by abe33** [comment]
I've published a new version that should properly handles both versions (stable and beta). Let me know if you still have any trouble.

**Comment by me-benni** [comment]
fixed it on both versions. thx :)

**Comment by ashleysommer** [comment]
@abe33 
I was on atom 1.1-beta1 for testing, I had to upgrade to Minimap 4.14 to fix an issue in that version.
I also have Atom 1.0.19 installed on my system for general use. I guess they use the same plugin directory, that is how I was using 4.14 in atom 1.0.19.

I installed your update, and it is working in both versions now. Thanks :+1:

**Comment by abe33** [comment]
@ashleysommer You're welcome :), I'll close the issue then.
