### ISSUE TITLE
Uncaught TypeError: registerOrUpdateElement is not a function

### ISSUE THREAD

**Issue by Tuxie** [atom-minimap/minimap#402]
[Enter steps to reproduce below:]

1. Open a file with minimap installed
2. Click on the cog icon on the minimap.

**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.16.0

### Stack Trace

Uncaught TypeError: registerOrUpdateElement is not a function

```
At /C:/Users/perwi/.atom/packages/minimap/lib/minimap-quick-settings-element.coffee:298

TypeError: registerOrUpdateElement is not a function
  at Object.<anonymous> (C:\Users\perwi\.atom\packages\minimap\lib\minimap-quick-settings-element.coffee:158:31)
  at Object.<anonymous> (C:\Users\perwi\.atom\packages\minimap\lib\minimap-quick-settings-element.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\perwi\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.openQuickSettingSubscription.subscribeTo.mousedown [as __NONE__] (C:\Users\perwi\.atom\packages\minimap\lib\minimap-element.coffee:215:36)
  at HTMLDivElement.listener (C:\Users\perwi\.atom\packages\minimap\node_modules\atom-utils\lib\mixins\events-delegation.js:108:41)

```

### Commands

```
  2x -5:28.6.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
  2x -5:19.3.0 tool-bar:toggle (atom-text-editor.editor.mini.is-focused)
  5x -5:11.1.0 menu-manager:show (atom-text-editor.editor.mini)
     -3:50.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -3:44.6.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -3:44 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:43.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -3:33.8.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -3:27.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:23 core:delete (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "metro-ui",
      "base16-tomorrow-dark-theme"
    ],
    "autoHideMenuBar": true
  },
  "minimap": {}
}
```

### Installed Packages

```coffee
# User
metro-ui, v2.2.2
minimap, v4.16.0
vim-mode, v0.62.0
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @Tuxie, do you still get this issue after having reload Atom?

**Comment by eduardomcrodrigues** [comment]
Just had this issue it right now.

**Comment by Tuxie** [comment]
It seems to work after fully restarting Atom.

**Comment by nook24** [comment]
I can confirm, after a restart of Atom the error is gone on OS X, Atom 1.0.19, minimap v4.16.0

**Comment by abe33** [comment]
It looks like there's still issues in the way Atom handles its module cache after an update. It should have cleared it to reload the new version of `atom-utils`, which now provides `registerOrUpdateElement`, but it didn't. This should not play much in the future but I understand it's still frustrating.
