### ISSUE TITLE
Failed to activate minimap package

### ISSUE THREAD

**Issue by michael-yx-wu** [atom-minimap/minimap#407]
[Enter steps to reproduce below:]

1. start up atom

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.16.0

### Stack Trace

Failed to activate the minimap package

```
At registerOrUpdateElement is not a function

TypeError: registerOrUpdateElement is not a function
  at Object.<anonymous> (/Users/Michael/.atom/packages/minimap/lib/minimap-element.coffee:744:18)
  at Object.<anonymous> (/Users/Michael/.atom/packages/minimap/lib/minimap-element.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Main.activate (/Users/Michael/.atom/packages/minimap/lib/main.coffee:102:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:300:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:625:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:79:25)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "rst-preview"
    ],
    "disabledPackages": [
      "linter-pep8"
    ]
  },
  "minimap": {
    "plugins": {
      "find-and-replace": true,
      "git-diff": true,
      "selection": true
    },
    "scrollAnimation": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v7.7.2
autocomplete-python, v0.10.1
build, v0.48.0
build-gradle, v0.3.0
language-docker, v1.1.3
language-gradle, v0.0.3
language-groovy, v0.4.0
language-restructuredtext, v0.9.0
linter, v1.10.0
linter-clang, v3.3.0
linter-javac, v1.3.0
linter-pylint, v1.0.3
linter-shellcheck, v1.0.2
minimap, v4.16.0
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
omni-ruler, v0.4.2
rest-client, v0.5.0
rst-preview-pandoc, v0.1.11
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @michael-yx-wu, do you still get this error after running the `Update Package Dependencies: Update` command and reloading Atom? 

This looks like #402 for me.

**Comment by michael-yx-wu** [comment]
`apm update` doesn't do anything for me. For what it's worth, I'm using the atom sync settings package to keep my atom settings the same across machines.

**Comment by michael-yx-wu** [comment]
It seems like uninstalling/reinstalling the minimap package was not enough. I had to uninstall/reinstall all minimap related packages as well.

**Comment by abe33** [comment]
Hmm, ok, I think I see what's the problem, it looks like it was still the version of `atom-utils` in the plugins that was loaded. Thanks for the follow up, I'll make a pass on the plugin to make sure their version is up to date. I'll close it then.
