### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of null

### ISSUE THREAD

**Issue by mrtuborg** [atom-minimap/minimap#408]
Want to toggle on / toggle off minimap  
execute:   
minimap:toggle  

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.16.0

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of null

```
At /Users/vn/.atom/packages/minimap/lib/minimap.coffee:88

TypeError: Cannot read property 'dispose' of null
  at Minimap.module.exports.Minimap.destroy (/Users/vn/.atom/packages/minimap/lib/minimap.coffee:88:19)
  at /Users/vn/.atom/packages/minimap/lib/main.coffee:141:15
  at Map.forEach (native)
  at Main.toggle (/Users/vn/.atom/packages/minimap/lib/main.coffee:140:25)
  at atom-workspace.subscriptionsOfCommands.atom.commands.add.minimap:toggle (/Users/vn/.atom/packages/minimap/lib/main.coffee:107:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:143:19)
  at ToolbarView.module.exports.ToolbarView.executeCmd (/Users/vn/.atom/packages/command-toolbar/lib/toolbar-view.coffee:166:21)
  at ToolbarView.module.exports.ToolbarView.btnClick (/Users/vn/.atom/packages/command-toolbar/lib/toolbar-view.coffee:171:6)
  at space-pen-div.<anonymous> (/Users/vn/.atom/packages/command-toolbar/lib/toolbar-view.coffee:283:55)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
  2x -0:36.2.0 linter:toggle (atom-text-editor.editor.is-focused)
     -0:26.9.0 minimap:toggle-split-diff (atom-text-editor.editor.is-focused)
  3x -0:12.6.0 minimap:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-light-syntax"
    ],
    "projectHome": "/Users/vn",
    "disabledPackages": [
      "vim-mode-plus"
    ]
  },
  "minimap": {
    "plugins": {
      "highlight-selected": true,
      "split-diff": false
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-beautify, v0.28.16
atom-hyperlinks, v0.1.5
autocomplete-clang, v0.8.8
build-markdown, v1.0.2
colorful-json, v1.0.0
command-toolbar, v1.0.12
file-type-icons, v0.7.3
git-log, v0.4.1
highlight-column, v0.5.0
highlight-line, v0.11.0
highlight-selected, v0.10.1
hyperclick, v0.0.32
js-hyperclick, v1.4.0
json-colorer, v0.3.0
language-doxygen, v0.2.1
language-markdown, v0.1.2
linter, v1.10.0
linter-cpplint, v0.1.4
linter-markdown, v1.2.1
linter-shellcheck, v1.0.2
markdown-assistant, v0.1.0
markdown-deluxe, v1.0.0
markdown-mindmap, v0.2.4
markdown-preview-opener, v0.1.1
markdown-preview-plus, v2.2.2
markdown-preview-plus-opener, v0.2.0
markdown-scroll-sync, v0.4.2
markdown-table-formatter, v2.5.4
minimap, v4.16.0
minimap-highlight-selected, v4.3.1
minimap-split-diff, v0.2.0
pigments, v0.18.1
pretty-json, v0.4.1
project-manager, v2.6.5
project-view, v0.1.2
save-session, vundefined
symbols-tree-view, v0.10.1
tool-bar, v0.1.9
tree-view-git-branch, v0.0.6
tree-view-git-status, v0.2.2
tree-view-open-files, v0.2.4
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @mrtuborg, it looks like it's related to the `tool-bar` package in some way as I can't reproduce it using the command palette, do you happen to have a custom button to toggle the minimap? Could you share it with me so I can to reproduce that myself?

**Comment by mrtuborg** [comment]
I have tried with usual command panel. The same effect. BTW, on my home OSX it works perfectly. At home I have El Capitan. It is the only difference.

**Comment by abe33** [comment]
Ok, I'm still on Yosemite at work, but I have El Capitan at home, I'll take a look at that tonight.

**Comment by mrtuborg** [comment]
Everything fine with El Capitan, I will try investigate more this issue.
