### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by m-schrepel** [atom-minimap/minimap#424]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Microsoft Windows 10 Pro
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.17.0

### Stack Trace

Uncaught TypeError: Cannot read property 'apply' of undefined

```
At C:\Users\matthew\.atom\packages\minimap\node_modules\atom-utils\lib\register-or-update-element.js:14

TypeError: Cannot read property 'apply' of undefined
    at atom-text-editor-minimap.Object.defineProperty.value [as attributeChangedCallback] (C:\Users\matthew\.atom\packages\minimap\node_modules\atom-utils\lib\register-or-update-element.js:14:32)
    at Object.module.exports.handleScroll (file:///C:/Users/matthew/.atom/packages/minimap-autohide/lib/minimap-autohide.coffee:30:18)
    at file:///C:/Users/matthew/.atom/packages/minimap-autohide/lib/minimap-autohide.coffee:27:10
    at Emitter.module.exports.Emitter.emit (C:\Users\matthew\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\matthew\AppData\Local\atom\app-1.3.1\resources\app.asar\src\text-editor-element.js:113:47
    at Emitter.module.exports.Emitter.emit (C:\Users\matthew\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateScrollTop (C:\Users\matthew\AppData\Local\atom\app-1.3.1\resources\app.asar\src\text-editor-presenter.js:1024:29)
    at TextEditorPresenter.module.exports.TextEditorPresenter.commitPendingScrollTopPosition (C:\Users\matthew\AppData\Local\atom\app-1.3.1\resources\app.asar\src\text-editor-presenter.js:1919:14)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (C:\Users\matthew\AppData\Local\atom\app-1.3.1\resources\app.asar\src\text-editor-presenter.js:109:12)
    at LinesYardstick.module.exports.LinesYardstick.prepareScreenRowsForMeasurement (C:\Users\matthew\AppData\Local\atom\app-1.3.1\resources\app.asar\src\lines-yardstick.js:26:63)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getState (C:\Users\matthew\AppData\Local\atom\app-1.3.1\resources\app.asar\src\text-editor-presenter.js:182:27)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (C:\Users\matthew\AppData\Local\atom\app-1.3.1\resources\app.asar\src\text-editor-component.js:195:38)
    at C:\Users\matthew\AppData\Local\atom\app-1.3.1\resources\app.asar\src\text-editor-component.js:298:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (C:\Users\matthew\AppData\Local\atom\app-1.3.1\resources\app.asar\src\view-registry.js:190:9)
    at C:\Users\matthew\AppData\Local\atom\app-1.3.1\resources\app.asar\src\view-registry.js:3:61
```

### Commands

```
     -5:48.5.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -5:46 core:move-down (div.panels-item)
  4x -5:44 core:move-up (button.btn.btn-default.icon.icon-link-external)
  2x -5:40.4.0 core:move-down (button.btn.btn-default.icon.icon-link-external)
  2x -5:39.9.0 core:move-up (button.btn.btn-default.icon.icon-link-external)
  3x -5:34.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-sharp-syntax"
    ]
  },
  "minimap": {
    "plugins": {
      "minimap-autohide": true
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
file-icons, v1.6.13
jshint, v1.8.3
language-cfml, v0.10.0
minimap, v4.17.0
minimap-autohide, v0.10.1
one-sharp-syntax, v1.1.1

# Dev
No dev packages
```

**Comment by phoenixweiss** [comment]
I have the same issue with atom 1.3.1 on OS X.

**Comment by dflock** [comment]
Same issue on Ubuntu 13.10, with atom 1.3.1.

I initially had #418 - I restarted atom a few times, then I did this, as suggested:

```
cd ~/.atom/packages/minimap
rm -rf node_modules/atom-utils
apm install
```

That didn't help. Then I uninstalled the package from within atom, then re-installed it and now I'm here.

**Comment by devinus** [comment]
Same issue after updating.

**Comment by mistadikay** [comment]
reproducible on 1.4.0-beta0

**Comment by dragonfire1119** [comment]
Just got the update and now getting the error on windows 8.

**Comment by maplewizard** [comment]
Same issue after updating. OSX, atom 1.3.1

**Comment by mair0z** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Linux Mint
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.17.0


### Stack Trace

Uncaught TypeError: Cannot read property 'apply' of undefined

```
At /home/marioz/.atom/packages/minimap/node_modules/atom-utils/lib/register-or-update-element.js:14

TypeError: Cannot read property 'apply' of undefined
    at atom-text-editor-minimap.Object.defineProperty.value [as attributeChangedCallback] (/home/marioz/.atom/packages/minimap/node_modules/atom-utils/lib/register-or-update-element.js:14:32)
    at Object.createView (/home/marioz/.atom/packages/minimap/lib/minimap-element.js:37:21)
    at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app.asar/src/view-registry.js:83:72)
    at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app.asar/src/view-registry.js:68:21)
    at /home/marioz/.atom/packages/minimap/lib/main.js:336:39
    at /usr/share/atom/resources/app.asar/src/workspace.js:287:16
    at /usr/share/atom/resources/app.asar/src/workspace.js:352:18
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app.asar/src/pane-container.js:375:27)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:359:28
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app.asar/src/pane.js:340:20)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:311:14)
    at /usr/share/atom/resources/app.asar/src/workspace.js:492:18
    at process._tickDomainCallback (node.js:411:9)
```

### Commands

```
     -0:17.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  2x -0:04.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-dark-ui",
      "darkular-syntax"
    ],
    "packagesWithKeymapsDisabled": [
      "git-diff-details"
    ]
  },
  "minimap": {
    "plugins": {
      "git-diff": true
    },
    "absoluteMode": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.10.3
color-picker, v2.0.14
colorful-json, v1.0.0
darkular-syntax, v0.3.0
file-icons, v1.6.13
git-diff-details, v0.21.0
highlight-line, v0.11.0
highlight-selected, v0.11.1
js-hyperclick, v1.4.1
jshint, v1.8.3
minimap, v4.17.0
minimap-git-diff, v4.1.8
node-debugger, v1.3.0
pigments, vundefined

# Dev
No dev packages
```

**Comment by dagstuan** [comment]
+1

**Comment by abe33** [comment]
I just published new version that bumps the version of atom-utils to the version with the fix.
