### ISSUE TITLE
Failed to instal

### ISSUE THREAD

**Issue by kiochan** [atom-minimap/minimap#425]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.3
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.18.0

### Stack Trace

Failed to load the minimap package

```
At this.initializePlugins is not a function

TypeError: this.initializePlugins is not a function
    at new Main (/Users/sunxingchen/.atom/packages/minimap/lib/main.js:75:10)
    at Object.<anonymous> (/Users/sunxingchen/.atom/packages/minimap/lib/main.js:350:16)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:661:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:115:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:511:30)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -1:40.8.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:40.6.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:40.1.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:39.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:39.5.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:39.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:38.9.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:38.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:37.9.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:37.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:32.6.0 editor:log-cursor-scope (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -1:28.2.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:23.7.0 editor:log-cursor-scope (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 34x -1:20.6.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:33.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:19.8.0 blur (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "minimap": {}
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.11.3
ex-mode, v0.7.0
jquery-snippets, v11.0.0
linter, v1.11.3
linter-gcc, v0.5.5
linter-jshint, v1.2.1
minimap, v4.18.0
relative-numbers, v0.2.4
simplified-chinese-menu, v3.4.2
tester, v0.0.2
vim-mode, v0.63.0
vim-shift-movers, v0.1.3

# Dev
No dev packages
```

**Comment by fundon** [comment]
Dup of https://github.com/atom-minimap/minimap/issues/418.
