### ISSUE TITLE
Failed to load the minimap package (EPERM: operation not permitted, write)

### ISSUE THREAD

**Issue by LendLord** [atom-minimap/minimap#426]
[Enter steps to reproduce below:]

1. Install minimap
2. Error occured

**Atom Version**: 1.4.0-beta0
**System**: Unknown Windows Version (Windows 10)
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.18.0

### Stack Trace

Failed to load the minimap package

```
At C:/Users/Lord/.atom/packages/minimap/lib/main.js: EPERM: operation not permitted, write

Error: C:/Users/Lord/.atom/packages/minimap/lib/main.js: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:663:20)
    at SyncWriteStream.write (fs.js:1981:6)
    at Function.log (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\node_modules\debug\node.js:106:17)
    at enabled (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\node_modules\debug\debug.js:117:11)
    at Logger.debug (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\file\logger.js:92:31)
    at File.parse (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:573:14)
    at File.parseCode (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:691:20)
    at C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\pipeline.js:167:12
    at File.wrap (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:639:16)
    at Pipeline.transform (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\pipeline.js:165:17)
    at Object.exports.compile (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\babel.js:51:16)
    at compileFileAtPath (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\compile-cache.js:72:44)
    at Object.defineProperty.value [as .js] (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\compile-cache.js:203:18)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\native-compile-cache.js:41:21)
    at Package.module.exports.Package.requireMainModule (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:721:27)
    at C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package-manager.js:443:14)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package-manager.js:393:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\atom-environment.js:684:21)
    at module.exports (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\initialize-application-window.js:28:10)
    at setupWindow (file:///C:/Users/Lord/AppData/Local/atom/app-1.4.0-beta0/resources/app.asar/static/index.js:85:5)
    at window.onload (file:///C:/Users/Lord/AppData/Local/atom/app-1.4.0-beta0/resources/app.asar/static/index.js:40:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-csslint",
      "achievements",
      "save-session",
      "docblockr",
      "whitespace",
      "atom-ternjs",
      "minimap-highlight-selected",
      "minimap-pigments",
      "minimap-selection",
      "minimap-split-diff",
      "linter",
      "linter-htmlhint",
      "linter-jshint",
      "linter-php"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "minimap": {
    "plugins": {
      "highlight-selected": true,
      "pigments": true,
      "selection": true,
      "split-diff": true
    },
    "scrollAnimation": true
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.4
aligner-php, v1.0.0
atom-alignment, v0.12.1
atom-beautify, vundefined
atom-material-ui, v0.8.0
autoclose-html, v0.19.0
color-picker, v2.0.14
file-icons, v1.6.13
highlight-selected, v0.11.1
indent-guide-improved, v1.4.5
minimap, v4.18.0
pigments, v0.19.3
sync-settings, v0.6.0
synced-sidebar, v0.4.3
tool-bar, v0.1.9
tool-bar-almighty, v0.5.0
tool-bar-main, v0.0.8
trailing-spaces, v0.3.2
tree-view-open-files, v0.3.0
wakatime, v5.0.2

# Dev
No dev packages
```

**Comment by mojason-81** [comment]
Just wanted to drop a comment that I've had this error as well.

Atom Version: 1.3.1
System: Ubuntu 14.04
Thrown From: minimap package, v4.18.0

Steps:
Update minimap -> got error
Uninstalled minimap
Installed minimap -> got error, minimap was not displayed in open file
Restarted atom -> the world seems right again.  No more defects noted.

I run pretty much the same setup on my laptop for work that I do at home, and I've seen the same behavior on that machine as well.  Doesn't seem to be causing any major issues though.

**Comment by LendLord** [comment]
thanks for comment, but I already tried reinstall atom and minimap and it didnt help

**Comment by nealfennimore** [comment]
I ran into the same issue when updating. Restarting Atom worked for me.

**Comment by ggamel** [comment]
Likewise, this issue required a disable/enable + restart. Working now.

**Comment by LendLord** [comment]
Issue happend only if I install/upgrade package in version >1.3.1, but if I install package in version 1.3.1 and then upgrade to 1.4.0 there is no problem at all. So this issue not in package, it's atom issue. Thanks all.

**Comment by abe33** [comment]
Sorry guys, I completely missed this thread, it looks like an issue with the babel compilation in Atom.I'm not sure if there's anything I can do at the minimap level to fix this.

**Comment by TeChn4K** [comment]
Upgrade -> disable -> enable -> restart Atom : working now

**Comment by jcrwhite** [comment]
I tried disable/enabling, reinstalling, nothing worked. I has to remove atom completely then reinstall minimap for it to work.

**Comment by miftahafina** [comment]
@jcrwhite I restarted and everything is okay again. Maybe you have to pray first.

**Comment by abe33** [comment]
Would you mind opening an issue on atom repo? As far as I can tell it's an issue with Atom itself.

**Comment by LendLord** [comment]
Already posted similar issue with default package, but it was closed
https://github.com/atom/atom/issues/10056

**Comment by zehel2892** [comment]
Restarting atom using <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>r</kbd> worked for me.
Most of the time atom needs to be restarted when something is changed . :+1:

**Comment by hitautodestruct** [comment]
+1

**Comment by neko** [comment]
+1

**Comment by d4rkd0s** [comment]
+1 fix er

**Comment by superzadeh** [comment]
+1

**Comment by IbnSaeed** [comment]
just received this error 1.4 beta 3

**Comment by mraak** [comment]
+1

**Comment by abe33** [comment]
I reopened the issue @LendLord created in the Atom repo, but as is there's nothing I can do at the minimap level. 

It looks like some people succeeded to get rid of this issue by restarting or reinstalling Atom, if it doesn't work for you, I would advise to report as much information as possible in the atom issue (atom/atom#10056). 

Also, I'll be curious to know how many of you are using the `sync-settings` package? As it meddles with packages installation I'd make it my first suspect here.

**Comment by LendLord** [comment]
After some reinstalls problem with minimap is gone, but its still persist with other packages like line-ending-selector or linter-php. And yes, Iam using sync-settigs package. 
Also I get this error only on my laptop with win10.

**Comment by foligo** [comment]
Restarting atom using Ctrl+Alt+r worked for me as well. :)

**Comment by abe33** [comment]
@LendLord @hitautodestruct @neko @d4rkd0s @superzadeh @mraak: Do you mind helping with atom/atom#10056 by providing as many information as possible so that someone from core can look into it? 
I'll say that version of Atom, OS and such would be the bare minimum. They may need additional information though.

**Comment by thorsten-mueller** [comment]
Error still appears when updating packages after Atom update to 1.4

Though a simple restart seems to solve it right away. (no disable/enable necessary in my case)

**Comment by foligo** [comment]
OS Ubuntu 15.10;  Atom 1.0.19

**Comment by abe33** [comment]
@foligo You should probably update Atom, you are 4 minor versions behind.

**Comment by thorsten-mueller** [comment]
@abe33 I had the same error still in 1.4 after updating with the .deb file. This happened on two machines one with Kubuntu 15.04 the other with Kubuntu 15.10. Directly after updating Atom I updated packages and that's  when the error appears. Restarting Atom and everything works, so minor issue.

(Though reading through the posts I'm not sure it's actually the error reported here. I came to this post by the 'already reported' button in the error message.)

Sadly I can't  reproduce since it seems the error does only appear during the update. Disabling and enabling mini-map seems not to throw the error.

**Comment by abe33** [comment]
@thorsten-mueller It should be solved with 1.5.0 release, as you can see with the atom PR linked above. It was related to babel not silencing some stderr output (I guess this issue also happens with CS code but was properly recovered by Atom by silencing the errors)

**Comment by Sheridan-Tech** [comment]
+1 running 1.3.2

**Comment by Sheridan-Tech** [comment]
+1 

I'm running 1.3.2.

**Comment by LegitStack** [comment]
restart after updating it fixed it

**Comment by MrMahdiBH** [comment]
The problem pops up when installing the package manually.
After installing it from Settings>>Install its working fine.
**Running Version**: 1.5.2

**Comment by Angelfirenze01** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.3
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.19.0


### Stack Trace

Failed to load the minimap package

```
At this.initializePlugins is not a function

TypeError: this.initializePlugins is not a function
    at new Main (/Users/Angelfirenze/.atom/packages/minimap/lib/main.js:86:10)
    at Object.<anonymous> (/Users/Angelfirenze/.atom/packages/minimap/lib/main.js:367:16)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:721:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:443:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:522:30)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -5:26.9.0 application:add-project-folder (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
break-time, v0.2.1
color-picker, v2.1.1
minimap, v4.19.0
pigments, v0.24.1
saveallthetime, v0.2.1
statusbar-datetime, v0.9.7
sublime-word-navigation, v0.1.2
time-status, v1.1.2
travis-ci-status, v1.0.0
vim-mode, v0.64.0
wakatime, v5.0.8

# Dev
No dev packages
```

**Comment by neopunisher** [comment]
Mine happened after syncing my settings of backup and installing all the new packages on a new linux machine
