### ISSUE TITLE
Uncaught TypeError: this.initializePlugins is not a function

### ISSUE THREAD

**Issue by bartzushka** [atom-minimap/minimap#427]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Microsoft Windows 10 Pro
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.18.0

### Stack Trace

Uncaught TypeError: this.initializePlugins is not a function

```
At /C:/Users/Bartz/.atom/packages/minimap/lib/main.js:102

TypeError: this.initializePlugins is not a function
    at new Main (C:/Users/Bartz/.atom/packages/minimap/lib/main.js:75:10)
    at Object.<anonymous> (C:/Users/Bartz/.atom/packages/minimap/lib/main.js:350:16)
    at Module._compile (C:\Users\Bartz\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (C:\Users\Bartz\AppData\Local\atom\app-1.3.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Bartz\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:41:21)
    at Object.<anonymous> (C:/Users/Bartz/.atom/packages/minimap/lib/minimap-quick-settings-element.js:4:57)
    at Module._compile (C:\Users\Bartz\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (C:\Users\Bartz\AppData\Local\atom\app-1.3.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Bartz\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:41:21)
    at Object.openQuickSettingSubscription.subscribeTo.mousedown [as __NONE__] (C:\Users\Bartz\.atom\packages\minimap\lib\minimap-element.coffee:295:47)
    at HTMLDivElement.listener (C:\Users\Bartz\.atom\packages\minimap\node_modules\atom-utils\lib\mixins\events-delegation.js:108:41)
```

### Commands

```
     -2:42.7.0 core:save (atom-text-editor.editor.is-focused)
  5x -2:40.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:31.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:39.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:32.4.0 core:save (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  5x -1:29.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:27.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:25.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:25.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.5.0 minimap:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-autocomplete-php",
      "atom-beautify",
      "atom-yii2"
    ]
  },
  "minimap": {
    "absoluteMode": true,
    "displayMinimapOnLeft": true
  }
}
```

### Installed Packages

```coffee
# User
atom-yii, v0.4.1
autocomplete-html-entities, v0.1.0
autocomplete-wordpress-hooks, v0.2.0
color-picker, v2.0.14
minimap, v4.18.0
Remote-FTP, v0.7.14

# Dev
No dev packages
```

**Comment by fundon** [comment]
Dup of https://github.com/atom-minimap/minimap/issues/418.
