### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setTextEditorScrollTop' of null

### ISSUE THREAD

**Issue by gsmetal** [atom-minimap/minimap#438]
[Enter steps to reproduce below:]

I just closed last tab.

**Atom Version**: 1.3.2
**System**: Ubuntu 15.10
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.18.3

### Stack Trace

Uncaught TypeError: Cannot read property 'setTextEditorScrollTop' of null

```
At /home/gsmetal/.atom/packages/minimap/lib/minimap-element.js:968

TypeError: Cannot read property 'setTextEditorScrollTop' of null
    at step (/home/gsmetal/.atom/packages/minimap/lib/minimap-element.js:968:39)
    at update (/home/gsmetal/.atom/packages/minimap/lib/minimap-element.js:1227:7)
```

### Commands

```
     -3:21.8.0 application:new-file (atom-pane.pane.active)
     -3:20.3.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -3:18.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:18.3.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:17.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -3:14.5.0 core:select-all (atom-text-editor.editor.is-focused)
     -3:14.3.0 core:copy (atom-text-editor.editor.is-focused)
     -0:02.6.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "git-blame",
      "activate-power-mode",
      "pigments"
    ],
    "projectHome": "/home/gsmetal/projects",
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      "shared/log",
      "shared/data",
      "shared/sphinxsearch",
      "shared/tmp",
      "tmp",
      ".deploy_cache",
      ".tags*",
      ".gemtags"
    ],
    "audioBeep": false,
    "packagesWithKeymapsDisabled": [
      "blame"
    ]
  },
  "minimap": {
    "scrollAnimation": true,
    "plugins": {
      "find-and-replace": true,
      "highlight-selected": true
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.4.2
atom-eco, v0.2.0
auto-detect-indentation, v0.4.2
autoclose-html, v0.19.0
autocomplete-ctags, v0.3.3
change-case, v0.6.0
highlight-selected, v0.11.1
language-ejs, v0.2.0
language-mediawiki, v2.0.0
language-textile, v0.2.0
minimap, v4.18.3
minimap-find-and-replace, v4.4.0
minimap-highlight-selected, v4.3.1
monokai, v0.18.0
project-manager, v2.6.5
ruby-block, v0.3.5
ruby-syntax-replacer, v0.5.1
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by fundon** [comment]
It's fine on Mac.

**Comment by abe33** [comment]
@gsmetal Thanks for the report! I can reproduce this and I know what triggers this error, I'm even surprised we didn't get this one sooner. I'll push a patch soon.
