### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by vik-borisov** [atom-minimap/minimap#448]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Unknown Windows Version
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.19.0
### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At C:\Users\vikbo\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:132

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at MarkerLayer.module.exports.MarkerLayer.findMarkers (C:\Users\vikbo\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:132:21)
    at DisplayBuffer.module.exports.DisplayBuffer.findFoldMarkers (C:\Users\vikbo\AppData\Local\atom\app-1.4.1\resources\app.asar\src\display-buffer.js:1143:36)
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (C:\Users\vikbo\AppData\Local\atom\app-1.4.1\resources\app.asar\src\display-buffer.js:799:29)
    at DisplayBuffer.module.exports.DisplayBuffer.screenRangeForBufferRange (C:\Users\vikbo\AppData\Local\atom\app-1.4.1\resources\app.asar\src\display-buffer.js:754:20)
    at TextEditorMarker.module.exports.TextEditorMarker.getScreenRange (C:\Users\vikbo\AppData\Local\atom\app-1.4.1\resources\app.asar\src\text-editor-marker.js:141:33)
    at Minimap.decorationsByTypeThenRows (C:/Users/vikbo/.atom/packages/minimap/lib/mixins/decoration-management.js:240:37)
    at atom-text-editor-minimap.drawBackDecorationsForLines (C:/Users/vikbo/.atom/packages/minimap/lib/mixins/canvas-drawer.js:326:38)
    at atom-text-editor-minimap.drawLinesForRanges (C:/Users/vikbo/.atom/packages/minimap/lib/mixins/canvas-drawer.js:216:14)
    at atom-text-editor-minimap.redrawRangesOnLayer (C:/Users/vikbo/.atom/packages/minimap/lib/mixins/canvas-drawer.js:194:12)
    at atom-text-editor-minimap.updateBackDecorationsLayers (C:/Users/vikbo/.atom/packages/minimap/lib/mixins/canvas-drawer.js:149:10)
    at atom-text-editor-minimap.updateCanvas (C:/Users/vikbo/.atom/packages/minimap/lib/mixins/canvas-drawer.js:104:10)
    at atom-text-editor-minimap.update (C:/Users/vikbo/.atom/packages/minimap/lib/minimap-element.js:814:10)
    at C:/Users/vikbo/.atom/packages/minimap/lib/minimap-element.js:717:12
```
### Commands

```
     -1:18.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:17.3.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:16.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:58.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:56.4.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:52.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:47.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:47.6.0 split-diff:diffPanes (atom-text-editor.editor)
     -0:31.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:13.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:13.4.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:13.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -0:11.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:02.6.0 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "minimap": {
    "plugins": {
      "highlight-selected": true,
      "split-diff": true
    }
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-ui, v0.8.1
compare-files, v0.6.2
highlight-selected, v0.11.1
minimap, v4.19.0
minimap-highlight-selected, v4.3.1
minimap-split-diff, v0.3.0
split-diff, v0.5.4

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @vik-borisov, I'm not really sure what happened, can you provide reproduction steps for that issue?
