### ISSUE TITLE
Error: Cannot find module 'mixto'

### ISSUE THREAD

**Issue by yncxjcw** [atom-minimap/minimap#468]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Unknown Windows Version
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.21.0
### Stack Trace

Failed to load the minimap package

```
At Cannot find module 'mixto'

Error: Cannot find module 'mixto'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (E:\Soft\Program\Atom\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (E:\Soft\Program\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Admin\.atom\packages\minimap-master\lib\mixins\plugin-management.js:19:14)
    at Module._compile (E:\Soft\Program\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (E:\Soft\Program\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (E:\Soft\Program\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:/Users/Admin/.atom/packages/minimap/lib/main.js:17:43)
    at Module._compile (E:\Soft\Program\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (E:\Soft\Program\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (E:\Soft\Program\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (E:\Soft\Program\Atom\resources\app.asar\src\package.js:720:27)
    at E:\Soft\Program\Atom\resources\app.asar\src\package.js:116:28
    at Package.module.exports.Package.measure (E:\Soft\Program\Atom\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (E:\Soft\Program\Atom\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (E:\Soft\Program\Atom\resources\app.asar\src\package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (E:\Soft\Program\Atom\resources\app.asar\src\package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (E:\Soft\Program\Atom\resources\app.asar\src\atom-environment.js:684:21)
    at module.exports (E:\Soft\Program\Atom\resources\app.asar\src\initialize-application-window.js:28:10)
    at setupWindow (file:///E:/Soft/Program/Atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///E:/Soft/Program/Atom/resources/app.asar/static/index.js:41:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-chs-menu",
      "emmet",
      "emmet",
      "atom-ctags",
      "color-tabs",
      "emmet-simplified",
      "emmet",
      "css-comb",
      "emmet-simplified",
      "emmet",
      "css-comb"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "E:\\Soft\\Program\\Atom\\github",
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ]
  },
  "minimap": {
    "scrollAnimation": true
  }
}
```
### Installed Packages

``` coffee
# User
auto-id-class, v0.2.6
chester-atom-syntax, v0.1.1
color-picker, v2.1.1
file-icons, v1.7.1
minimap, v4.19.0
simplified-chinese-menu, v3.4.11

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @yncxjcw, it looks like an issue occurred during the package install, can you verify if the `mixto` module is present in the `node_modules` directory of the minimap package? If not, your can run `apm install` in the minimap directory to install. If yes, something went wrong went installing it, remove the whole `mixto` directory and, again, run `apm install` in the minimap directory.

**Comment by aminya** [comment]
This issue is too old. I don't think it is relevant now.
