### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isDestroyed' of undefined

### ISSUE THREAD

**Issue by nseinlet** [atom-minimap/minimap#482]
[Enter steps to reproduce below:]

1. install last atom with last minimap
2. edit an XML or JS file

**Atom Version**: 1.9.0-dev-edcd338
**System**: LMDE 2
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.23.5

### Stack Trace

Uncaught TypeError: Cannot read property 'isDestroyed' of undefined

```
At /home/nse/.atom/packages/minimap/lib/mixins/decoration-management.js:475

TypeError: Cannot read property 'isDestroyed' of undefined
    at Minimap.emitDecorationChanges (/home/nse/.atom/packages/minimap/lib/mixins/decoration-management.js:475:40)
    at Minimap.removeAllDecorationsForMarker (/home/nse/.atom/packages/minimap/lib/mixins/decoration-management.js:575:12)
    at /home/nse/.atom/packages/minimap/lib/mixins/decoration-management.js:349:14
    at Function.module.exports.Emitter.simpleDispatch (/usr/local/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at DisplayMarker.module.exports.DisplayMarker.destroy (/usr/local/share/atom/resources/app.asar/node_modules/text-buffer/lib/display-marker.js:28:20)
    at Selection.module.exports.Selection.destroy (/usr/local/share/atom/resources/app.asar/src/selection.js:52:26)
    at TextEditor.module.exports.TextEditor.destroyed (/usr/local/share/atom/resources/app.asar/src/text-editor.js:380:19)
    at TextEditor.module.exports.Model.destroy (/usr/local/share/atom/resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (/usr/local/share/atom/resources/app.asar/src/pane.js:641:18)
    at atom-tabs.TabBarView.onClick (/usr/local/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:687:17)
```

### Commands

```
     -6:09.9.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -6:08.3.0 project-find:show (ul.list-inline.tab-bar.inset-panel)
     -6:07.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -6:06.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:28 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
     -0:29.4.0 window:toggle-full-screen (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-python-django-templates",
      "atom-copy-on-select",
      "linter-python-pep8",
      "linter-python-pyflakes",
      "linter-pyflakes",
      "atom-python-debugger",
      "language-python",
      "linter-pylint",
      "git-grep"
    ],
    "ignoredNames": [
      ".git",
      ".gitignore",
      "*.pyc"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "minimap": {
    "plugins": {
      "cursorline": true,
      "cursorlineDecorationsZIndex": 0,
      "find-and-replace": true,
      "find-and-replaceDecorationsZIndex": 0,
      "git-diff": true,
      "git-diffDecorationsZIndex": 0,
      "selection": true,
      "selectionDecorationsZIndex": 0
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7 (inactive)
atom-copy-on-select, v1.4.0 (inactive)
atom-dark-ui-slim, v0.47.1 (inactive)
atom-django, v0.3.2 (active)
atom-python-debugger, v0.3.4 (inactive)
autocomplete-python, v1.7.2 (active)
color-picker, v2.1.1 (active)
git-blame, v0.4.8 (inactive)
git-control, v0.7.1 (inactive)
git-difftool, v0.2.7 (inactive)
git-grep, v0.9.0 (inactive)
git-history, v3.2.0 (inactive)
git-log, v0.4.1 (active)
git-tab-status, v1.10.0 (active)
language-python-django-templates, v0.1.0 (inactive)
linter, v1.11.4 (active)
linter-pyflakes, v0.3.0 (inactive)
linter-pylint, v1.2.0 (inactive)
linter-python-pep8, v0.2.0 (inactive)
MagicPython, v0.5.9 (active)
merge-conflicts, v1.4.2 (active)
minimap, v4.23.5 (active)
minimap-color-highlight, v4.1.4 (active)
minimap-cursorline, v0.1.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-selection, v4.4.0 (active)
python-isort, v0.0.7 (active)
python-tools, v0.6.7 (active)
tag, v0.4.0 (active)
xml-formatter, v0.10.0 (inactive)
xml-tools, v0.2.1 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.51.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.1 (inactive)
one-light-ui, v1.3.1 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.10.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.0.6 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.30.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.57.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.0 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.236.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.2.6 (active)
styleguide, v0.45.2 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.93.2 (active)
timecop, v0.33.1 (active)
tree-view, v0.206.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.51.5 (active)
language-clojure, v0.20.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.1 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.18.0 (active)
language-javascript, v0.110.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.0 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.43.2 (inactive)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.49.0 (active)
language-shellscript, v0.22.1 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.27.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.6 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @nseinlet, It's definitely weird, as I'm running the same version of Atom and I'm not seeing this issue (and the whole minimap is written in JS so I pretty much have to open a JS file in order to modify it ;)). Do  you still see that issue after a restart?

**Comment by b1nary** [comment]
I have the same issue. On every single keystroke and mouse click.

**Comment by zhihuitang** [comment]
me too.

**Comment by tobiashofmann88** [comment]
same here...

**Comment by barneydmedia** [comment]
+1

**Comment by b1nary** [comment]
Just for completeness, i just reinstalled it thinking i am going to fix it but it works again as before.

**Comment by marcosalberto** [comment]
same here.

**Comment by marcosalberto** [comment]
Fixed after run `apm update` on terminal

**Comment by eighteyes** [comment]
`apm update` not fixing for me. :(

**Comment by jamsac2012** [comment]
"apm update" fix it for me too. thanks "marcosalberto"
