### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pixelPositionForScreenPosition' of null

### ISSUE THREAD

**Issue by ayon06** [atom-minimap/minimap#486]
Ran the Expose function from the Expose package and ran into this error.

**Atom Version**: 1.7.4
**System**: Microsoft Windows 10 Pro
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.24.0

### Stack Trace

Uncaught TypeError: Cannot read property 'pixelPositionForScreenPosition' of null

```
At C:\Users\dickbutt\AppData\Local\atom\app-1.7.4\resources\app.asar\src\text-editor-element.js:336

TypeError: Cannot read property 'pixelPositionForScreenPosition' of null
    at atom-text-editor.TextEditorElement.pixelPositionForScreenPosition (C:\Users\dickbutt\AppData\Local\atom\app-1.7.4\resources\app.asar\src\text-editor-element.js:336:28)
    at StableAdapter.computeScrollTop (C:/Users/dickbutt/.atom/packages/minimap/lib/adapters/stable-adapter.js:54:42)
    at StableAdapter.getScrollTop (C:/Users/dickbutt/.atom/packages/minimap/lib/adapters/stable-adapter.js:43:36)
    at Minimap.getTextEditorScaledScrollTop (C:/Users/dickbutt/.atom/packages/minimap/lib/minimap.js:454:25)
    at atom-text-editor-minimap.update (C:/Users/dickbutt/.atom/packages/minimap/lib/minimap-element.js:779:36)
    at C:/Users/dickbutt/.atom/packages/minimap/lib/minimap-element.js:751:12
```

### Commands

```
     -6:07.8.0 script:run-options (atom-text-editor.editor.is-focused)
     -6:05.5.0 browser-plus:open (atom-text-editor.editor.is-focused)
     -5:59.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -5:59.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -5:04.8.0 linter:lint (atom-text-editor.editor.is-focused)
  2x -5:01.3.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -4:56.5.0 linter:lint (atom-text-editor.editor.is-focused)
  3x -4:56 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -4:52.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -4:49.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:49.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:47.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:46.4.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
  2x -0:50.1.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:31.2.0 emmet:balance-outward (atom-text-editor.editor.is-focused)
  4x -0:29.5.0 expose:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-tidy"
    ],
    "themes": [
      "atom-material-ui",
      "monokai"
    ]
  },
  "minimap": {
    "absoluteMode": true,
    "plugins": {
      "find-and-replace": true,
      "find-and-replaceDecorationsZIndex": 0,
      "pigments": true,
      "pigmentsDecorationsZIndex": 0
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7
atom-material-ui, v1.2.12
atom-typescript, v8.10.1
browser-plus, v0.0.60
color-picker, v2.1.1
css-specificity, v0.2.2
emmet, v2.4.3
expose, v0.11.1
file-icons, v1.7.12
linter, v1.11.4
linter-csslint, v1.3.2
linter-htmlhint, v1.1.4
linter-javac, v1.9.1
linter-jshint, v2.1.0
minimap, v4.24.0
minimap-find-and-replace, v4.5.1
minimap-pigments, v0.2.1
monokai, v0.18.0
opened-files, v0.3.6
package-sync, v1.1.0
pigments, v0.26.3
project-manager, v2.9.7
script, v3.7.1
Sublime-Style-Column-Selection, v1.5.1
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by AshtonMeuser** [comment]
:+1:

**Comment by AshtonMeuser** [comment]
:+1:
