### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gargullia** [atom-minimap/minimap#500]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Ubuntu 16.04
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:709

TypeError: Cannot read property 'substr' of null
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:709:80
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:376:51
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:403:20
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:215:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -0:30.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.tinted-tab-bar.compact-tab-bar.panel-shadows.panel-contrast.use-animations.compact-tree-view.blend-tree-view.theme-atom-material-syntax-dark.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax-dark, v0.2.5
atom-material-ui, v1.2.13
minimap, v4.24.3

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment]
This is https://github.com/atom/settings-view/issues/766 as was fixed in Atom 1.9..8

**Comment by abe33** [comment]
Hi @Ben3eeE, are you sure it's a minimap issue? I fail to see exactly what's the issue and what's the solution at the minimap level.

**Comment by Ben3eeE** [comment]
This is not an issue in the minimap package. It is an issue in the settings-view that has already been solved. So you can probably close this one.
