### ISSUE TITLE
Uncaught TypeError: Cannot read property 'parentElement' of null

### ISSUE THREAD

**Issue by lzkelley** [atom-minimap/minimap#503]
[Enter steps to reproduce below:]

- Create a file with the following contents

```

if __name__ == '__main__':
    import_main()
```

- Save it as `test_error.py`.  

- Fold the code

![minimap_err](https://cloud.githubusercontent.com/assets/3839265/16128952/bfdd65ac-33d0-11e6-889f-cf598919a8ea.gif)

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.2
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.24.6

### Stack Trace

Uncaught TypeError: Cannot read property 'parentElement' of null

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/src/lines-tile-component.js:282

TypeError: Cannot read property 'parentElement' of null
    at LinesTileComponent.module.exports.LinesTileComponent.buildLineNode (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/lines-tile-component.js:282:42)
    at LinesTileComponent.module.exports.LinesTileComponent.updateLineNodes (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/lines-tile-component.js:138:34)
    at LinesTileComponent.module.exports.LinesTileComponent.updateSync (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/lines-tile-component.js:94:12)
    at LinesComponent.module.exports.TiledComponent.updateTileNodes (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/tiled-component.js:67:19)
    at LinesComponent.module.exports.TiledComponent.updateSync (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/tiled-component.js:30:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:265:34)
    at TextEditorComponent.module.exports.TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:662:14)
    at atom-text-editor.TextEditorElement.pixelPositionForScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-element.js:336:29)
    at StableAdapter.computeScrollTop (/Users/lzkelley/.atom/packages/minimap/lib/adapters/stable-adapter.js:54:42)
    at StableAdapter.getScrollTop (/Users/lzkelley/.atom/packages/minimap/lib/adapters/stable-adapter.js:43:36)
    at Minimap.getTextEditorScaledScrollTop (/Users/lzkelley/.atom/packages/minimap/lib/minimap.js:456:25)
    at atom-text-editor-minimap.update (/Users/lzkelley/.atom/packages/minimap/lib/minimap-element.js:779:36)
    at /Users/lzkelley/.atom/packages/minimap/lib/minimap-element.js:751:12
```

### Commands

```
     -0:45.1.0 editor:indent (atom-text-editor.editor.is-focused)
  5x -0:43.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  6x -0:37.5.0 atomic-emacs:backward-char (atom-text-editor.editor.is-focused)
     -0:36.5.0 editor:move-to-beginning-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:36.3.0 core:save (atom-text-editor.editor.is-focused)
  7x -0:32.2.0 atomic-emacs:forward-char (atom-text-editor.editor.is-focused)
     -0:28.4.0 editor:move-to-beginning-of-line (atom-text-editor.editor.is-focused)
  2x -0:28.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:17.1.0 atomic-emacs:forward-char (atom-text-editor.editor.is-focused)
     -0:15.8.0 editor:move-to-beginning-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:15.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.7.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:03.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:02.4.0 editor:move-to-beginning-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:02.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.3.0 editor:fold-at-indent-level-1 (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "language-python",
      "symbols-tree-view",
      "linter-markdown"
    ],
    "ignoredNames": [
      ".*",
      "*~",
      "*.pdf",
      "*.png",
      "*.pyc",
      "*.npz"
    ],
    "openEmptyEditorOnStart": false
  },
  "minimap": {
    "absoluteMode": true,
    "plugins": {
      "cursorline": true,
      "cursorlineDecorationsZIndex": 0
    }
  }
}
```

### Installed Packages

```coffee
# User
atomic-emacs, v0.9.1 (active)
file-watcher, v0.4.0 (active)
language-cython, v0.3.0 (active)
language-restructuredtext, v0.16.0 (active)
linter, v1.11.10 (active)
linter-flake8, v1.13.2 (active)
linter-markdown, v1.5.2 (inactive)
MagicPython, v0.5.11 (active)
markdown-scroll-sync, v2.1.2 (active)
markdown-writer, v2.3.4 (active)
minimap, v4.24.6 (active)
minimap-cursorline, v0.2.0 (active)
pretty-json, v1.4.1 (active)
symbols-tree-view, v0.13.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by lzkelley** [comment]
The same error is also generated in certain situations when scrolling below the end of folded text

**Comment by abe33** [comment]
Hi @lzkelley, thanks for the report, I was off a few days for a musical festival, just catching up with notifications right now, I'll take a look at how I can fix that.
