### ISSUE TITLE
Uncaught TypeError: Cannot read property 'findMarkers' of undefined

### ISSUE THREAD

**Issue by lzkelley** [atom-minimap/minimap#506]
Error is produced when changing tabs, but not consistently.
The same error is produced every time I re-enable the minimap package (see gif).  @abe33

![minimap-err_1](https://cloud.githubusercontent.com/assets/3839265/16363200/19e5aa7e-3b91-11e6-9389-e6dd73ac0b71.gif)

Possibly related to:
https://github.com/atom/atom/issues/5250, https://github.com/atom/atom/issues/4891, https://github.com/atom/atom/issues/8856

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'findMarkers' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/src/decoration-manager.js:151

TypeError: Cannot read property 'findMarkers' of undefined
    at DecorationManager.module.exports.DecorationManager.decorationsStateForScreenRowRange (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/decoration-manager.js:151:21)
    at TextEditor.module.exports.TextEditor.decorationsStateForScreenRowRange (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1537:37)
    at TextEditorPresenter.module.exports.TextEditorPresenter.fetchDecorations (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1377:44)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:123:14)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:265:60)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:205:12)
    at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:304:21)
    at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:1027:16)
    at TextEditorComponent.module.exports.TextEditorComponent.pollDOM (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:1014:17)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61
    at ViewRegistry.module.exports.ViewRegistry.performDocumentPoll (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:265:9)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:228:14)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```

### Commands

```
  2x -3:35.6.0 core:save (atom-text-editor.editor.is-focused)
     -2:32.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:32.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:30.9.0 core:close (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -1:45.2.0 editor:move-to-beginning-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:44.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:36.7.0 editor:move-to-beginning-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:36.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:31.4.0 atomic-emacs:previous-line (atom-text-editor.editor.is-focused)
  9x -1:31.3.0 atomic-emacs:forward-char (atom-text-editor.editor.is-focused)
     -1:24.8.0 editor:move-to-beginning-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:24.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:22.5.0 editor:move-to-beginning-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:22.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:20.2.0 editor:move-to-beginning-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:19.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "audioBeep": false,
    "disabledPackages": [
      "language-python",
      "symbols-tree-view",
      "linter-markdown"
    ],
    "ignoredNames": [
      ".*",
      "*~",
      "*.pdf",
      "*.png",
      "*.pyc",
      "*.npz"
    ],
    "openEmptyEditorOnStart": false
  },
  "editor": {
    "fontSize": 10,
    "invisibles": {},
    "preferredLineLength": 100,
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "softWrapAtPreferredLineLength": true,
    "softWrapHangingIndent": 8,
    "tabLength": 4,
    "tabType": "soft"
  }
}
```

### Installed Packages

```coffee
# User
atomic-emacs, v0.9.2 (active)
bug-report, v0.7.1 (active)
file-watcher, v0.4.0 (active)
language-cython, v0.3.0 (active)
language-restructuredtext, v0.16.0 (active)
linter, v1.11.14 (active)
linter-flake8, v1.13.2 (active)
linter-markdown, v1.5.2 (inactive)
MagicPython, v0.5.11 (active)
markdown-scroll-sync, v2.1.2 (active)
markdown-writer, v2.3.5 (active)
minimap, v4.24.6 (active)
minimap-cursorline, v0.2.0 (active)
pretty-json, v1.4.1 (active)
python-indent, v0.4.3 (active)
symbols-tree-view, v0.13.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (active)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (active)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @lzkelley, I'm not reproducing it on master, and AFAICT it looks like minimap doesn't appear in the stack trace so I'm a bit at loss to find the root cause of the issue.

**Comment by bmatto** [comment]
I'm getting the same error - here is my stack trace

`
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.2
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'findMarkers' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/decoration-manager.js:151

TypeError: Cannot read property 'findMarkers' of undefined
    at DecorationManager.module.exports.DecorationManager.decorationsStateForScreenRowRange (/Applications/Atom.app/Contents/Resources/app.asar/src/decoration-manager.js:151:21)
    at TextEditor.module.exports.TextEditor.decorationsStateForScreenRowRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1540:37)
    at TextEditorPresenter.module.exports.TextEditorPresenter.fetchDecorations (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1377:44)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:123:14)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:265:60)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:205:12)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:233:9)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```

### Commands

```
     -0:55.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:54.5.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:53.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:53.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:52.7.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:52.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:50.5.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:48.9.0 core:cut (atom-text-editor.editor.is-focused)
     -0:47.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:37.7.0 tree-view:remove (span.name.icon.icon-file-text)
     -0:29.2.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:20.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:20 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:18.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:10.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.4.0 pane:split-right-and-copy-active-item (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "activate-power-mode",
      "atom-wallaby"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 13,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0 (inactive)
atom-material-ui, v1.3.3 (active)
atom-wallaby, v1.0.9 (inactive)
emmet, v2.4.3 (active)
file-type-icons, v1.3.2 (active)
git-plus, v5.16.2 (inactive)
git-time-machine, v1.5.3 (inactive)
language-babel, v2.32.1 (active)
language-elixir, v0.15.0 (active)
linter, v1.11.14 (active)
linter-eslint, v7.2.4 (active)
pretty-json, v1.4.4 (active)
rails-open-rspec, v1.0.0 (inactive)
ruby-slim, v0.2.0 (active)
terminal-plus, v0.14.5 (active)
toggle-quotes, v1.0.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```


`
