### ISSUE TITLE
Uncaught TypeError: this.getTextEditor(...).tokenizedLinesForScreenRows is not a function

### ISSUE THREAD

**Issue by wshudong** [atom-minimap/minimap#509]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.3
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.24.6

### Stack Trace

Uncaught TypeError: this.getTextEditor(...).tokenizedLinesForScreenRows is not a function

```
At /Users/wangshudong/.atom/packages/minimap/lib/mixins/canvas-drawer.js:408

TypeError: this.getTextEditor(...).tokenizedLinesForScreenRows is not a function
    at atom-text-editor-minimap.drawLines (/Users/wangshudong/.atom/packages/minimap/lib/mixins/canvas-drawer.js:408:40)
    at atom-text-editor-minimap.redrawRangesOnLayer (/Users/wangshudong/.atom/packages/minimap/lib/mixins/canvas-drawer.js:183:14)
    at atom-text-editor-minimap.updateTokensLayer (/Users/wangshudong/.atom/packages/minimap/lib/mixins/canvas-drawer.js:135:10)
    at atom-text-editor-minimap.updateCanvas (/Users/wangshudong/.atom/packages/minimap/lib/mixins/canvas-drawer.js:103:10)
    at atom-text-editor-minimap.update (/Users/wangshudong/.atom/packages/minimap/lib/minimap-element.js:814:10)
    at /Users/wangshudong/.atom/packages/minimap/lib/minimap-element.js:717:12
```

### Commands

```
     -7:33.3.0 application:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -7:21.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-atom-material-syntax-dark.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angular2-snippets, v0.3.0 (active)
angularjs-snippets, v0.10.18 (active)
angularjs-styleguide-snippets, v0.7.3 (active)
atom-beautify, v0.29.9 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (active)
atom-material-ui, v1.2.13 (active)
atom-ng-attr-hint, v2.1.0 (inactive)
autocomplete-angular-material, v0.4.0 (active)
autocomplete-emojis, v2.5.0 (active)
autocomplete-php, v0.3.7 (active)
drunken-php, v0.2.1 (active)
file-icons, v1.7.15 (active)
minimap, v4.24.6 (active)
php-fmt, v0.1.2 (inactive)
pigments, v0.29.3 (active)
react-snippets, v0.4.2 (active)
vim-mode, v0.65.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @wshudong, it looks like another issue with post update package reload, reloading/restarting atom should be enough to fix this issue.

**Comment by panox** [comment]
I had this bug too. However, I checked and a lot of my packages needed an update. After that is seems to have gone away.

**Comment by gphummer** [comment]
Likewise. Needed to update the minimap package and the bug disappeared.

**Comment by rl-dmay** [comment]
updating to 4.24.7 fixed this.

**Comment by ummahusla** [comment]
I had the same error today, updating the package fixed the issue.
