### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by candrsn** [atom-minimap/minimap#513]
[Enter steps to reproduce below:]

1.  open Atom - error appears

**Atom Version**: 0.175.0
**System**: linux 4.6.4-301.fc24.x86_64
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.7.6

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/candrsn/.atom/packages/minimap/lib/minimap-element.coffee:79

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.attachedCallback (/home/candrsn/.atom/packages/minimap/lib/minimap-element.coffee:79:35)
  at atom-pane.PaneElement.activeItemChanged (/usr/local/share/atom/resources/app/src/pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/local/share/atom/resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (/usr/local/share/atom/resources/app/src/pane.js:328:21)
  at /usr/local/share/atom/resources/app/src/workspace.js:524:16
  at _fulfilled (/usr/local/share/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/usr/local/share/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/usr/local/share/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:749:13)
  at /usr/local/share/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:557:44
  at flush (/usr/local/share/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:386:11)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-jedi",
      "autocomplete-css",
      "npm-autocomplete",
      "autocomplete-plus-python-jedi"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atomatigit, v1.5.5
closure-linter, v0.2.5
compass, v0.9.1
git-go, v1.0.1
git-log, v0.4.1
git-tab-status, v1.7.0
linter, v1.11.16
linter-csslint, v1.3.2
linter-gjslint, v1.5.0
linter-jshint, v2.1.0
linter-package-json-validator, v1.0.1
linter-pylint, v0.2.2
linter-python-pyflakes, v0.1.0
linter-tidy, v1.0.1
minimap, v4.7.6
minimap-selection, v4.4.0
open-last-project, v0.4.2
pretty-json, v1.6.0
project-manager, v1.15.5
project-ring, v0.19.6
project-view, v0.5.0
python, v0.5.1
python-coverage, v0.2.0
python-jedi, v0.3.7
recent-projects, v0.3.0
tualo-git-context, v0.3.0
vim-mode, v0.62.0
virtualenv, v0.6.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Wow, that's some seriously old Atom version you're running here. We no longer maintain minimap for pre-1.0 versions so I would suggest you update Atom to a more recent version.
