### ISSUE TITLE
Uncaught Error: Position (N, Infinity) 

### ISSUE THREAD

**Issue by abe33** [atom-minimap/minimap#522]
Not sure about the steps, I just scrolled all the way down a file with `scroll past end` enabled
### Stack Trace

<details>
Uncaught Error: Position (2208.1409200968524, Infinity) is less than the current token's start ((2209, 0))

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/display-index/dist/token-iterator.js:251

Error: Position (2208.1409200968524, Infinity) is less than the current token's start ((2209, 0))
    at TokenIterator.translateScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/display-index/dist/token-iterator.js:251:15)
    at DisplayLayer.module.exports.DisplayLayer.translateScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1491:52)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateToBufferMarkerLayerFindParams (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:220:46)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.findMarkers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:133:21)
    at DecorationManager.module.exports.DecorationManager.decorationsStateForScreenRowRange (/Applications/Atom.app/Contents/Resources/app.asar/src/decoration-manager.js:151:21)
    at TextEditor.module.exports.TextEditor.decorationsStateForScreenRowRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1711:37)
    at TextEditorPresenter.module.exports.TextEditorPresenter.fetchDecorations (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1380:44)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:125:14)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:259:60)
    at TextEditorComponent.module.exports.TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:623:14)
    at atom-text-editor.TextEditorElement.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:288:29)
    at StableAdapter.computeScrollTop (/Users/cedric/.atom/packages/minimap/lib/adapters/stable-adapter.js:60:42)
    at StableAdapter.getScrollTop (/Users/cedric/.atom/packages/minimap/lib/adapters/stable-adapter.js:51:17)
    at Minimap.getTextEditorScrollRatio (/Users/cedric/.atom/packages/minimap/lib/minimap.js:530:25)
    at Minimap.getCapedTextEditorScrollRatio (/Users/cedric/.atom/packages/minimap/lib/minimap.js:542:29)
    at Minimap.getScrollTopFromEditor (/Users/cedric/.atom/packages/minimap/lib/minimap.js:865:12)
    at Minimap.updateScrollTop (/Users/cedric/.atom/packages/minimap/lib/minimap.js:853:30)
    at /Users/cedric/.atom/packages/minimap/lib/minimap.js:219:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:95:46
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:931:29)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateScrollHeight (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:853:21)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateVerticalDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:866:21)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:115:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:259:60)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:191:12)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:318:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:231:9)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:59
```

</details>
### Commands

<details>

```
     -5:26.1.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -5:19.8.0 find-and-replace:show (input.hidden-input)
     -5:15.1.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -5:14.7.0 editor:consolidate-selections (input.hidden-input)
     -5:14.7.0 core:cancel (input.hidden-input)
     -5:12.5.0 window:run-package-specs (input.hidden-input)
     -0:03.0 window:toggle-dev-tools (input.hidden-input)
```

</details>
### Config

<details>

``` json
{
  "core": {
    "audioBeep": false,
    "customFileTypes": {
      "source.ruby.rails": [
        "rb"
      ]
    },
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "minimap-symbols",
      "preview-tabs",
      "crosshairs",
      "coffee-compile",
      "enhanced-package-list",
      "themed-settings",
      "smart-tag-cycle",
      "tree-view-open-files",
      "typewriter",
      "travis-ci-status"
    ],
    "openEmptyEditorOnStart": false,
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "spacegray-dark-neue-syntax"
    ],
    "useCustomTitleBar": true
  },
  "minimap": {
    "charHeight": 1,
    "independentMinimapScroll": true,
    "moveCursorOnMinimapClick": true,
    "plugins": {
      "bookmarks": true,
      "bookmarksDecorationsZIndex": 0,
      "codeglance": false,
      "codeglanceDecorationsZIndex": 0,
      "color-highlight": true,
      "find-and-replace": true,
      "find-and-replaceDecorationsZIndex": 0,
      "git-diff": true,
      "git-diffDecorationsZIndex": 0,
      "highlight-selected": true,
      "highlight-selectedDecorationsZIndex": 0,
      "linter": true,
      "linterDecorationsZIndex": 0,
      "pigments": true,
      "pigmentsDecorationsZIndex": 0,
      "selection": true,
      "selectionDecorationsZIndex": 0
    },
    "scrollAnimation": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-eco, v0.2.0 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-ternjs, v0.15.0 (active)
bezier-curve-editor, v0.7.2 (active)
caniuse, v0.9.0 (active)
clipboard-plus, v0.5.1 (active)
docblockr, v0.8.7 (active)
duotone-dark-forest-syntax, v1.0.0 (inactive)
duotone-dark-space-syntax, v1.0.0 (inactive)
expose, v0.12.1 (inactive)
figlet, v0.5.4 (active)
highlight-selected, v0.11.2 (active)
indent-tooltip, v0.2.1 (inactive)
language-generic-config, v1.2.0 (active)
language-haml, v0.24.0 (active)
language-jade, v0.7.2 (active)
language-sass, v0.57.0 (active)
linter, v1.11.18 (active)
linter-js-standard, v3.4.1 (active)
minimap, v4.26.1 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-codeglance, v0.4.5 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.6.0 (active)
minimap-pigments, v0.2.1 (active)
minimap-selection, v4.4.0 (active)
php-twig, v4.0.0 (active)
pigments, v0.38.0 (active)
process-palette, v0.9.1 (active)
project-palette-finder, v2.4.17 (active)
red-wavy-underline, v0.3.1 (active)
solarized-dark-ui, v0.3.1 (inactive)
sort-lines, v0.14.0 (inactive)
spacegray-dark-neue-syntax, v1.3.0 (active)
spacegray-dark-neue-ui, v1.6.0 (inactive)
spacegray-dark-syntax, v0.2.0 (inactive)
spacegray-dark-ui, v0.12.0 (inactive)
Stylus, v3.1.0 (active)
tablr, v1.5.5 (active)
tabs-to-spaces, v1.0.2 (active)
toggle-quotes, v1.0.0 (inactive)
travis-ci-status, v1.3.0 (inactive)
tree-view-breadcrumb, v0.8.1 (active)
tree-view-open-files, v0.3.0 (inactive)
typewriter, v0.3.5 (inactive)
unfancy-file-icons, v0.10.0 (active)
white-cursor, v0.6.0 (active)
Zen, v0.16.4 (inactive)
zentabs, v0.8.7 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.7.0 (active)
one-light-ui, v1.7.0 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.1 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.203.0 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.3 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.47.3 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

</details>

**Comment by abe33** [comment]
Was  not able to reproduce
