### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shabum** [atom-minimap/minimap#526]
Error: Cannot find module 'mixto'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\dns\.atom\packages\minimap\lib\mixins\plugin-management.js:19:14)
    at Module._compile (C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:/Users/dns/.atom/packages/minimap/lib/main.js:16:43)
    at Module._compile (C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:721:27)
    at Package.module.exports.Package.activateNow (C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:173:16)
    at C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:92:15)
    at C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\dns\AppData\Local\atom\app-1.11.2\resources\app.asar\src\atom-environment.js:779:28

**Comment by abe33** [comment]
Hi, in which circumstances did you get this error?

**Comment by shabum** [comment]
Hi @abe33, I get this error when starting the application(Atom)

**Comment by fundon** [comment]
Could `Reinstall` fix that?

**Comment by shabum** [comment]
I reinstalled the Atom and the error was gone.
