### ISSUE TITLE
Error: Can't create a view for Minimap instance. Please register a view provider

### ISSUE THREAD

**Issue by VincentTofterup** [atom-minimap/minimap#530]
Error: Can't create a view for Minimap instance. Please register a view provider.
    at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app.asar/src/view-registry.js:133:13)
    at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app.asar/src/view-registry.js:86:21)
    at /home/vincenttofterup/.atom/packages/minimap/lib/main.js:386:39
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:290:9)
    at Main.initSubscriptions (/home/vincenttofterup/.atom/packages/minimap/lib/main.js:384:43)
    at Main.toggle (/home/vincenttofterup/.atom/packages/minimap/lib/main.js:180:12)
    at Main.activate (/home/vincenttofterup/.atom/packages/minimap/lib/main.js:111:55)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:181:20)
    at /usr/share/atom/resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:526:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)

**Comment by fundon** [comment]
Which version of minimap do you use?

**Comment by fundon** [comment]
Which version of minimap do you use?

**Comment by VincentTofterup** [comment]
It's alright now, reinstalled atom and minimap, it's working again.

Thanks for the interest in my problem. I think the problem was the version of Atom.

Regards
Vincent

Den 31. okt. 2016 kl. 17.01 skrev Fangdun Cai <notifications@github.com<mailto:notifications@github.com>>:


Which version of minimap do you use?

**Comment by abe33** [comment]
@VincentTofterup Great to hear that it works again for you, closing the issue then.
