### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by idleberg** [atom-minimap/minimap#568]
The following error occured several times after re-open Atom with a previous project and then (excessively?) making use of the undo feature.

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.3
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.26.7

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Users/jan/.atom/packages/minimap/lib/mixins/decoration-management.js:431

RangeError: Maximum call stack size exceeded
    at CallSiteToString [as toString] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/source-map-support/source-map-support.js:219:12)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/source-map-support/source-map-support.js:338:24
    at Array.map (native)
    at prepareStackTrace (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/source-map-support/source-map-support.js:337:24)
    at Function.prepareStackTraceWithRawStackAssignment (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:182:12)
    at Error.get stack [as stack] (native)
    at Minimap.getOriginatorPackageName (/Users/jan/.atom/packages/minimap/lib/mixins/decoration-management.js:431:29)
    at Minimap.decorateMarker (/Users/jan/.atom/packages/minimap/lib/mixins/decoration-management.js:338:38)
    at MinimapCursorLineBinding.handleMarker (/Users/jan/.atom/packages/minimap-cursorline/lib/minimap-cursorline-binding.js:21:37)
    at /Users/jan/.atom/packages/minimap-cursorline/lib/minimap-cursorline-binding.js:15:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.addCursor (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2088:20)
    at TextEditor.module.exports.TextEditor.addSelection (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2569:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:64:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at MarkerLayer.module.exports.MarkerLayer.createMarker (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:392:22)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:196:19)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:90:62)
    at TextEditor.module.exports.TextEditor.addSelectionForBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2254:34)
    at TextEditor.module.exports.TextEditor.createLastSelectionIfNeeded (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2631:21)
    at TextEditor.module.exports.TextEditor.getLastSelection (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2427:12)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:73:24)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:59
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.addCursor (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2088:20)
    at TextEditor.module.exports.TextEditor.addSelection (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2569:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:64:18
```

### Commands

```
 20x -0:14.9.0 core:undo (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "file-icons",
      "nsis-plugins",
      "build-custom",
      "nsis-ide",
      "wrap-guide",
      "minimap-linter"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "hopscotch"
    ]
  },
  "minimap": {
    "plugins": {
      "codeglance": true,
      "codeglanceDecorationsZIndex": 0,
      "cursorline": true,
      "cursorlineDecorationsZIndex": 0,
      "linter": true,
      "linterDecorationsZIndex": 0,
      "selection": true,
      "selectionDecorationsZIndex": 0
    }
  }
}
```

### Installed Packages

```coffee
# User
anderson-dark-syntax, v0.1.0 (inactive)
atomizr, v0.23.0 (inactive)
browse, v1.3.5 (inactive)
build, v0.67.0 (active)
build-bridlensis, v0.8.3 (active)
build-custom, v0.0.0 (inactive)
build-dart-sass, v0.1.2 (active)
build-makensis, v0.16.2 (active)
build-makensis-wine, v0.15.2 (active)
build-nsl, v0.10.4 (active)
build-tsc, v0.5.3 (active)
build-webpack, v0.6.2 (active)
busy, v0.7.0 (active)
colorful-json, v1.1.0 (active)
console-panel, v0.2.1 (active)
custom-one-dark-ui, v1.9.0 (inactive)
drag-relative-path, v1.0.3 (active)
edit-in-new-tab, v0.6.2 (inactive)
haskell-nsis, v0.3.3 (active)
hopscotch, v2.0.2 (active)
language-batch, v0.3.3 (active)
language-bridlensis, v3.3.6 (active)
language-dots, v0.0.4 (active)
language-ini, v1.17.0 (active)
language-javascript-jsx, v0.3.7 (active)
language-nsis, v5.15.0 (active)
language-nsl, v2.11.7 (active)
language-powershell, v4.0.0 (active)
language-typescript-grammars-only, v1.6.0 (active)
linter, v1.11.21 (active)
local-storage, v0.3.3 (inactive)
logo-file-icons, v1.8.0 (active)
m8tro-ui, v0.0.0 (inactive)
minimap, v4.26.7 (active)
minimap-codeglance, v0.4.5 (active)
minimap-cursorline, v0.2.0 (active)
minimap-linter, v1.6.0 (inactive)
minimap-selection, v4.4.0 (active)
multi-cursor, v2.1.5 (inactive)
nsis-dark-syntax, v0.0.0 (inactive)
nsis-ide, v0.11.1 (inactive)
nsis-plugins, v2.0.2 (inactive)
open-in-developer-mode, v0.1.1 (inactive)
open-package, v0.2.0 (inactive)
package-developer-toolbar, v0.9.1 (active)
package-settings, v1.1.0 (active)
pigments, v0.39.0 (active)
pretty-json, v1.6.1 (active)
set-syntax, v0.3.2 (active)
tabs-to-spaces, v1.0.3 (active)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by DFelten** [comment]
Samer error here with lage files (150k lines) in 1.15.0-beta0.

**Comment by abe33** [comment]
Do you have some reproduction steps to provide? I never encountered this error.

**Comment by DFelten** [comment]
I just opened a really large TXT file and this error appears. It's about 14 Mb large with 150.000 lines. Unfortunately, I can not attach the file here.

**Comment by tobiasboyd** [comment]
I have the same error opening an 85,000 line sitemap.xml file in 1.15-beta1  - not only does the minimap fail to load, but the editor itself only loads the first 66 lines.

**Comment by espton** [comment]
Same here. 65 000 lines of inserts in a sql-file. Freshly opened. Minimap ver 4.26.8, Atom ver. 1.14.1 x60 on Mac.
