### ISSUE TITLE
Error: env: node: No such file or directory

### ISSUE THREAD

**Issue by BluePawDev** [atom-minimap/minimap#570]
Started receiving the following error with respect to [AtomLinter](https://github.com/AtomLinter), [linter-bootlint](https://github.com/AtomLinter/linter-bootlint) after the following steps:

1. Via GitHub desktop '_Open in Atom_' existing repo (_sandbox-html_)
2. **Created** new file (_cmd + N_)
3. **Saved** new file (_cmd + S_) as _index.html_

Only known changes to system configuration was update of [atom-minimap](https://github.com/atom-minimap) ([minimap v4.26.8](https://github.com/atom-minimap/minimap))
[Submitted issue](https://github.com/AtomLinter/linter-bootlint/issues/96) on AtomLinter as well.

```
Error: env: node: No such file or directory
    at ChildProcess.<anonymous> (/Users/Jason/.atom/packages/linter-bootlint/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

**Comment by BluePawDev** [comment]
Issue appears to have resolved after following steps
Still interested in any thoughts on cause--thank you!

1. Reinstalled [tidy-HTML5](http://www.html-tidy.org/) via [Homebrew](https://github.com/Homebrew):
    - `brew install tidy-html5`
3. Quit [GitHub Desktop](https://desktop.github.com/)
4. Quit [Atom](https://atom.io/)
5. Restarted MacBook
