### ISSUE TITLE
Failed to activate the minimap package

### ISSUE THREAD

**Issue by anshumanf** [atom-minimap/minimap#572]
[Enter steps to reproduce:]

1. Uninstall 32-bit Atom beta on Windows and install 64-bit beta
2. Start Atom

**Atom**: 1.15.0-beta1 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.26.8

### Stack Trace

Failed to activate the minimap package

```
At Cannot find module 'mixto'

Error: Cannot find module 'mixto'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0-beta1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/minimap/lib/mixins/plugin-management.js:3:15)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/minimap/lib/main.js:17:26)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
```

### Commands

```
 11x -3:58.3.0 blur (div.settings-view.pane-item)
```

### Non-Core Packages

```
2-dark-syntax 1.1.0 
accents-ui 1.2.0 
atom-alignment 0.12.1 
atom-beautify 0.29.17 
atom-css-comb 3.1.0 
atom-import-sort undefined 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.9 
atom-monokai 0.10.7 
atom-ternjs 0.17.0 
autoclose-html 0.23.0 
autocomplete-emojis 2.5.0 
cake-syntax 1.0.2 
cold-ui 1.4.0 
dark-flat-ui 1.2.4 
duotone-dark-syntax 2.1.0 
eclectic-syntax 0.2.1 
elm-format 2.1.0 
firewatch-syntax 1.1.1 
flat-ui-syntax 0.5.1 
git-time-machine 1.5.4 
gruvbox-syntax 2.4.1 
highlight-selected 0.12.0 
ide-flow 0.8.0 
language-babel undefined 
language-elm 1.5.0 
line-ending-selector-unix 0.0.9 
linter 1.11.21 
linter-elm-make 0.22.2 
linter-eslint 8.1.0 
linter-flake8 2.1.4 
linter-flow 5.5.0 
min-ui 0.0.1 
minimap 4.26.8 
minimap-highlight-selected 4.5.0 
northem-dark-atom-ui 2.0.0 
nucleus-dark-ui 0.10.22 
outlander-syntax 2.0.0 
pigments 0.39.0 
react 0.16.0 
react-es6-snippets 0.3.0 
sensible-tab 1.0.0 
seti-ui 1.6.1 
sort-lines 0.14.0 
Sublime-Style-Column-Selection 1.7.3 
tab-switcher 1.5.4 
tabs-to-spaces 1.0.3 
tango-syntax 0.4.1 
todo-show 1.9.0 
trailing-spaces 0.4.0 
```

**Comment by jradarp** [comment]
I'm a complete beginner, attempting to learn Atom

**Comment by Pizdetss** [comment]
I'm getting the same issue on Windows 8 64bit

**Comment by abe33** [comment]
It looks like some issue with dependencies install, try deleting the `node_modules` directory in the package (should be in your home in a `.atom/packages/minimap` directory) and then run `apm install` in that directory.

**Comment by Pizdetss** [comment]
No idea what this is, after running apm install in directory:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.4.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.3.13/iojs-v1.3.13.tar.gz
gyp http 200 https://atom.io/download/electron/v1.3.13/iojs-v1.3.13.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._handle.onerror (zlib.js:363:17)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Users\\vaniki\\AppData\\Local\\atom\\app-1.14.3\\resources
\\app\\apm\\bin\\node.exe" "C:\\Users\\vaniki\\AppData\\Local\\atom\\app-1.14.3\
\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--run
time=electron" "--target=1.3.13" "--dist-url=https://atom.io/download/electron"
"--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\vaniki\.atom
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

**Comment by Pizdetss** [comment]
@anshumanf turn ssl-strict to true and try again.

**Comment by stratigos** [comment]
Noting here that I received a similar issue with `minimap` this morning, but a different stack trace (below).

I keep my `.atom` dir on DropBox, and mount that dir to several different machines I work on. I install packages from varying machines, but I guess `minimap` doesn't take well to this pattern. Running `apm install` throws some errors. Running `apm install minimap` on the machine reporting the issue seems to have fixed it.

Here is my stack trace from the `minimap` error:

```
ReferenceError: Invalid left-hand side in assignment
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:77:42)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:173:16)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```

Here is the error when I just run `apm install` on the same machine:

```
npm ERR! install Couldn't read dependencies
npm ERR! Linux 3.13.0-57-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/USER/.atom/.apm/.apmrc" "--userconfig" "/home/USER/.atom/.apmrc" "install" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! path /home/USER/Dropbox/.atom/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! package.json ENOENT, open '/home/USER/Dropbox/.atom/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/USER/Dropbox/.atom/npm-debug.log
```

I thought this might have something to do with the node version above (v0.10.40 - super out of date), and then realized this is also discussed in [this github issue](https://github.com/atom/apm/issues/328) (and also [here](https://discuss.atom.io/t/apm-using-ancient-versions-of-node-npm-and-i-cant-seem-to-fix-it/26400/9)). I cant seem to get the nodeJS version with apm to update (and am not sure if its even related to the above problem).  The debug log is complaining about not finding a `package.json`, but to my knowledge I've never had one for atom, and Ive never had this problem before today. 

Either way, it atom doesnt seem to like it when I am reading it from a mounted dir like DropBox. It isnt causing me problems right now, but I have a bad feeling about that above error message for the future. Anyone know why that last error (when I do `apm install`) appears, and how I can get it to work correctly?

**Comment by furrutton** [comment]
An easier way to solve this issue, I believe, shuld be the npm methodology which is easy to be installed and executed.
Try `npm install ` **the module you need**

**Comment by KnoveZ** [comment]
uninstall minimap and restart atom.and install minimap   -> ok

**Comment by xtgoxa** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.29.9


### Stack Trace

Failed to activate the minimap package

```
At Cannot find module 'mixto'

Error: Cannot find module 'mixto'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:146745)
    at /packages/minimap/lib/mixins/plugin-management.js:3:15)
    at /packages/minimap/lib/mixins/plugin-management.js:293:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:146745)
    at /packages/minimap/lib/main.js:17:26)
    at /packages/minimap/lib/main.js:408:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:1:721712)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3338526)
    at Package.activateNow (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3326510)
    at measure (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3326288)
    at Package.measure (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3323898)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3326148)
    at new Promise (<anonymous>)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.33.4 
atom-js 1.2.0 
atom-material-syntax undefined 
atom-material-ui undefined 
simplified-chinese-menu 5.3.5 
atom-terminal-panel 4.4.4 
file-icons undefined 
minimap 4.29.9 
```
