### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTextEditor' of undefined

### ISSUE THREAD

**Issue by tomopro** [atom-minimap/minimap#574]
[Enter steps to reproduce:]

1. Open the tab menu
2. It occurs when you switch the order of the files in the tab menu.

**Atom**: 1.14.3 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.26.8

### Stack Trace

Uncaught TypeError: Cannot read property 'getTextEditor' of undefined

```
At C:\Users\Username\.atom\packages\minimap\lib\minimap-element.js:630

TypeError: Cannot read property 'getTextEditor' of undefined
    at /packages/minimap/lib/minimap-element.js:630:41)
    at /packages/minimap/lib/minimap-element.js:640:50)
    at /packages/minimap/lib/minimap-element.js:349:58)
    at /packages/minimap/node_modules/atom-utils/lib/register-or-update-element.js:15:57)
    at Sortable._onDragStart (/packages/expose/node_modules/sortablejs/Sortable.js:638:12)
```

### Commands

```
     -0:52.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.theme-one-dark-syntax.theme-atom-material-ui)
     -0:26.2.0 expose:toggle (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.2.0 
advanced-open-file 0.16.5 
atom-beautify 0.29.17 
atom-bootstrap3 1.2.12 
atom-clock 0.1.4 
atom-fontawesome 0.4.0 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-minify 0.8.0 
autoclose-html 0.23.0 
autocomplete-angular-material 0.4.0 
autocomplete-emojis 2.5.0 
autocomplete-paths 1.0.5 
autocomplete-sass 0.1.0 
bootstrap-3-snippetset 0.0.6 
color-picker 2.2.5 
convert-to-utf8 0.2.4 
editorconfig 2.2.1 
emmet 2.4.3 
expose 0.14.0 
file-icons 2.0.15 
hey-pane 0.1.0 
highlight-selected 0.12.0 
imdone-atom 2.1.18 
imdone-atom-github 0.1.11 
japanese-menu 1.9.0 
jquery-snippets 11.0.0 
jumpy 3.1.3 
Language-Skript 2.1.3 
linter 1.11.23 
linter-csslint 1.3.3 
linter-htmlhint 1.3.1 
linter-jshint 3.0.2 
linter-markdown 3.1.0 
linter-php 1.3.1 
linter-write-good 0.8.0 
local-history 4.0.1 
markdown-pdf 1.5.0 
markdown-scroll-sync 2.1.2 
markdown-writer 2.6.4 
maximize-panes 0.2.0 
mdl-snippets 0.3.0 
minimap 4.26.8 
minimap-autohide 0.10.1 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
minimap-pigments 0.2.2 
minimap-split-diff 0.3.5 
monokai 0.22.0 
open-in-browsers 0.0.19 
outline-selection 0.3.1 
pigments 0.39.0 
project-manager 3.3.3 
Remote-FTP 0.10.5 
show-ideographic-space 1.0.2 
split-diff 1.1.4 
Sublime-Style-Column-Selection 1.7.3 
tablr 1.8.1 
tabs-to-spaces 1.0.3 
tag 0.4.0 
web-search 0.3.3 
zentabs 0.8.8 
```

**Comment by tomopro** [comment]
Additional notes
If you move the setting tab, no error will occur.

**Comment by akapa100** [comment]
I have the same error

**Comment by Jackymancs4** [comment]
Why this issue has been closed?
@abe33 Can you please provide some insight on your decision, since with minimap v4.29.7 the error still occurs.
Maybe, just leaving this open for future analysis.

**Comment by aenhsaihan** [comment]
I'm also getting the same error. I'm thinking about disabling the minimap package just to get this working.
