### ISSUE TITLE
error

### ISSUE THREAD

**Issue by IPIBA** [atom-minimap/minimap#587]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.27.1

### Stack Trace

Failed to activate the minimap package

```
At Invalid left-hand side in assignment

ReferenceError: Invalid left-hand side in assignment
    at Module._compile (C:\Users\IPIBA EIRL\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:77:42)
    at Object.defineProperty.value [as .js] (C:\Users\IPIBA EIRL\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\IPIBA EIRL\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\IPIBA EIRL\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateNow (C:\Users\IPIBA EIRL\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:173:16)
    at C:\Users\IPIBA EIRL\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\IPIBA EIRL\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\IPIBA EIRL\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\IPIBA EIRL\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\IPIBA EIRL\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\IPIBA EIRL\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\IPIBA EIRL\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\IPIBA EIRL\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\IPIBA EIRL\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\IPIBA EIRL\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false
  },
  "minimap": {}
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
autocompiler-pug-jade, v2.0.1
busy-signal, v1.3.0
color-picker, v2.2.5
compiler-invoker, v1.1.0
emmet, v2.4.3
emmet-simplified, v2.5.0
file-icons, v1.7.25
gpp-compiler, v3.0.7
intentions, v1.1.2
jade-autocompile, v0.8.5
jshint, v1.8.6
linter, v1.11.18
linter-eslint, v7.3.2
linter-htmlhint, v1.3.3
linter-jshint, v3.0.3
linter-ui-default, v1.2.2
minimap, v4.26.8
pp, v0.0.1
pretty-json, v1.6.3
preview-plus, v1.2.7
seti-icons, v1.4.3
snippets-jade, v0.2.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by mehcode** [comment]
@IPIBA Do you still get this with the latest Minimap version?

**Comment by aminya** [comment]
This issue does not seem to be related to minimap
