### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined

### ISSUE THREAD

**Issue by bmwilly** [atom-minimap/minimap#590]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.28.1

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined

```
At /Users/brandon/.atom/packages/minimap/lib/kite-wrapper.js:117

TypeError: Cannot read property 'onDidStopChanging' of undefined
    at /packages/minimap/lib/kite-wrapper.js:117:43)
    at /packages/minimap/node_modules/atom-utils/lib/register-or-update-element.js:15:57)
    at /app.asar/src/pane-container-element.js:42:14)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.setRoot (/app.asar/src/pane-container.js:163:20)
    at PaneContainer.module.exports.PaneContainer.replaceChild (/app.asar/src/pane-container.js:173:19)
    at Pane.module.exports.Pane.split (/app.asar/src/pane.js:919:21)
    at Pane.module.exports.Pane.splitRight (/app.asar/src/pane.js:899:19)
    at /app.asar/src/register-default-commands.js:258:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -4:15.7.0 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -4:12.4.0 core:backspace (input.hidden-input)
     -4:10.7.0 core:confirm (input.hidden-input)
     -2:31.9.0 find-and-replace:show (input.hidden-input)
     -2:30.3.0 core:confirm (input.hidden-input)
  2x -0:08.2.0 pane:split-right-and-copy-active-item (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.1 
character-count 1.0.3 
intentions 1.1.2 
keybinding-cheatsheet 0.1.1 
language-csv 1.1.2 
language-ini 1.19.0 
language-julia 0.11.0 
language-latex 1.0.0 
language-markdown 0.21.0 
language-ocaml 1.8.0 
language-proto 0.8.0 
language-protobuf 0.7.1 
language-r 0.4.1 
latex 0.43.0 
latex-completions 0.3.2 
latextools 0.8.5 
linter 2.1.4 
linter-flake8 2.2.1 
linter-lintr 1.1.4 
linter-markdown 4.0.0 
linter-pycodestyle 2.0.2 
linter-python-pep257 0.0.1 
linter-ui-default 1.2.3 
markdown-table-formatter-z 2.9.2 
minimap 4.28.1 
multi-cursor 2.1.5 
ocaml-indent 0.6.0 
ocaml-merlin 0.14.3 
pdf-view 0.57.0 
python-autopep8 0.1.3 
python-debugger 0.2.0 
python-indent 1.0.2 
python-tools 0.6.9 
r-exec 0.5.0 
Repl 0.5.0 
tablr 1.8.3 
tabs-to-spaces 1.0.3 
tool-bar 1.1.0 
tree-view-autoresize 1.6.0 
tree-view-big-files 0.4.1 
wraptor 0.2.1 
```

**Comment by zhutmost** [comment]
I tried to locate this issue and I found that when pdf-view is installed, opening a pdf file and putting it on the side will cause this error. 
"pdf-view" is always used by "latex" package to pre-view the output.
