### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined

### ISSUE THREAD

**Issue by marcelhekking** [atom-minimap/minimap#592]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.28.1

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined

```
At /home/marcelhekking/Dropbox/Atom/packages/minimap/lib/kite-wrapper.js:117

TypeError: Cannot read property 'onDidStopChanging' of undefined
    at /packages/minimap/lib/kite-wrapper.js:117:43)
    at /packages/minimap/node_modules/atom-utils/lib/register-or-update-element.js:15:57)
    at /app.asar/src/pane-container-element.js:42:14)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.setRoot (/app.asar/src/pane-container.js:163:20)
    at PaneContainer.module.exports.PaneContainer.replaceChild (/app.asar/src/pane-container.js:173:19)
    at PaneAxis.module.exports.PaneAxis.reparentLastChild (/app.asar/src/pane-axis.js:223:19)
    at PaneAxis.module.exports.PaneAxis.removeChild (/app.asar/src/pane-axis.js:188:21)
    at /app.asar/src/pane-axis.js:231:24
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.destroyed (/app.asar/src/pane.js:875:20)
    at Pane.module.exports.Model.destroy (/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroy (/app.asar/src/pane.js:866:39)
    at Pane.module.exports.Pane.removeItem (/app.asar/src/pane.js:605:21)
    at Pane.module.exports.Pane.destroyItem (/app.asar/src/pane.js:658:16)
    at Pane.module.exports.Pane.destroyActiveItem (/app.asar/src/pane.js:638:12)
    at Workspace.destroyActivePaneItem (/app.asar/src/workspace.js:868:33)
    at Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/app.asar/src/workspace.js:929:12)
    at /app.asar/src/register-default-commands.js:222:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:04.7.0 command-palette:toggle (input.hidden-input)
  4x -1:02.0 core:backspace (input.hidden-input)
     -0:56.6.0 core:confirm (input.hidden-input)
     -0:56.6.0 python-isort:sortImports (input.hidden-input)
     -0:53 autocomplete-plus:cancel (input.hidden-input)
     -0:52.3.0 intentions:highlight (input.hidden-input)
     -0:51.6.0 core:undo (input.hidden-input)
     -0:50.1.0 intentions:highlight (input.hidden-input)
     -0:49.8.0 command-palette:toggle (input.hidden-input)
     -0:46.5.0 core:confirm (input.hidden-input)
     -0:46.5.0 python-isort:sortImports (input.hidden-input)
     -0:30.8.0 markdown-preview:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:28.4.0 editor:consolidate-selections (input.hidden-input)
     -0:28.4.0 core:cancel (input.hidden-input)
     -0:22.4.0 intentions:highlight (input.hidden-input)
  2x -0:21.2.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.8.63 
blame 0.10.3 
busy-signal 1.4.1 
django-templates 0.5.0 
expand-selection-to-quotes 0.11.0 
file-icons 2.1.4 
git-blame 1.0.1 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
hyperclick 0.0.40 
indent-guide-improved 1.4.12 
indentation-jumper 0.1.2 
intentions 1.1.2 
linter 2.1.4 
linter-annotations 1.0.1 
linter-flake8 2.2.1 
linter-htmlhint 1.3.3 
linter-ui-default 1.2.3 
local-history 4.0.1 
lorem 1.2.1 
minimap 4.28.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
monokai 0.22.0 
monokai-seti 0.7.0 
pigments 0.39.1 
project-manager 3.3.4 
python-isort 0.0.7 
scroll-without-moving-cursor 0.3.5 
seti-ui 1.7.0 
symbols-view-plus 0.113.2-plus.4 
todo-show 1.11.0 
toggle-quotes 1.0.1 
wombat-light-syntax 1.2.0 
```

**Comment by Frida854** [comment]
I had the same error today, but it was only showing up, when I removed g++. When I reinstalled g++ it went away again. I'm on Linux Mint 17.3

**Comment by trypag** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: "Fedora release
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.28.1


### Stack Trace

Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined

```
At /home/ganaye/.atom/packages/minimap/lib/kite-wrapper.js:117

TypeError: Cannot read property 'onDidStopChanging' of undefined
    at /packages/minimap/lib/kite-wrapper.js:117:43)
    at /packages/minimap/node_modules/atom-utils/lib/register-or-update-element.js:15:57)
    at /app.asar/src/pane-axis-element.js:95:12)
    at /app.asar/src/pane-axis-element.js:129:12)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneAxis.module.exports.PaneAxis.replaceChild (/app.asar/src/pane-axis.js:200:27)
    at Pane.module.exports.Pane.split (/app.asar/src/pane.js:919:21)
    at Pane.module.exports.Pane.splitDown (/app.asar/src/pane.js:907:19)
    at showFile (/packages/git-plus/lib/models/git-commit.coffee:86:7)
    at startCommit (/packages/git-plus/lib/models/git-commit.coffee:114:5)
    at /packages/git-plus/lib/models/git-commit.coffee:128:20
```

### Commands

```
     -0:41.6.0 git-plus:add-all-commit-and-push (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
atom-clock 0.1.7 
atom-runner 2.7.1 
autocomplete 0.47.0 
autocomplete-clang 0.11.3 
autocomplete-python 1.8.63 
build 0.67.0 
build-cmake 0.9.1 
build-make 0.13.0 
busy 0.7.0 
busy-signal 1.4.1 
color-picker 2.2.5 
file-icons 2.1.4 
git-plus 7.7.0 
gpp-compiler 3.0.7 
intentions 1.1.2 
language-cmake 0.3.0 
language-latex 1.0.0 
language-lua 0.9.11 
linter 2.1.4 
linter-lua 1.0.4 
linter-pycodestyle 2.0.2 
linter-ui-default 1.2.3 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.4 
minimap 4.28.1 
project-manager 3.3.4 
python-indent 1.0.2 
python-tools 0.6.9 
sync-settings 0.8.1 
```
