### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scan' of undefined

### ISSUE THREAD

**Issue by jeremygrace** [atom-minimap/minimap#595]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.28.2

### Stack Trace

Uncaught TypeError: Cannot read property 'scan' of undefined

```
At /Users/Jeremy/.atom/packages/minimap/lib/kite-wrapper.js:104

TypeError: Cannot read property 'scan' of undefined
    at /packages/minimap/lib/kite-wrapper.js:104:20)
    at subscriptions.add.textEditor.onDidStopChanging (/packages/minimap/lib/kite-wrapper.js:128:12)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/node_modules/text-buffer/lib/text-buffer.js:1392:25
```

### Commands

```
  3x -7:42.6.0 core:backspace (input.hidden-input)
     -7:08.8.0 core:paste (input.hidden-input)
     -7:04.7.0 core:save (input.hidden-input)
     -4:13.8.0 core:paste (input.hidden-input)
     -3:34.3.0 core:save (input.hidden-input)
  6x -3:00.9.0 core:backspace (input.hidden-input)
  6x -2:13.9.0 core:undo (input.hidden-input)
     -2:01.3.0 core:save (input.hidden-input)
     -0:50.4.0 tabs:split-right (li.texteditor.tab.sortable.active.right-clicked)
     -0:43.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-jade 0.3.0 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.10 
autocomplete-python 1.8.63 
busy-signal 1.4.1 
chester-atom-syntax 0.1.1 
file-icons 2.1.4 
intentions 1.1.2 
linter 2.1.4 
linter-flake8 2.2.1 
linter-pycodestyle 2.0.2 
linter-ui-default 1.2.3 
markdown-pdf 1.5.0 
minimap 4.28.2 
monokai 0.22.0 
pigments 0.39.1 
spacegray-atom-dark-syntax 1.3.2 
```

**Comment by soumendrak** [comment]
Every time I type something it throws this error. Is there anyway to at least disable this pop-up ?

**Comment by YannickSchini** [comment]
Same here !

**Comment by mahmoudalismail** [comment]
I had the same problem and the issue was resolved for me by closing all Atom windows and quitting the application on Mac. Once I relaunched Atom, it was resolved. I am running on Mac 10.12.4 and Atom 1.16.0 x64. I am not sure what the underlying cause but its one interesting bug! 

@soumendrak if my work around does not work, you could try disabling the minimap package for now.

**Comment by imutkarshpatil** [comment]
Are you guys behind any proxy server which is blocking `docs` part of the minimap? Issue with me was it was blocking some scripts and connection to [kite.com](https://kite.com/docs/)'s doc hyperlinks.

**Comment by madLyfe** [comment]
i also had this error just now.
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.28.2


### Stack Trace

Uncaught TypeError: Cannot read property 'scan' of undefined

```
At C:\Users\madLy\.atom\packages\minimap\lib\kite-wrapper.js:104

TypeError: Cannot read property 'scan' of undefined
    at /packages/minimap/lib/kite-wrapper.js:104:20)
    at subscriptions.add.textEditor.onDidStopChanging (/packages/minimap/lib/kite-wrapper.js:128:12)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/text-buffer/lib/text-buffer.js:1442:1
```

### Commands

```
     -6:45.1.0 tabs:split-right (div.title.icon.python-icon.dark-blue)
     -2:11.2.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.7.3 
atom-runner 2.7.1 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.63 
comment 0.6.1 
copy-on-select 0.2.0 
file-icons 2.1.7 
highlight-selected 0.13.1 
minimap 4.28.2 
minimap-autohider 1.4.0 
quick-highlight 0.10.0 
```
