### ISSUE TITLE
Uncaught TypeError: Cannot read property 'insertBefore' of null

### ISSUE THREAD

**Issue by Tibo-ds** [atom-minimap/minimap#597]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.28.2

### Stack Trace

Uncaught TypeError: Cannot read property 'insertBefore' of null

```
At C:\Users\tibo-\.atom\packages\minimap\lib\kite-wrapper.js:69

TypeError: Cannot read property 'insertBefore' of null
    at /packages/minimap/lib/kite-wrapper.js:69:20)
    at subscriptions.add.atom.config.observe (/packages/minimap/lib/kite-wrapper.js:136:21)
    at /app.asar/src/config.js:618:16
    at /app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at Config.module.exports.Config.emitChangeEvent (/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/app.asar/src/config.js:227:14)
    at click (/packages/minimap/lib/kite-wrapper.js:147:21)
    at /packages/minimap/node_modules/atom-utils/lib/mixins/events-delegation.js:128:18
    at /packages/minimap/node_modules/atom-utils/lib/mixins/events-delegation.js:144:13)
    at /packages/minimap/node_modules/atom-utils/lib/mixins/events-delegation.js:122:22
    at /packages/minimap/node_modules/atom-utils/lib/mixins/events-delegation.js:169:7)
    at /packages/minimap/node_modules/atom-utils/lib/mixins/events-delegation.js:118:19)
    at /packages/minimap/node_modules/atom-utils/lib/mixins/events-delegation.js:105:15)
```

### Commands

```
     -2:03.3.0 intentions:highlight (input.hidden-input)
 12x -2:02.4.0 core:backspace (input.hidden-input)
     -1:57 autocomplete-plus:confirm (input.hidden-input)
  3x -1:51.1.0 core:move-left (input.hidden-input)
     -1:50.3.0 core:backspace (input.hidden-input)
  5x -1:49.7.0 core:move-right (input.hidden-input)
     -1:48.9.0 editor:newline (input.hidden-input)
  4x -1:46 core:backspace (input.hidden-input)
  2x -1:32.8.0 core:move-left (input.hidden-input)
  3x -1:31.7.0 core:backspace (input.hidden-input)
  2x -1:30.6.0 core:move-right (input.hidden-input)
     -1:28.7.0 autocomplete-plus:confirm (input.hidden-input)
  2x -0:45.8.0 core:backspace (input.hidden-input)
 12x -0:42.1.0 core:move-left (input.hidden-input)
 12x -0:38.7.0 core:move-right (input.hidden-input)
 37x -0:35.7.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
busy-signal 1.4.1 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.2.3 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
open-recent 5.0.0 
python-snippets 1.9.0 
script 3.14.1 
simple-drag-drop-text 0.3.4 
```

**Comment by madLyfe** [comment]
i just had this error as well while messing around in the settings:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.28.2


### Stack Trace

Uncaught TypeError: Cannot read property 'insertBefore' of null

```
At C:\Users\madLy\.atom\packages\minimap\lib\kite-wrapper.js:69

TypeError: Cannot read property 'insertBefore' of null
    at /packages/minimap/lib/kite-wrapper.js:69:20)
    at subscriptions.add.atom.config.observe (/packages/minimap/lib/kite-wrapper.js:136:21)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:627:1
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:644:1
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:835:1)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:621:1)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:236:1)
    at SettingsPanel.set (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/settings-panel.js:229:1)
    at HTMLInputElement.changeHandler (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/settings-panel.js:174:1)
```

### Commands

```
     -5:42.4.0 editor:newline (input.hidden-input)
  5x -2:20.5.0 core:backspace (input.hidden-input)
     -1:41.9.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
 14x -1:34.3.0 core:backspace (input.hidden-input)
     -1:32.3.0 editor:consolidate-selections (input.hidden-input)
     -1:32.3.0 core:cancel (input.hidden-input)
     -1:30.4.0 command-palette:toggle (input.hidden-input)
     -1:19.3.0 settings-view:view-installed-packages (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.7.3 
atom-runner 2.7.1 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.63 
comment 0.6.1 
copy-on-select 0.2.0 
file-icons 2.1.7 
highlight-selected 0.13.1 
minimap 4.28.2 
minimap-autohider 1.4.0 
quick-highlight 0.10.0 
```
