### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scan' of undefined

### ISSUE THREAD

**Issue by jomno** [atom-minimap/minimap#604]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.28.2

### Stack Trace

Uncaught TypeError: Cannot read property 'scan' of undefined

```
At C:\Users\oneno\.atom\packages\minimap\lib\kite-wrapper.js:104

TypeError: Cannot read property 'scan' of undefined
    at /packages/minimap/lib/kite-wrapper.js:104:20)
    at subscriptions.add.textEditor.onDidStopChanging (/packages/minimap/lib/kite-wrapper.js:128:12)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/text-buffer/lib/text-buffer.js:1442:1
```

### Commands

```
  7x -9:52.8.0 core:backspace (input.hidden-input)
     -9:51.1.0 core:save (input.hidden-input)
     -4:09.7.0 core:paste (input.hidden-input)
     -4:09.0 core:save (input.hidden-input)
     -2:21.4.0 tabs:split-right (div.title.icon.python-icon.dark-blue)
  6x -2:02.7.0 core:backspace (input.hidden-input)
     -1:26.9.0 tabs:split-right (div.title.icon.python-icon.dark-blue)
  2x -1:19.5.0 core:backspace (input.hidden-input)
     -1:05.7.0 core:copy (input.hidden-input)
     -1:04.4.0 core:cut (input.hidden-input)
  2x -1:00.8.0 editor:newline (input.hidden-input)
     -1:00.2.0 core:paste (input.hidden-input)
     -0:59.2.0 core:move-left (input.hidden-input)
  6x -0:56.2.0 core:backspace (input.hidden-input)
     -0:50.4.0 core:move-right (input.hidden-input)
  2x -0:48.5.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
aligner 1.2.0 
aligner-javascript 1.1.0 
atom-beautify 0.29.24 
atom-nodejs-snippets 1.5.0 
atom-ternjs 0.18.3 
code-peek 1.4.20 
column-select 0.2.0 
emmet 2.4.3 
file-icons 2.1.6 
git-control 0.9.0 
git-plus 7.9.2 
git-time-machine 1.5.9 
goto-last-edit 0.3.3 
highlight-selected 0.13.1 
jade-beautify 0.1.5 
markdown-scroll-sync 2.1.2 
minimap 4.28.2 
node-debugger 1.10.1 
pigments 0.39.1 
script 3.15.0 
swackets 0.26.0 
```

**Comment by Kilo59** [comment]
Getting this error too. Seems to only happen on my "right split" panels.

**Stack Trace**
```
TypeError: Cannot read property 'scan' of undefined
    at kite-minimap-wrapper.update (~\.atom\packages\minimap\lib\kite-wrapper.js:104:20)
    at subscriptions.add.textEditor.onDidStopChanging (~\.atom\packages\minimap\lib\kite-wrapper.js:128:12)
    at Function.module.exports.Emitter.simpleDispatch (~\AppData\Local\atom\app-1.18.0\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~\AppData\Local\atom\app-1.18.0\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at ~\AppData\Local\atom\app-1.18.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1442:31
``

**Comment by oxcug** [comment]
Same is happening for me on macOS.

**Comment by KillersDeath** [comment]
Same is happening for me on macOS too, how to fix it ?.

**Comment by marcusguttenplan** [comment]
This just started throwing for me too, with slightly different stack trace than OP's:

```
TypeError: Cannot read property 'scan' of undefined
    at kite-minimap-wrapper.update (/Users/me/.atom/packages/minimap/lib/kite-wrapper.js:104:20)
    at subscriptions.add.textEditor.onDidStopChanging (/Users/me/.atom/packages/minimap/lib/kite-wrapper.js:128:12)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1442:1
```

Specifically `at kite-minimap-wrapper.update`, and sure enough it fires on every single update to one doc -- only occurring in a python file in the furthest left pane. Can't recreate with another python file or any other file type. Strange!

**Comment by viddo** [comment]
Similar to @Kilo59 it only happens to me in "right split". Been able to reproduce it now, when selecting a word (double clicking it) and then moving the cursor elsewhere (direction doesn't matter).

**Comment by viddo** [comment]
So did some quick debugging to see what could be wrong:
It throws the exception here: https://github.com/atom-minimap/minimap/blob/master/lib/kite-wrapper.js#L104 which indeed is because `this.textEditor` is undefined. `this` appears to be the expected context object (`<kite-minimap-wrapper />`).

Based on a glancing through the same file it's my understanding that this err could only happen if the element is actually [destroyed]
(https://github.com/atom-minimap/minimap/blob/master/lib/kite-wrapper.js#L64).

The element isn't present in the DOM tree, so that verifies that, but it doesn't explain why the listener keeps firing. Supposedly that should be cleaned up upon the [`subscriptions.dispose()`](https://github.com/atom-minimap/minimap/blob/master/lib/kite-wrapper.js#L60).

Not more familiar with this code to be able to tell where the root problem really could be. Ideas anyone?

**Comment by mwent-cray** [comment]
Happens on macOS here.
