### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scan' of undefined

### ISSUE THREAD

**Issue by danieldemonceau** [atom-minimap/minimap#610]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.28.2

### Stack Trace

Uncaught TypeError: Cannot read property 'scan' of undefined

```
At C:\Users\daniel.demonceau\.atom\packages\minimap\lib\kite-wrapper.js:104

TypeError: Cannot read property 'scan' of undefined
    at /packages/minimap/lib/kite-wrapper.js:104:20)
    at subscriptions.add.textEditor.onDidStopChanging (/packages/minimap/lib/kite-wrapper.js:128:12)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1442:31
```

### Commands

```
     -0:31.7.0 intentions:highlight (input.hidden-input)
     -0:31.6.0 editor:toggle-line-comments (input.hidden-input)
     -0:30.6.0 intentions:highlight (input.hidden-input)
     -0:30.6.0 editor:toggle-line-comments (input.hidden-input)
     -0:30.1.0 intentions:highlight (input.hidden-input)
     -0:30 editor:toggle-line-comments (input.hidden-input)
     -0:29.2.0 intentions:highlight (input.hidden-input)
     -0:29.1.0 editor:toggle-line-comments (input.hidden-input)
     -0:27 intentions:highlight (input.hidden-input)
     -0:27 editor:toggle-line-comments (input.hidden-input)
     -0:15 intentions:highlight (input.hidden-input)
     -0:14.9.0 editor:toggle-line-comments (input.hidden-input)
     -0:13.9.0 intentions:highlight (input.hidden-input)
     -0:13.8.0 editor:toggle-line-comments (input.hidden-input)
     -0:09.5.0 intentions:highlight (input.hidden-input)
     -0:09.4.0 editor:toggle-line-comments (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-history 1.0.8 
atom-jshint 2.0.0 
atom-prettify 0.1.3 
atom-shortcuts 0.0.2 
autocomplete-clang 0.11.3 
build 0.68.0 
busy 0.7.0 
busy-signal 1.4.3 
file-icons 2.1.8 
git-diff-details 1.4.0 
git-history 3.3.0 
git-plus 7.9.3 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.2 
local-history 4.3.0 
merge-conflicts 1.4.5 
minimap 4.28.2 
platformio-ide-terminal 2.5.3 
tool-bar 1.1.0 
```

**Comment by drvid** [comment]
I just encountered this issue as well...

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.28.2


### Stack Trace

Uncaught TypeError: Cannot read property 'scan' of undefined

```
At C:\Users\Dave\.atom\packages\minimap\lib\kite-wrapper.js:104

TypeError: Cannot read property 'scan' of undefined
    at /packages/minimap/lib/kite-wrapper.js:104:20)
    at subscriptions.add.textEditor.onDidStopChanging (/packages/minimap/lib/kite-wrapper.js:128:12)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1442:31
```

### Commands

```
  4x -3:46.3.0 core:backspace (input.hidden-input)
     -3:43 core:confirm (input.hidden-input)
     -2:55.1.0 intentions:highlight (input.hidden-input)
     -2:54.8.0 find-and-replace:show (input.hidden-input)
     -2:52.6.0 find-and-replace:find-next (input.hidden-input)
     -2:44.5.0 fuzzy-finder:toggle-file-finder (div.results-view.focusable-panel)
     -2:42.8.0 core:confirm (input.hidden-input)
  3x -1:40.6.0 core:delete (input.hidden-input)
     -1:04.9.0 editor:move-to-first-character-of-line (input.hidden-input)
  5x -1:04.3.0 core:select-down (input.hidden-input)
     -1:02.5.0 intentions:highlight (input.hidden-input)
     -1:02.4.0 editor:toggle-line-comments (input.hidden-input)
     -0:51.1.0 intentions:highlight (input.hidden-input)
     -0:50.8.0 core:save (input.hidden-input)
     -0:49.7.0 intentions:highlight (input.hidden-input)
     -0:49.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
busy-signal 1.4.3 
django-templates 0.5.0 
editorconfig 2.2.2 
intentions 1.1.2 
language-nginx 0.8.0 
linter 2.2.0 
linter-bootlint 1.0.4 
linter-eslint 8.2.1 
linter-jshint 3.1.4 
linter-jsonlint 1.3.0 
linter-ui-default 1.6.2 
minimap 4.28.2 
tabs-to-spaces 1.0.3 
```
