### ISSUE TITLE
Uncaught InvalidStateError: Failed to execute 'dispatchEvent' on 'EventTarget': The event is alre...

### ISSUE THREAD

**Issue by kurtschlatzer** [atom-minimap/minimap#614]
[Enter steps to reproduce:]

1. Mouse over the Minimap

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.29.1

### Stack Trace

Uncaught InvalidStateError: Failed to execute 'dispatchEvent' on 'EventTarget': The event is already being dispatched.

```
At /Users/kschlatzer/.atom/packages/minimap/lib/minimap-element.js:1138

Error: Failed to execute 'dispatchEvent' on 'EventTarget': The event is already being dispatched.
    at Error (native)
    at /packages/minimap/lib/minimap-element.js:1138:35)
    at /packages/minimap/lib/minimap-element.js:492:16)
    at /packages/minimap/node_modules/atom-utils/lib/mixins/events-delegation.js:108:41)
```

### Commands

```
     -4:18.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-nord-atom-syntax-accessibility-custom-comment-contrast)
```

### Non-Core Packages

```
afterglow-monokai-syntax 1.3.7 
afterglow-syntax 1.0.0 
afterlight 1.0.0 
ample-syntax 0.3.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.4 
atom-cursor-indent 0.1.1 
atom-edit-in-new-tab 0.5.2 
atom-git-revert 0.2.5 
atom-html-templates 0.1.3 
atom-material-muted-syntax 1.0.10 
atom-min-ui 1.1.0 
atom-minify 0.8.0 
atom-sunburst 1.0.0 
auto-indent 0.5.0 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
base16-material-syntax 1.2.6 
bottom-dock 0.4.4 
bracket-padder 0.4.1 
busy-signal 1.4.3 
codepen-syntax 0.1.1 
color-picker 2.2.5 
conduit-ui 0.1.3 
css-declaration-sorter 1.0.1 
day-after-tomorrow 1.0.0 
diff-pane 0.3.0 
double-tag 0.9.0 
duotone-blue-black-syntax 0.7.3 
duotone-dark-syntax 2.1.0 
duotone-nature-syntax 0.2.0 
editorconfig 2.2.2 
file-icons 2.1.9 
fixmyjs 1.4.1 
git-control 0.9.0 
git-log 0.4.1 
git-plus 7.9.3 
git-time-machine 1.5.9 
github-atom-light-syntax 0.5.0 
gulp-control 0.5.0 
gulp-manager 0.2.19 
highlight-selected 0.13.1 
idleDigits 0.2.2 
indent-guide-improved 1.4.12 
intentions 1.1.2 
isotope-light-ui 2.2.7 
isotope-ui 2.8.5 
json-converter 0.2.4 
language-csv 1.1.2 
language-dots 0.0.4 
language-generic-config 1.3.0 
language-gitignore 0.3.0 
language-htaccess 0.1.1 
linter 2.2.0 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-js-yaml 1.2.7 
linter-jshint 3.1.5 
linter-json-lint 0.1.2 
linter-jsonlint 1.3.0 
linter-manager 0.2.12 
linter-php 1.3.2 
linter-sass-lint 1.7.4 
linter-scss-lint 3.1.0 
linter-tidy 2.3.1 
linter-ui-default 1.6.3 
linter-xmllint 1.4.3 
merge-conflicts 1.4.5 
min-syntax 1.0.0 
minimap 4.29.1 
minimap-codeglance 0.4.7 
minimap-find-and-replace 4.5.2 
minimap-hide 0.3.0 
minimap-highlight-selected 4.6.1 
minimap-selection 4.4.0 
new-moon-atom-syntax 2.0.9 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0
open-recent 5.0.0
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.0 
php-integrator-base 3.0.1 
php-integrator-call-tips-legacy-php56 1.2.3 
php-integrator-linter-legacy-php56 1.3.1 
php-integrator-navigation 1.2.1 
php-integrator-tooltips-legacy-php56 1.1.6 
php-light-syntax 1.0.2 
pretty-json 1.6.3 
project-manager 3.3.5 
simple-drag-drop-text 0.3.4 
sort-lines 0.14.0 
source-preview 0.5.2 
source-preview-less 0.1.6 
source-preview-sass 0.1.6 
ssh-config 0.10.1 
tablr 1.8.3 
tablr-json 0.1.0 
text-manipulation 0.6.0 
todo-show 1.11.0 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
tree-view-autoresize 2.1.0 
tree-view-copy-relative-path 1.2.0 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.4.0 
wordpress-api 1.2.2 
xml-formatter 0.11.0 
xml-tools 0.2.1 
```

**Comment by dertin** [comment]
I have the same error.

**Comment by loganabsher** [comment]
same problem just after updating.

**Comment by Derbyshire10** [comment]
I got this too after the recent update

**Comment by iczero** [comment]
I get this after trying to scroll while over the minimap.

**Comment by daniandl** [comment]
Same error happens randomly when scrolling

**Comment by ughitsaaron** [comment]
me too
