### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, 0) thrown when highlighting

### ISSUE THREAD

**Issue by river226** [atom-minimap/minimap#643]
Note, did not check if error already reported, and not copied produced error report. 

1. Select/Highlight Text

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.6
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.29.6

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, 0)

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at DisplayLayer.translateScreenPosition (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:333:17)
    at DisplayLayer.clipScreenPosition (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:391:18)
    at TextEditor.module.exports.TextEditor.clipScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1794:38)
    at HTMLElement.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:242:38)
    at StableAdapter.computeScrollTop (/packages/minimap/lib/adapters/stable-adapter.js:60:42)
    at StableAdapter.getScrollTop (/packages/minimap/lib/adapters/stable-adapter.js:51:17)
    at Minimap.getTextEditorScrollRatio (/packages/minimap/lib/minimap.js:598:25)
    at Minimap.getCapedTextEditorScrollRatio (/packages/minimap/lib/minimap.js:610:29)
    at Minimap.getScrollTopFromEditor (/packages/minimap/lib/minimap.js:937:12)
    at Minimap.getScrollTop (/packages/minimap/lib/minimap.js:887:14)
    at Minimap.getLastVisibleScreenRow (/packages/minimap/lib/minimap.js:865:13)
    at Minimap.emitRangeChanges (/packages/minimap/lib/mixins/decoration-management.js:504:38)
    at Minimap.emitDecorationChanges (/packages/minimap/lib/mixins/decoration-management.js:489:10)
    at Minimap.decorateMarker (/packages/minimap/lib/mixins/decoration-management.js:422:10)
    at MinimapHighlightSelected.markerCreated (/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:53:26)
    at MinimapHighlightSelected.markerCreated (/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:1:1)
    at /packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:39:62
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:163:20
    at ForwardsSingleLine.iterate (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/match-iterator.js:94:17)
    at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1090:29)
    at TextEditor.module.exports.TextEditor.scanInBufferRange (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2737:32)
    at HighlightedAreaView.module.exports.HighlightedAreaView.highlightSelectionInEditor (/packages/highlight-selected/lib/highlighted-area-view.coffee:151:12)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:136:10
    at Array.forEach (native)
    at HighlightedAreaView.module.exports.HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:135:27)
    at HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:62:8
```

### Commands

```
     -0:29.5.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
language-csv 1.1.2 
highlight-selected 0.13.1 
language-4gl 0.2.0 
language-csv 1.1.2 
language-pascal 0.20.2 
minimap 4.29.6 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
Sublime-Style-Column-Selection 1.7.4 
tablr 1.8.3 
```

**Comment by zeckdude** [comment]
This has been fixed in version 4.29.7
