### ISSUE TITLE
Uncaught TypeError: tokenizedBuffer.onDidTokenize is not a function

### ISSUE THREAD

**Issue by Arcanemagus** [atom-minimap/minimap#649]
It looks like `minimap` was using a private method that has been removed in the latest Atom beta.

----

Enter steps to reproduce:

1. Install `minimap`
2. Open a file.

**Atom**: 1.25.0-beta0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.29.7

### Stack Trace

Failed to activate the minimap package

```
At tokenizedBuffer.onDidTokenize is not a function

TypeError: tokenizedBuffer.onDidTokenize is not a function
    at /packages/minimap/lib/minimap.js:277:30)
    at Main.minimapForEditor (/packages/minimap/lib/main.js:327:17)
    at subscriptions.add.atom.workspace.observeTextEditors (/packages/minimap/lib/main.js:390:26)
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.25.0-beta0/resources/app/src/workspace.js:637:59)
    at Main.initSubscriptions (/packages/minimap/lib/main.js:389:43)
    at Main.toggle (/packages/minimap/lib/main.js:184:12)
    at Main.activate (/packages/minimap/lib/main.js:115:55)
    at Package.activateNow (~/AppData/Local/atom/app-1.25.0-beta0/resources/app/src/package.js:230:33)
    at measure (~/AppData/Local/atom/app-1.25.0-beta0/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.25.0-beta0/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.25.0-beta0/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.25.0-beta0/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.25.0-beta0/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.25.0-beta0/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (~/AppData/Local/atom/app-1.25.0-beta0/resources/app/src/config.js:852:28)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.25.0-beta0/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.25.0-beta0/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.25.0-beta0/resources/app/src/atom-environment.js:867:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

<details>
<summary>Packages</summary>

```
atom-beautify 0.30.9 
atom-ide-ui 0.8.1 
atom-material-ui 2.1.1 
autocomplete-lua 0.9.0 
busy-signal 1.4.3 
docblockr 0.13.6 
editorconfig 2.2.2 
file-watcher 1.2.6 
highlight-selected 0.13.1 
ide-flowtype 0.19.0 
ide-php 0.7.5 
ide-python 0.7.0 
ide-typescript 0.7.2 
intentions 1.1.5 
language-ansible 0.2.2 
language-chef 0.11.0 
language-cjson 0.0.1 
language-docker 1.1.8 
language-elixir 0.22.0 
language-erlang 3.2.0 
language-fortran 2.1.6 
language-gettext 0.6.1 
language-glsl 2.0.4 
language-haml 0.25.2 
language-haskell 1.17.3 
language-icinga2 0.4.1 
language-ini 1.19.0 
language-jade 0.7.2 
language-jolie 0.5.0 
language-kotlin 0.5.0 
language-livescript 0.0.3 
language-lua 0.9.11 
language-moonscript 1.7.1 
language-postcss 1.3.1 
language-powershell 4.0.0 
language-pug 0.0.22 
language-puppet 0.23.0 
language-r 0.4.2 
language-reg 0.0.0 
language-rust 0.4.12 
language-swift 0.5.0 
language-terraform 0.8.1 
language-vue 0.23.1 
linter 2.2.0 
linter-coffeelint 1.3.1 
linter-eslint 8.4.1 
linter-flake8 2.3.0 
linter-htmlhint 1.4.0 
linter-js-standard 4.2.0 
linter-js-yaml 1.2.8 
linter-jsonlint 1.3.0 
linter-markdown 5.2.0 
linter-perl 0.8.1 
linter-perlcritic 2.0.0 
linter-php 1.5.1 
linter-phpcs 1.6.8 
linter-phpmd 2.0.0 
linter-proselint 3.3.0 
linter-pylama 0.9.5 
linter-pylint 2.1.1 
linter-rails-best-practices 0.2.2 
linter-reek 2.2.2 
linter-rubocop 2.2.3 
linter-ruby 1.2.6 
linter-stylelint 4.2.0 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
linter-ui-plus 0.3.2 
mapfile-grammar 0.1.0 
minimap 4.29.7 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-selection 4.5.0 
sequential-number 0.5.0 
sort-lines 0.18.0 
tab-control 0.6.10 
teletype 0.7.0 
terminal-tab 0.5.0 
toggle-quotes 1.1.0 
trailing-spaces 0.4.0 
```
</details>

**Comment by Evpok** [comment]
I can reproduce, but only when using tree-sitter grammars.

**Comment by Arcanemagus** [comment]
Yep, needs to be a `tree-sitter` grammar to reproduce, since they don't have the private properties the current code is relying on. The wrapper provided by Atom and used in #650 works though 😉.
