### ISSUE TITLE
Failed to initialize the minimap package

### ISSUE THREAD

**Issue by RammahKarpous** [atom-minimap/minimap#657]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Home
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.29.8

### Stack Trace

Failed to initialize the minimap package

```
At Cannot read property 'initialize' of null

TypeError: Cannot read property 'initialize' of null
    at measure (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:185:41)
    at Package.measure (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:88:25)
    at Package.initializeIfNeeded (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:178:16)
    at Object.viewRegistry.addViewProvider.model [as createView] (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:537:22)
    at ViewRegistry.createView (~/AppData/Local/atom/app-1.24.1/resources/app/src/view-registry.js:154:34)
    at ViewRegistry.getView (~/AppData/Local/atom/app-1.24.1/resources/app/src/view-registry.js:127:25)
    at subscriptions.add.atom.workspace.observeTextEditors (/packages/minimap/lib/main.js:391:39)
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.24.1/resources/app/src/workspace.js:728:15)
    at Main.initSubscriptions (/packages/minimap/lib/main.js:389:43)
    at Main.toggle (/packages/minimap/lib/main.js:184:12)
    at Main.activate (/packages/minimap/lib/main.js:115:55)
    at Package.activateNow (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:230:33)
    at measure (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:200:20)
    at Package.activate (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.24.1/resources/app/src/package-manager.js:695:42)
    at ~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.24.1/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.24.1/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -1:23.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.5 
atom-live-server 2.2.0 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.17 
less-autocompile 1.0.0 
minimap 4.29.8 
php-server 0.8.0 
sass 0.5.0 
sass-autocompile 0.13.5 
```

**Comment by aminya** [comment]
Please reinstall.
