### ISSUE TITLE
Uncaught SyntaxError: Error parsing $ATOM_HOME/packages\minimap\node_modules\element-resize-detec...

### ISSUE THREAD

**Issue by CaptainMorgans** [atom-minimap/minimap#659]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0-beta3 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Home
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.29.8

### Stack Trace

Uncaught SyntaxError: Error parsing C:\Users\Stephen\.atom\packages\minimap\node_modules\element-resize-detector\package.json: Unexpected token Z in JSON at position 0

```
At module.js:96

SyntaxError: Error parsing C:\Users\Stephen\.atom\packages\minimap\node_modules\element-resize-detector\package.json: Unexpected token Z in JSON at position 0
    at JSON.parse (<anonymous>)
    at readPackage (module.js:92:52)
    at tryPackage (module.js:102:13)
    at Function.Module._findPath (module.js:183:20)
    at Module._resolveFilename (module.js:468:25)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.25.0-beta3/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.25.0-beta3/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.25.0-beta3/resources/app/src/native-compile-cache.js:66:33)
    at /packages/minimap/lib/minimap-element.js:8:31)
    at /packages/minimap/lib/minimap-element.js:1393:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.25.0-beta3/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.25.0-beta3/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.25.0-beta3/resources/app/src/native-compile-cache.js:66:33)
    at Main.minimapViewProvider (/packages/minimap/lib/main.js:128:47)
    at Object.viewRegistry.addViewProvider.model [as createView] (~/AppData/Local/atom/app-1.25.0-beta3/resources/app/src/package.js:538:51)
    at ViewRegistry.createView (~/AppData/Local/atom/app-1.25.0-beta3/resources/app/src/view-registry.js:154:34)
    at ViewRegistry.getView (~/AppData/Local/atom/app-1.25.0-beta3/resources/app/src/view-registry.js:127:25)
    at subscriptions.add.atom.workspace.observeTextEditors (/packages/minimap/lib/main.js:391:39)
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.25.0-beta3/resources/app/src/workspace.js:637:59)
    at Main.initSubscriptions (/packages/minimap/lib/main.js:389:43)
    at Main.toggle (/packages/minimap/lib/main.js:184:12)
    at /packages/minimap/lib/main.js:98:14)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.25.0-beta3/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.25.0-beta3/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.25.0-beta3/resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.25.0-beta3/resources/app/src/application-delegate.js:346:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
     -1:19.5.0 window:focus-pane-on-right (input.hidden-input)
     -0:47.6.0 pane:split-right-and-copy-active-item (input.hidden-input)
  2x -0:31.3.0 minimap:toggle (span.syntax--string.syntax--quoted.syntax--double.syntax--html)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-css-comb 3.3.1 
atom-html-preview 0.2.5 
atom-ide-ui 0.9.3 
atom-material-ui 2.1.3 
color-picker 2.2.5 
emmet 2.4.3 
file-type-icons 1.3.4 
highlight-selected 0.13.1 
ide-css 0.2.0 
ide-html 0.4.2 
ide-typescript 0.7.5 
language-liquid 0.6.0 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
sync-settings 0.8.5 
```

**Comment by aminya** [comment]
This issue is too old. I don't think it is relevant now. Please install the latest version.
