### ISSUE TITLE
Failed to load the minimap package

### ISSUE THREAD

**Issue by lakshmandeep1** [atom-minimap/minimap#680]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.18
**System**: Unknown Windows Version
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.3.1

### Stack Trace

Failed to load the minimap package

```
At Cannot find module 'atom-utils'

Error: Cannot find module 'atom-utils'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\豊樹\AppData\Local\atom\app-1.0.18\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\豊樹\.atom\packages\minimap\lib\minimap-element.coffee:3:22)
  at Object.<anonymous> (C:\Users\豊樹\.atom\packages\minimap\lib\minimap-element.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\豊樹\AppData\Local\atom\app-1.0.18\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at new Main (C:\Users\豊樹\.atom\packages\minimap\lib\main.coffee:102:23)
  at Object.<anonymous> (C:\Users\豊樹\.atom\packages\minimap\lib\main.coffee:288:22)
  at Object.<anonymous> (C:\Users\豊樹\.atom\packages\minimap\lib\main.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\豊樹\AppData\Local\atom\app-1.0.18\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\豊樹\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package.js:761:34)
  at C:\Users\豊樹\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package.js:192:28
  at Package.module.exports.Package.measure (C:\Users\豊樹\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.load (C:\Users\豊樹\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package.js:183:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\豊樹\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\豊樹\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package-manager.js:369:14)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\豊樹\AppData\Local\atom\app-1.0.18\resources\app.asar\src\atom.js:667:21)
  at Object.<anonymous> (C:\Users\豊樹\AppData\Local\atom\app-1.0.18\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\豊樹\AppData\Local\atom\app-1.0.18\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\豊樹\AppData\Local\atom\app-1.0.18\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///C:/Users/%E8%B1%8A%E6%A8%B9/AppData/Local/atom/app-1.0.18/resources/app.asar/static/index.js:82:25)
  at window.onload (file:///C:/Users/%E8%B1%8A%E6%A8%B9/AppData/Local/atom/app-1.0.18/resources/app.asar/static/index.js:35:9)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "minimap": {}
}
```

### Installed Packages

```coffee
# User
atom-utils, v0.6.3
color-tabs-regex, v0.2.2
compass, v0.9.1
file-icons, v1.6.9
highlight-selected, v0.10.1
japanese-word-selection, v0.2.1
japanese-wrap, v0.2.7
linter, v1.6.0
minimap, v4.3.1
show-ideographic-space, v1.0.1
space-tab, v0.4.2
webbox-color, v0.5.8

# Dev
No dev packages
```

**Comment by aminya** [comment]
Please reinstall
