### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by yar0d** [atom-minimap/minimap#682]
Just open Atom and get this crash.

**Atom**: 1.34.0 x64
**Electron**: 3.1.1
**OS**: "Antergos Linux"
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.29.9

### Stack Trace

Uncaught Error: Requested measurement of a line component that is not currently rendered

```
At /usr/lib/atom/src/text-editor-component.js:2278

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (/usr/lib/atom/src/text-editor-component.js:2267:23)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.measureHorizontalPositions (/usr/lib/atom/src/text-editor-component.js:2260:39)
    at TextEditorComponent.measureContentDuringUpdateSync (/usr/lib/atom/src/text-editor-component.js:401:10)
    at TextEditorComponent.updateSync (/usr/lib/atom/src/text-editor-component.js:280:33)
    at TextEditorComponent.pixelPositionForScreenPosition (/usr/lib/atom/src/text-editor-component.js:198:12)
    at HTMLElement.pixelPositionForScreenPosition (/usr/lib/atom/src/text-editor-element.js:246:32)
    at StableAdapter.computeScrollTop (/packages/minimap/lib/adapters/stable-adapter.js:66:42)
    at StableAdapter.getScrollTop (/packages/minimap/lib/adapters/stable-adapter.js:47:36)
    at Minimap.getTextEditorScaledScrollTop (/packages/minimap/lib/minimap.js:529:25)
    at HTMLElement.update (/packages/minimap/lib/minimap-element.js:808:36)
    at requestAnimationFrame (/packages/minimap/lib/minimap-element.js:780:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.16 
atom-ide-debugger-node 0.7.3 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-save-all 0.4.1 
autocomplete-paths 2.12.2 
busy-signal 2.0.0 
color-picker 2.3.0 
file-icons 2.1.29 
gl-light-syntax 3.0.0 
highlight-selected 0.14.0 
ide-css 0.3.2 
ide-html 0.5.0 
ide-json 0.2.1 
ide-vue 0.1.9 
ide-yaml 0.4.4 
intentions 1.1.5 
language-docker 1.1.8 
language-stylus 0.2.0 
language-vue 0.24.0 
linter 2.3.0 
linter-eslint 8.5.1 
linter-js-standard 6.1.0 
linter-jshint 3.1.11 
linter-jsonlint 1.4.0 
linter-less 2.6.0 
linter-python 3.1.2 
linter-ui-default 1.7.1 
markdown-pdf 2.2.0 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
monokai 0.24.0 
platformio-ide-terminal 2.9.0 
project-manager 3.3.6 
split-diff 1.6.0 
standard-formatter 2.8.0 
todo-show 2.3.2 
tree-view-git-status 1.5.2 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by UziTech** [comment]
I think this was an issue in Atom
