### ISSUE TITLE
Uncaught error:tunneling socket could not be established casue = connect ETIMEDOUT 10.177.38.133:80

### ISSUE THREAD

**Issue by vikalpjain91** [atom-minimap/minimap#691]
I have installed Minimap
and in the right it is showing this error in red box.

Logs:
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.177.38.133:80

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.177.38.133:80
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
  2x -9:15.8.0 editor:newline (input.hidden-input)
     -9:11.8.0 snippets:next-tab-stop (input.hidden-input)
     -9:11.8.0 snippets:expand (input.hidden-input)
     -9:11.8.0 editor:indent (input.hidden-input)
 10x -9:11.3.0 core:backspace (input.hidden-input)
  2x -8:59.4.0 editor:newline (input.hidden-input)
     -8:54 snippets:next-tab-stop (input.hidden-input)
     -8:54 snippets:expand (input.hidden-input)
     -8:54 editor:indent (input.hidden-input)
  7x -8:53.5.0 core:backspace (input.hidden-input)
     -4:19.8.0 core:select-all (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.14.0 
file-icons 2.1.32 
minimap 4.29.9 
platformio-ide-terminal 2.9.1 
script 3.18.1 
```

**Comment by aminya** [comment]
This issue is an internet/ISP issue.
