### ISSUE TITLE
Uncaught InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The imag...

### ISSUE THREAD

**Issue by sanyuanya** [atom-minimap/minimap#702]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.29.9

### Stack Trace

Uncaught InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

```
At C:\Users\hp\.atom\packages\minimap\lib\canvas-layer.js:64

Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at CanvasLayer.copyToOffscreen (/packages/minimap/lib/canvas-layer.js:64:27)
    at HTMLElement.redrawRangesOnLayer (/packages/minimap/lib/mixins/canvas-drawer.js:285:11)
    at HTMLElement.updateTokensLayer (/packages/minimap/lib/mixins/canvas-drawer.js:136:10)
    at HTMLElement.updateCanvas (/packages/minimap/lib/mixins/canvas-drawer.js:104:10)
    at HTMLElement.update (/packages/minimap/lib/minimap-element.js:887:10)
    at /packages/minimap/lib/minimap-element.js:780:12
```

### Commands

```
  6x -1:37 core:confirm (input.hidden-input)
  8x -1:06.7.0 intentions:highlight (input.hidden-input)
     -1:06.0 tree-view:toggle (input.hidden-input)
  2x -1:02.6.0 intentions:highlight (input.hidden-input)
     -0:58.5.0 core:save (input.hidden-input)
  3x -0:56.5.0 intentions:highlight (input.hidden-input)
     -0:42.7.0 command-palette:toggle (input.hidden-input)
     -0:39.7.0 core:confirm (input.hidden-input)
     -0:39.7.0 autocomplete-plus:navigate-to-description-more-link (input.hidden-input)
     -0:37.8.0 intentions:highlight (input.hidden-input)
     -0:37.4.0 command-palette:toggle (input.hidden-input)
     -0:29.7.0 intentions:highlight (input.hidden-input)
  2x -0:29.3.0 emmet:merge-lines (input.hidden-input)
     -0:26.9.0 intentions:highlight (input.hidden-input)
     -0:26.5.0 command-palette:toggle (input.hidden-input)
     -0:22.2.0 markdown-preview:toggle (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-autocomplete-php 0.25.6 
atom-python-run 0.9.7 
build 0.70.0 
busy-signal 2.0.1 
emmet 2.4.3 
gcc-make-run 0.2.12 
goto 1.8.3 
goto-definition 1.3.4 
hyperclick 0.1.5 
ide-dlang 1.17.1 
intentions 1.1.5 
laravel 0.7.1 
linter 2.3.1 
linter-gcc 0.9.0 
linter-ui-default 1.8.1 
markdown-preview-plus 3.11.5 
minimap 4.29.9 
php-hyperclick 1.2.1 
platformio-ide-terminal 2.10.0 
seti-ui 1.11.0 
simplified-chinese-menu 5.3.5 
```

**Comment by Mrreadiness** [comment]
I got this problem too, I have so mac

**Comment by pjgorski** [comment]
I also had this error. It was after upgrade of Atom, Julia client and while running for the first time 
`using Plots`

**Comment by rickydazla** [comment]
I got this error when opening the Github right side drawer when viewport was too  narrow to display that, the main panel, and the project tree view panel all at the same time.

**Comment by binbjz** [comment]
This problem has been around for a long time. When will it be fixed ?

**Comment by roman-sitewits** [comment]
Yep, still there:
1. Split Right on a tab
2. Drag the divider all the way to the right/left so that the width of the area is 0
3. Get the error

**Comment by AnnanKhan** [comment]
Still there 
it's not when the area is zero because if the divider is moved slowly to the edge then the error can be avoided
there is a problem with `drawImage`  and time(not at the program level probably) maybe has an effect.

**Comment by aminya** [comment]
Hey everyone. Minimap is abandoned. Please post your issues in minimap-plus:
https://atom.io/packages/minimap-plus

**Comment by aminya** [comment]
This is fixed in minimap-plus:
https://atom.io/packages/minimap-plus
