### ISSUE TITLE
Uncaught TypeError: this.getDevicePixelRatioRounding is not a function

### ISSUE THREAD

**Issue by hensyourbae** [atom-minimap/minimap#706]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.29.9

### Stack Trace

Uncaught TypeError: this.getDevicePixelRatioRounding is not a function

```
At C:\Users\hendrik\.atom\packages\minimap\lib\minimap.js:840

TypeError: this.getDevicePixelRatioRounding is not a function
    at Minimap.getDevicePixelRatio (/packages/minimap/lib/minimap.js:840:17)
    at HTMLElement.updateCanvasesSize (/packages/minimap/lib/minimap-element.js:1002:43)
    at HTMLElement.measureHeightAndWidth (/packages/minimap/lib/minimap-element.js:995:12)
    at HTMLElement.attachedCallback (/packages/minimap/lib/minimap-element.js:359:14)
    at /packages/minimap/node_modules/atom-utils/lib/register-or-update-element.js:15:57)
    at HTMLElement.activeItemChanged (/app.asar/src/pane-element.js:152:22)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:1190202)
    at Emitter.emit (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:1191643)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:456175)
    at Pane.addItem (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:459589)
    at Pane.activateItem (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:458377)
    at Workspace.open (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:432091)
    at async Promise.all (index 0)
    at AtomEnvironment.openLocations (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:1:766959)
```

### Commands

```
 21x -2:12.7.0 core:backspace (input.hidden-input)
     -1:49.5.0 tree-view:reveal-active-file (div.title)
     -0:32.8.0 pane:close (span.name.icon.icon-file-text)
     -0:12.3.0 application:new-file (atom-pane.pane.active)
```

### Non-Core Packages

```
autocomplete-paths 2.12.2 
color-picker 2.3.0 
emmet 2.4.3 
javascript-snippets 1.2.1 
language-blade 0.46.0 
minimap 4.29.9 
pigments 0.40.2 
```

**Comment by aminya** [comment]
Hey everyone. Minimap is abandoned. Please post your issues in minimap-plus:
https://atom.io/packages/minimap-plus
