### ISSUE TITLE
Uncaught TypeError: Cannot set property 'minimapElement' of null

### ISSUE THREAD

**Issue by the-woocash** [atom-minimap/minimap#764]
[Enter steps to reproduce:]

1. Toggle minimap to disable it - another error is thrown (#763)
2. Restart Atom
3. Toggle minimap to enable it.
4. Observe that minimap is not enabled, red error popup appears.

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.39.0

### Stack Trace

Uncaught TypeError: Cannot set property 'minimapElement' of null

```
At C:\Users\username\.atom\packages\minimap\dist\main-0471cbc5.js:1

TypeError: Cannot set property 'minimapElement' of null
    at HTMLElement.destroy (/packages/minimap/dist/main-0471cbc5.js:1:69786)
    at /packages/minimap/dist/main-0471cbc5.js:1:69420
    at NodeList.forEach (<anonymous>)
    at HTMLElement.attach (/packages/minimap/dist/main-0471cbc5.js:1:69406)
    at /packages/minimap/dist/main-0471cbc5.js:1:15610
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:429487)
    at Be (/packages/minimap/dist/main-0471cbc5.js:1:15514)
    at De (/packages/minimap/dist/main-0471cbc5.js:1:14409)
    at /packages/minimap/dist/main-0471cbc5.js:1:13635)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:350382)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:348857)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:1:754178)
    at EventEmitter.t (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:1:762128)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (~/AppData/Local/atom/app-1.54.0/resources/electron.asar/renderer/init.js:42:16)
```

### Commands

```
  3x -0:43.6.0 minimap:toggle (div.minimap-visible-area)
```

### Non-Core Packages

```
file-type-icons 1.3.4 
minimap 4.39.0 
remote-ftp 2.2.4 
```

**Comment by aminya** [comment]
Fixed in https://github.com/atom-minimap/minimap/commit/3685628c6c75aa57417a665eed054dda4f7c8061
