### ISSUE TITLE
Uncaught TypeError: Cannot read property 'DecorationManagement' of null

### ISSUE THREAD

**Issue by KalAvroniev** [atom-minimap/minimap#766]
Started getting this error after updating to the latest version.

[Enter steps to reproduce:]

1. Update to latest version.
2. Open a file, make a change and error pops up

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.1
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.39.1

### Stack Trace

Uncaught TypeError: Cannot read property 'DecorationManagement' of null

```
At /Users/kal/.atom/packages/minimap/dist/main-f082673e.js:1

TypeError: Cannot read property 'DecorationManagement' of null
    at ei.getDecorationManagement (/packages/minimap/dist/main-f082673e.js:1:93851)
    at ei.decorateMarker (/packages/minimap/dist/main-f082673e.js:1:94668)
    at MinimapGitDiffBinding.markRange (/packages/minimap-git-diff/lib/minimap-git-diff-binding.js:86:16)
    at MinimapGitDiffBinding.addDecorations (/packages/minimap-git-diff/lib/minimap-git-diff-binding.js:71:10)
    at MinimapGitDiffBinding.updateDiffs (/packages/minimap-git-diff/lib/minimap-git-diff-binding.js:58:9)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1191622)
    at TextBuffer.emitDidStopChangingEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:506208)
    at later (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:104700)
```

### Commands

```
     -6:08.6.0 core:save (input.hidden-input)
     -5:00.9.0 project-find:show (input.hidden-input)
     -4:45.8.0 editor:duplicate-lines (input.hidden-input)
     -4:37.6.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -4:24.7.0 core:copy (input.hidden-input)
     -4:24.3.0 pane:show-next-recently-used-item (input.hidden-input)
     -4:24.1.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -4:19.7.0 core:select-left (input.hidden-input)
     -4:19 core:paste (input.hidden-input)
     -4:18.6.0 core:save (input.hidden-input)
     -0:58.9.0 project-find:show (input.hidden-input)
     -0:31.7.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -0:31.5.0 core:delete (input.hidden-input)
     -0:30.4.0 find-and-replace:select-next (input.hidden-input)
     -0:16.8.0 editor:delete-line (input.hidden-input)
     -0:16.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-copy-with-line-numbers 0.1.0 
atom-debug-ui 1.0.4 
atom-ide-ui 0.13.0 
atom-react 1.0.0 
atom-storm-ui 2.0.1 
atom-typescript 14.1.2 
autocomplete-modules 2.3.0 
busy-signal 2.0.1 
chlorine 0.10.2 
clojure-lsp-adapter 0.1.0 
clojure-plus 0.3.0 
copy-path 0.5.1 
docblockr 0.13.7 
duplicate-removal 0.1.3 
emmet 2.4.3 
eslint-fixer 1.3.0 
file-icons 2.1.46 
git-blame 1.8.0 
git-control 0.9.0 
git-log 0.4.1 
git-time-machine 2.1.0 
grammar-token-limit 0.1.1 
highlight-selected 0.17.0 
hyperclick 0.0.0 
ide-css 0.3.5 
ide-html 0.6.2 
ide-json 0.2.1 
ide-kotlin 0.5.0 
ide-php 0.7.18 
ide-r 0.1.8 
ide-typescript 0.9.1 
ide-yaml 0.7.1 
ink 0.12.5 
intentions 1.1.5 
jquery-snippets 11.0.0 
js-refactor 0.8.1 
language-babel 2.85.0 
language-kotlin 0.5.0 
lemmings 1.3.0 
linter 3.2.3 
linter-clojure 1.2.0 
linter-eslint 8.5.5 
linter-jshint 3.1.19 
linter-jsonlint 1.4.0 
linter-kondo 1.2.0 
linter-kotlin 0.6.0 
linter-php 1.6.1 
linter-ui-default 2.4.1 
lisp-paredit 0.8.0 
local-history 4.3.1 
merge-conflicts 1.4.5 
minimap 4.39.1 
minimap-git-diff 4.3.5 
minimap-hide 0.3.0 
minimap-linter 2.2.2 
minimap-pigments 0.2.2 
minimap-split-diff 0.3.7 
multi-cursor 3.0.0 
open-git-modified-files 0.2.4 
parinfer 1.24.1 
php-composer-completion 0.3.4 
php-cs-fixer 4.2.0 
php-debug 0.3.5 
php-hyperclick 1.2.1 
pigments 0.40.6 
proto-repl 1.4.24 
proto-repl-charts 0.4.1 
proto-repl-sayid 0.1.4 
pull-request 0.2.1 
rainbow-delimiters 2.1.2 
react-function-to-class 0.2.4 
react-redux-atom-snippets 0.7.2 
refactor 0.11.5 
set-syntax 0.4.0 
split-diff 1.6.1 
swackets 0.35.0 
symbols-tree-view 0.14.0 
sync-settings 5.2.1 
tab-foldername-index 3.3.2 
tabs-closer 0.16.0 
teletype 0.13.4 
todo 0.6.0 
tool-bar 1.4.2 
tree-view-copy-relative-path 1.2.0 
```

**Comment by aminya** [comment]
I cannot reproduce the error. Did you try restarting Atom after updating?

**Comment by KalAvroniev** [comment]
Issue is gone in latest version 4.39.2

**Comment by aminya** [comment]
Great! Thanks.

**Comment by KalAvroniev** [comment]
Issue is back and more severe than before with version 4.39.4.

This time when I close Atom and reopen it, it freezes right after I see the above error plus a new one:
[Enter steps to reproduce:]

1. Close Atom
2. Open Atom
3. Project loads and then below and above errors pop up and editor freezes.
4. Force close
5. Open Atom
6. Loads with no project and same error as below shows
7. I can now choose to load a project
8. No errors show but if I close Atom the issue from step 2 repeats
9. Disabling minimap and minimap-git-diff stops the errors

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.1
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.39.4


### Stack Trace

Failed to activate the minimap package

```
At Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at /packages/minimap/dist/main-3af7aad3.js:1:69920
    at NodeList.forEach (<anonymous>)
    at HTMLElement.attach (/packages/minimap/dist/main-3af7aad3.js:1:69894)
    at Object.show (/packages/minimap-hide/lib/minimap-hide.coffee:41:21)
    at /packages/minimap-hide/lib/minimap-hide.coffee:29:8
    at Workspace.observeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:429943)
    at Object.activatePlugin (/packages/minimap-hide/lib/minimap-hide.coffee:25:46)
    at ce (/packages/minimap/dist/main-3af7aad3.js:1:10782)
    at de (/packages/minimap/dist/main-3af7aad3.js:1:10693)
    at /packages/minimap/dist/main-3af7aad3.js:1:11680
    at Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:335520)
    at Config.observe (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:330002)
    at pe (/packages/minimap/dist/main-3af7aad3.js:1:11664)
    at /packages/minimap/dist/main-3af7aad3.js:1:10118)
    at Object.consumeMinimapServiceV1 (/packages/minimap-hide/lib/minimap-hide.coffee:12:14)
    at Provider.provide (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1093694)
    at ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3525828)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3534167)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3531143)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1191622)
    at PackageManager.triggerDeferredActivationHooks (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:384090)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382841
    at TextEditorRegistry.updateAndMonitorEditorSettings (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:512989)
```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-copy-with-line-numbers 0.1.0 
atom-debug-ui 1.0.4 
atom-ide-ui 0.13.0 
atom-react 1.0.0 
atom-storm-ui 2.0.1 
atom-typescript 14.1.2 
autocomplete-modules 2.3.0 
busy-signal 2.0.1 
chlorine 0.10.2 
clojure-lsp-adapter 0.1.0 
clojure-plus 0.3.0 
copy-path 0.5.1 
docblockr 0.13.7 
duplicate-removal 0.1.3 
emmet 2.4.3 
eslint-fixer 1.3.0 
file-icons 2.1.46 
git-blame 1.8.0 
git-control 0.9.0 
git-log 0.4.1 
git-time-machine 2.1.0 
grammar-token-limit 0.1.1 
highlight-selected 0.17.0 
hyperclick 0.0.0 
ide-css 0.3.5 
ide-html 0.6.2 
ide-json 0.2.1 
ide-kotlin 0.5.0 
ide-php 0.7.18 
ide-r 0.1.8 
ide-typescript 0.9.1 
ide-yaml 0.7.1 
ink 0.12.5 
intentions 1.1.5 
jquery-snippets 11.0.0 
js-refactor 0.8.1 
language-babel 2.85.0 
language-kotlin 0.5.0 
lemmings 1.3.0 
linter 3.2.3 
linter-clojure 1.2.0 
linter-eslint 8.5.5 
linter-jshint 3.1.19 
linter-jsonlint 1.4.0 
linter-kondo 1.2.0 
linter-kotlin 0.6.0 
linter-php 1.6.1 
linter-ui-default 2.4.1 
lisp-paredit 0.8.0 
local-history 4.3.1 
merge-conflicts 1.4.5 
minimap 4.39.4 
minimap-git-diff 4.3.6 
minimap-hide 0.3.0 
minimap-linter 2.2.2 
minimap-pigments 0.2.2 
minimap-split-diff 0.3.7 
multi-cursor 3.0.0 
open-git-modified-files 0.2.4 
parinfer 1.24.1 
php-composer-completion 0.3.4 
php-cs-fixer 4.2.0 
php-debug 0.3.5 
php-hyperclick 1.2.1 
pigments 0.40.6 
proto-repl 1.4.24 
proto-repl-charts 0.4.1 
proto-repl-sayid 0.1.4 
pull-request 0.2.1 
rainbow-delimiters 2.1.2 
react-function-to-class 0.2.4 
react-redux-atom-snippets 0.7.2 
refactor 0.11.5 
set-syntax 0.4.0 
split-diff 1.6.1 
swackets 0.35.0 
symbols-tree-view 0.14.0 
sync-settings 5.2.1 
tab-foldername-index 3.3.2 
tabs-closer 0.16.0 
teletype 0.13.4 
todo 0.6.0 
tool-bar 1.4.2 
tree-view-copy-relative-path 1.2.0 
```

**Comment by aminya** [comment]
I spent a lot of time trying to find the reason, but I don't know why this happens. I will add some naive null checks for now.

**Comment by KalAvroniev** [comment]
Issues have gotten worst after latest release 4.39.5. It now crashes Atom when reopened and I can see a new bug just before the crash. Something to do with ParentNode of null

**Comment by aminya** [comment]
@KalAvroniev Could you install a dev version so we can find the error better?

```
apm uninstall minimap
``` 

Somewhere:
```
git clone https://github.com/atom-minimap/minimap/
cd minimap
apm link .
apm install
npm run build.readable
```

**Comment by KalAvroniev** [comment]
I think just uninstalling and installing fixed the issues.

**Comment by aminya** [comment]
I hope so! Let me know if it happens again 👍🏻
