### ISSUE TITLE
 Failed to activate the minimap-cursorline package

### ISSUE THREAD

**Issue by Astropoeta** [atom-minimap/minimap#778]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [minimap-cursorline](https://github.com/atom-minimap/minimap-cursorline) package 1.0.2

### Stack Trace

Failed to activate the minimap-cursorline package

```
At Cannot read property 'decorateMarker' of undefined

TypeError: Cannot read property 'decorateMarker' of undefined
    at ei.decorateMarker (/packages/minimap/dist/main-91f6e642.js:1:94758)
    at MinimapCursorLineBinding.handleMarker (/packages/minimap-cursorline/lib/minimap-cursorline-binding.js:20:35)
    at /packages/minimap-cursorline/lib/minimap-cursorline-binding.js:14:9
    at Array.forEach (<anonymous>)
    at TextEditor.observeCursors (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:8551)
    at /packages/minimap-cursorline/lib/minimap-cursorline-binding.js:13:38)
    at /packages/minimap-cursorline/lib/minimap-cursorline.js:42:20
    at /packages/minimap/dist/main-91f6e642.js:1:15912
    at Map.forEach (<anonymous>)
    at /packages/minimap/dist/main-91f6e642.js:1:15899)
    at Object.activatePlugin (/packages/minimap-cursorline/lib/minimap-cursorline.js:36:44)
    at ce (/packages/minimap/dist/main-91f6e642.js:1:10782)
    at de (/packages/minimap/dist/main-91f6e642.js:1:10693)
    at /packages/minimap/dist/main-91f6e642.js:1:11680
    at Config.observeKeyPath (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:335520)
    at Config.observe (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:330002)
    at pe (/packages/minimap/dist/main-91f6e642.js:1:11664)
    at /packages/minimap/dist/main-91f6e642.js:1:10118)
    at Object.consumeMinimapServiceV1 (/packages/minimap-cursorline/lib/minimap-cursorline.js:21:16)
    at Provider.provide (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:1093689)
    at ServiceHub.consume (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3653929)
    at Package.activateServices (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3662214)
    at Package.activateNow (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3658969)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1191622)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:384090)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:382841
    at TextEditorRegistry.updateAndMonitorEditorSettings (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:512989)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete-python 1.17.0 
busy-signal 2.0.1 
export-html 3.1.0 
file-icons 2.1.46 
highlight-selected 0.17.0 
Hydrogen 2.14.6 
hydrogen-python 0.0.8 
hyperclick 0.1.5 
indent-detective 0.4.0 
indent-guide-improved 1.4.13 
ink 0.12.5 
intentions 1.1.5 
julia-client 0.12.6 
language-julia 0.21.0 
language-latex 1.2.0 
latex-completions 0.3.6 
linter 3.2.3 
linter-flake8 2.4.0 
linter-julia 0.8.3 
linter-ui-default 2.4.1 
minimap 4.39.5 
minimap-codeglance 0.4.7 
minimap-cursorline 1.0.2 
minimap-find-and-replace 5.0.8 
minimap-git-diff 4.3.6 
minimap-hide 0.3.0 
minimap-highlight-selected 4.6.5 
minimap-linter 2.2.2 
python-autopep8 0.1.3 
script 3.29.3 
terminus 4.1.1 
tool-bar 1.4.2 
uber-juno 0.3.0 
```

**Comment by UziTech** [comment]
The error stack trace looks like the error is coming from minimap not minimap-cursorline. It seems minimap trys to add markers before the minimapElement is available.

**Comment by UziTech** [comment]
@aminya we should figure out how to get source maps working so these stack traces are easier to understand.

**Comment by aminya** [comment]
I know exactly where the error comes from. 
https://github.com/atom-minimap/minimap/blob/82de793b94e93567f88f68b33e6aecbf90fd6856/lib/minimap.js#L1153



P.S: Fixing source maps is a good separate issue. I think Electron 9 has better support for them.

**Comment by aminya** [comment]
I have a fix in mind, which might solve this issue. I will try that.
