### ISSUE TITLE
Coadload Error

### ISSUE THREAD

**Issue by danhamill** [atom-minimap/minimap#808]
When I try an install minimap using the cli, I see a `coadload` error:

```
(py39) C:\Local_Software\AtomPortable_1.38.2\App\Atom\resources\cli>apm install minimap
Installing minimap to C:\Users\l2edhddh\.atom\packages failed

npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://codeload.github.com/atom-minimap/minimap/legacy.tar.gz/refs/tags/v4.39.14 failed, reason: getaddrinfo ENOTFOUND codeload.github.com codeload.github.com:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\l2edhddh\.atom\.apm\_logs\2022-04-26T16_56_17_096Z-debug.log
```
### Full Log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Local_Software\\AtomPortable_1.38.2\\App\\Atom\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Local_Software\\AtomPortable_1.38.2\\App\\Atom\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\l2edhddh\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\l2edhddh\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/minimap/versions/4.39.14/tarball',
1 verbose cli   '--runtime=electron',
1 verbose cli   '--target=2.0.18',
1 verbose cli   '--dist-url=https://atom.io/download/electron',
1 verbose cli   '--arch=ia32',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v8.9.3
4 verbose npm-session 21b3cd99962d3583
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for https://www.atom.io/api/packages/minimap/versions/4.39.14/tarball request to https://codeload.github.com/atom-minimap/minimap/legacy.tar.gz/refs/tags/v4.39.14 failed, reason: getaddrinfo ENOTFOUND codeload.github.com codeload.github.com:443
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 1226ms
10 verbose type system
11 verbose stack FetchError: request to https://codeload.github.com/atom-minimap/minimap/legacy.tar.gz/refs/tags/v4.39.14 failed, reason: getaddrinfo ENOTFOUND codeload.github.com codeload.github.com:443
11 verbose stack     at ClientRequest.req.on.err (C:\Local_Software\AtomPortable_1.38.2\App\Atom\resources\app\apm\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
11 verbose stack     at emitOne (events.js:116:13)
11 verbose stack     at ClientRequest.emit (events.js:211:7)
11 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:387:9)
11 verbose stack     at emitOne (events.js:116:13)
11 verbose stack     at TLSSocket.emit (events.js:211:7)
11 verbose stack     at emitErrorNT (internal/streams/destroy.js:64:8)
11 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
12 verbose cwd C:\Users\l2edhddh\AppData\Local\Temp\1\apm-install-dir-122326-35396-edttob.4t7h7
13 verbose Windows_NT 10.0.19042
14 verbose argv "C:\\Local_Software\\AtomPortable_1.38.2\\App\\Atom\\resources\\app\\apm\\bin\\node.exe" "C:\\Local_Software\\AtomPortable_1.38.2\\App\\Atom\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\l2edhddh\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\l2edhddh\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/minimap/versions/4.39.14/tarball" "--runtime=electron" "--target=2.0.18" "--dist-url=https://atom.io/download/electron" "--arch=ia32" "--global-style"
15 verbose node v8.9.3
16 verbose npm  v6.2.0
17 error code ENOTFOUND
18 error errno ENOTFOUND
19 error network request to https://codeload.github.com/atom-minimap/minimap/legacy.tar.gz/refs/tags/v4.39.14 failed, reason: getaddrinfo ENOTFOUND codeload.github.com codeload.github.com:443
20 error network This is a problem related to network connectivity.
20 error network In most cases you are behind a proxy or have bad network settings.
20 error network
20 error network If you are behind a proxy, please make sure that the
20 error network 'proxy' config is set properly.  See: 'npm help config'
21 verbose exit [ 1, true ]
```

**Comment by UziTech** [comment]
Is this only happening with minimap? If it is not it seems like an apm issue

**Comment by danhamill** [comment]
It also happens when I click `code -> Download Zip` from the minimap repo home page:

![image](https://user-images.githubusercontent.com/11522898/165401783-8b538a5b-5d32-48a0-b324-eb5c0a89e940.png)

![image](https://user-images.githubusercontent.com/11522898/165401842-37b14fb9-f340-4da1-9c43-26bbe30ee2f3.png)

**Comment by UziTech** [comment]
That seems like a GitHub issue.

**Comment by danhamill** [comment]
I am having problems on other repos and do not think it is related to minimap.  

Likely an issue with the network security at my work.

**Comment by danhamill** [comment]
Or likely a network security issue at my work.  I am having issues on
other repos too.  

Since it seems to be related to something outside of minimap, I don't
see any reason to keep this issue open.


On April 26, 2022, nnk2193 ***@***.***> wrote:
> That seems like a GitHub issue.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/atom-minimap/minimap/issues/808#issuecomment-
1110338785>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ACX5GUX2ADSZ5CCOY2PTO53VHB23DANCNFSM5UMPSEWA>.
You are receiving this because you authored the thread.Message ID:
***@***.***>
